### ISSUE TITLE
X_POSSIBLE_NAMES, Y_POSSIBLE_NAMES: too long and drawn-out

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10019]
### Feature description

Just the other day I was doing
```
gdal_grid -l 0 -a nearest -oo X_POSSIBLE_NAMES=field_1 -oo Y_POSSIBLE_NAMES=field_2 -zfield field_3 CSV:0.locations 0.tif
```
and wondering why my code was going off the screen.

And then it dawned on me.

That `-oo X_POSSIBLE_NAMES=field_1 -oo Y_POSSIBLE_NAMES=field_2`
stuff has got to go.
Why not just use `-oo X=field_1 -oo Y=field_2` or something?
No good? How about `-oo nX=field_1 -oo nY=...`?
Something, anything, other than long drawn-out names that couldn't be drawn-out any longer.

Sure, keep `X_POSSIBLE_NAMES` et al. around for compatibility's sake, but do please start introducing more reasonably sized versions.

**Comment by jratike80** [comment]
Why? I guess that the world was totally open for the developer when the feature was added https://github.com/OSGeo/gdal/commit/eb7b60b5093b896063cfe18b6b0b7fec3821c212, and the author decided to use an open option name that describes rather clearly what it does: `X_POSSIBLE_NAMES` etc. 

`-oo X=field_1` would not tell that the possible names option can contain a list, and obviously that was an important feature for the author. Maybe they had real world examples with CSV data using "lon" or "long" or "longitude" or "x" or anything.

Perhaps the X and Y names could have a default value like GEOM_POSSIBLE_NAMES does (wkt). However, X/Y and lat/lon(g) are perhaps about as common.

I would say that it is not a too big deal to write X_POSSIBLE_NAMES and Y_POSSIBLE_NAMES (just did it), especially because they are easy to remember and thus write correctly. If one needs to use them frequently they can be written into an optfile that has a short name and then referred as `--optfile 2`. That saves even more typing. I think that CSV is so messy format that it is good that at least the opening options are clear https://gdal.org/drivers/vector/csv.html#open-options.

**Comment by jidanni** [comment]
>  least the opening options are clear https://gdal.org/drivers/vector/csv.html#open-options.

Wow, it turns out all of them are long. That's too much trimming for one barbershop!
