### ISSUE TITLE
gdal_contour: warn if given invalid  -i and -off

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10014]
### Feature description

In https://github.com/OSGeo/gdal/pull/10013 we give examples of invalid gdal_contour -i and -off values.

It would be great if invalid gdal_contour -i and -off values produced a warning.

**Comment by jratike80** [comment]
Test data for re-producing the confusing result would be appreciated.

**Comment by jidanni** [comment]
gunzip [0.locations.gz](https://github.com/OSGeo/gdal/files/15456340/0.locations.gz)
gdal_grid -l 0 -a nearest -oo X_POSSIBLE_NAMES=field_1 -oo Y_POSSIBLE_NAMES=field_2 -zfield field_3 CSV:0.locations 0.tif
for i in 25 50 75 100 200; do gdal_contour 0.tif $i-0.contours.kmz -i $i; done

This will give you several kmz's that all look the same, except for the -i 200 one.

Sure, you will say
> Zoom real close in to your (folded!) contour lines and also check the sizes of your kmz's. -i is doing its job.

Well yes, but to the "average user", -i appears to have no affect until -i 200.

**Comment by jratike80** [comment]
The result looks like this with 10 m interval. By the first sight it looks there are only 100 m contours.

<img width="190" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/61fba073-9b42-4d6c-aa9c-8203581b1343">

Close zoom reveals that the 10 m contours are there but there is really something odd in those.

<img width="75" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/bcf5d1e4-ab52-4d6c-9414-1e6bc3f45127">

Somehow I feel that it may be hard to analyze the data so that a warning about -i and -off could be thrown.

If you want more artistic result, use invdist instead of nearest with gdal_grid.

<img width="181" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/4106c470-0148-4303-b000-570f7e5fa785">

**Comment by jidanni** [comment]
I think I created a set of razor blades with steep valleys between them, instead of what I imagined: the same set with a cloth draped over it. Oh well. Back to the drawing board.
