### ISSUE TITLE
gdalwarp -ovr {absolute_value} doesn't influence choice of output resolution

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#10174]
Cf https://lists.osgeo.org/pipermail/gdal-dev/2024-June/059079.html

``gdalwarp -ovr 0 -overwrite input.tif output.tif`` should take into account the resolution of the 1st overview level of the input dataset to compute the output dataset

**Comment by jratike80** [comment]
Probably only when `-ts` or `-tr` are not defined, like in the example command.

**Comment by elpaso** [comment]
I had a look to the issue, first of all there here is a failing test case:

```patch

diff --git a/autotest/utilities/test_gdalwarp.py b/autotest/utilities/test_gdalwarp.py
index df8cb2d65b..d9c6cf9f1f 100755
--- a/autotest/utilities/test_gdalwarp.py
+++ b/autotest/utilities/test_gdalwarp.py
@@ -1113,6 +1113,14 @@ def test_gdalwarp_40(gdalwarp_path, tmp_path):
     assert ds.GetRasterBand(1).Checksum() == cs_ov0
     ds = None
 
+    # Should select overview 0
+    gdaltest.runexternal(f"{gdalwarp_path} {src_tif} {dst_tif} -overwrite -ovr 0")
+
+    ds = gdal.Open(dst_tif)
+    assert ds.GetRasterBand(1).Checksum() == cs_ov0
+    ds = None
+
+
```

What happens here is that the output raster resolution is calculated from the input raster without taking care of the specified overview (this does not happen with `-oo OVERVIEW_LEVEL=0` because in that case the overview level is applied to the input raster before entering the logic that tries to calculate the output resolution, so what the internal function "sees" is already the resolution of the selected overview.

Now I am struggling to find what is the best solution without breaking the API (`GDALSuggestedWarpOutput2` is exposed) and without duplicating a lot of code.

The logic which determines the resolution based on the overview level is deep inside `GDALWarpDirect` and it would need to be replicated for the input raster in the main function of the binary or the overview level should be passed as an additional argument to `GDALSuggestedWarpOutput2`.

**Comment by rouault** [comment]
isn't it a matter of moving code a bit inside GDALWarpDirect() so that the call to CreateOutput() done at line 2507 works on the poSrcOvrDS compute at line 2854 instead of the original pahSrcDS[] ?
Or perhaps simpler, in CreateOutput(), if psOptions->nOvLevel >= 0, use the result of GDALCreateOverviewDataset(pahSrcDS[i], psOptions->nOvLevel, /* bThisLevelOnly = */ true)  instead of pahSrcDS[i] ?
