### ISSUE TITLE
Improve Launder algorithm for uppercase letters

### ISSUE THREAD

**Issue by latot** [OSGeo/gdal#10918]
### Feature description

Actually, launder helps a lot to format some columns, I just think some cases ends to be off like:

"HiBye" -> "hibye"

I think would be nice transform this to "hi_bye".

So I propose two new rules for this algorithm:

- If after a lowercase there is a upper case, add a "_" in the middle
- If after a uppercase there is an uppercase, transform the second uppercase to lower case

The idea would be transform things like:

"HiByCMP" -> "hi_by_cmp"
"JKLaBye" -> jklma_by"

The second rule I'm not very sure if there is a better idea, but add both of them I think would simplify and helps a lot in how to read the new field's names.

I know this option is at least enabled for PG and SQLite.

Thx!

### Additional context

I think, Lauder helps a lot when we have columns without the right names, or weird symbols, so the proposal is help in this circumstances, I had several times found dbs with this type of formats using upper case, which needs to be formatted every time.

**Comment by jratike80** [comment]
I do not support this idea. For my mind the main advantage of laundering is that user does not need to use double quotes every time and they can do `select hibye from table` instead of `select "HiBye" from table`.  The minimum to achieve that goal is to use lower case (or upper case if the database is Oracle), and convert some characters which have a special meaning for the database (like "-" and "#" ) into something else. 

Certainly there are users who would like to see `hi_by_cmp` for easier readability. Some other users would see such changes unexpected and undesired.

Fortunately it is possible to rename the fields freely with SQL `select "HiByCMP"  as "hi_by_cm_p"`. Sure is requires more hand writing, but it is a totally usable workaround for those who are not satisfied with the default behavior. In ogr2ogr this can be done via the `-sql` option.

**Comment by latot** [comment]
Would be very annoying so much changes, and we can do it manually, still we would need a script to run this on larger dbs.

Actually there is cases like LAUNDER_ASCII of PG to handle even more types of column formats, maybe could worth create a keyword like LAUNDER_TYPE with a string as input, where we can choose how to format the columns.

**Comment by jratike80** [comment]
Are you aware of `--optfile` https://gdal.org/en/latest/programs/raster_common_options.html#cmdoption-optfile? That might be an option for a script, and rather easy to re-use if you have many tables with same attributes.
