### ISSUE TITLE
Support for S-100

### ISSUE THREAD

**Issue by felixdivo** [OSGeo/gdal#1092]
The GDAL-Team could consider supporting the "new" (2010) [IHO S-100](https://www.iho.int/iho_pubs/standard/S-100/S-100_Ed_3/S-100_Edition_3.0.0.pdf) standard, which will some day replace the already supported S-57 standard.

**Comment by jratike80** [comment]
There has been considerations about that http://osgeo-org.1560.x6.nabble.com/gdal-dev-Support-for-S-100-and-S-102-td5370370.html.
The amount of work that will be needed for making a new driver is relatively large. There does not exist a permanent GDAL-Team that stands ready for such work but let's hope that some big enough agent needs the driver, pops up and developes it by themselves. Commercial support is also available.

You feature request is valid but it is unlikely that just by filing it as a new issue will lead to any big and fast progress.

**Comment by jratike80** [comment]
Something new in https://github.com/OSGeo/gdal/pull/8569

**Comment by oysstu** [comment]
> Something new in [#8569](https://github.com/OSGeo/gdal/pull/8569)

That's an implemetation of s102, which is a raster format intended for bathymetry. S100 is a vector format.

**Comment by kannes** [comment]
> > Something new in [#8569](https://github.com/OSGeo/gdal/pull/8569)
> 
> That's an implemetation of s102, which is a raster format intended for bathymetry. S100 is a vector format.

S-100 is the data model for a whole bunch of S-1xx standards, both vector and raster and potentially in many different formats (ISO/IEC 8211, GML, GeoTIFF, HDF5, ...)

https://iho.int/uploads/user/pubs/standards/s-100/S-100%20Ed%205.2.1_FINAL.pdf -> "Part 10 – Encoding Formats"

I assume @felixdivo meant S-101.

-----

I still think this issue was ok to be closed in general (or have it changed to S-101?). It would make more sense to have issues for specific S-1xx formats.

Right now, GDAL supports reading S-102, S-104 and S-111.

S-101 would be great but someone's got to fund it I guess :)

**Comment by felixdivo** [comment]
Hey @kannes, thanks for digging this out! You're right, the different "Encoding Formats" make it a bit tricky to support the "whole" standard. I was indeed thinking about S-101, but honestly, I have at least forgotten about the other S-1XX variants.

I have since moved on and no longer need the software support. So yeah, let's keep this closed until someone with funding or engineers is willing to implement it.
