### ISSUE TITLE
Terminal progress bar: add estimated remaining time

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#11100]
It could be cool to improve GDALTermProgress for "long jobs" (perhaps those with an estimated time > 1 minute) to also display the number of remaining HH:MM and/or the estimated datetime of completion). We should be careful to do that in a way that doesn't impact performance too much (i.e. not calling gettimeofday() hundreds of time per seconds)

**Comment by jratike80** [comment]
Might be cool, even some processes are not linear, they may for example be fast till `0...10...20...30...40...50.` and progress slows down after that, and some others are doing something on the background even after `0...10...20...30...40...50...60...70...80...90...100 - done.`, maybe writing some temporary data into final format.
Windows users might even enjoy seeing how long it **took** because there is no simple equivalent for the Linux "time".

**Comment by rouault** [comment]
> Windows users might even enjoy seeing how long it **took**

could be the final update of the progress bar

That said, you can workaround that with --config CPL_DEBUG=ON --config CPL_TIMESTAMP=ON and doing the subtraction before the last and first timestamps

**Comment by jratike80** [comment]
One more nice trick, thanks. Never noticed CPL_TIMESTAMP config even it is documented.
