### ISSUE TITLE
Uniform name for a parameter that defines spatial, axis oriented limits

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#11526]
### What is the bug?

Could it be possible to find a common name and usage syntax for defining bbox/extent/envelope for all raster and vector sub-programs? The candidates `bbox` and `extent` are so obvious that it was hard to make a title that avoids them ;)

Somehow "extent" feels like something that defines a dataset and "bbox" like something that is used in queries. A bbox query returns data, and the extent of the new dataset is not necessarily the same than the bbox that was used in a query. So there might be place for both extent and bbox, but is that potential semantic difference meaningful?

I made a short OGC standard review: OGC API Features about vectors, and OGC API Coverages draft about rasters. Surprisingly they agree on this.  BBOX is used in the queries, but bbox appears also in the documents which describe a dataset.  A dataset has an extent, and the spatial extent is expressed as bbox. A temporal extent may also exist.

```
 "extent": {
        "spatial": {
           "bbox" : [ [ 7.01, 50.63, 7.22, 50.78 ] ],
           "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
        },
        "temporal": {
           "interval" : [ [ "2010-02-15T12:34:56Z", "2018-03-18T12:11:00Z" ] ]
        } 
```

Maybe one parameter, `bbox`, used as `minx,miny,maxx,maxy` could work for all GDAL cli subprograms? Naturally derived options like `source_bbox` and `target_bbox` would be needed.

### Steps to reproduce the issue

Future plans.

### Versions and provenance

Future versions.

**Comment by sgillies** [comment]
@jratike80 what about rotated extents? For example, the case of translating a rectilinear raster to a rotated raster?

In Rasterio, I'm thinking about an extent as being a (height, width) tuple plus an affine transformation matrix (a 6-tuple): https://github.com/rasterio/rasterio/issues/3009. I haven't thought about generalizing this to vectors.

**Comment by jratike80** [comment]
> what about rotated extents? 

How can we use rotated extents with GDAL command line utilities, now or in the future?

**Comment by rouault** [comment]
> How can we use rotated extents with GDAL command line utilities, now or in the future?

The --extent parameter of gdal raster edit  ultimately sets a geotransform.  So we could potentially provide --set-geotransform=gt0,gt1,gt2,gt3,gt4,gt5, but only the most enlightened minds will be able to make sense of that... It doesn't seem to me to rank high in the priority list of what users routinely need :-)

**Comment by mdsumner** [comment]
I wanted to raise just usage, in R there's a pretty loose convention that "extent" means xmin,xmax,ymin,ymax (I personally don't like to interleave my dimensions so I'm in this camp with {raster} and {terra}), and "bbox" means xmin,ymin,xmax,ymax - and that has become the defacto standard from the modern Python+Pangeo community after a fair bit of churn.   There's so much push for multidim now but why would anyone put x0,y0,z0,t0  x1,y1,z1,t1 ?? I don't understand the interleave and I don't think that way. (Intervals define the region to me, not points on the margin, but at any rate that's how I'd frame it for generality)

I just wouldn't like to see "extent" used where it means interleaved form, although that is already established in "-te". I'd rather reproject used "--bbox".   

I agree with Even that actual rotation in output is extremely arcane and I've never encountered the need  for *output* and even for input it's very rare, an explicit geotransform arg is ideal and normal use can use four numbers and *size* or *resolution* rather than mixing these together.

**Comment by rouault** [comment]
cf https://github.com/OSGeo/gdal/pull/11531

**Comment by sgillies** [comment]
I agree that `min, max, ...` bbox is what people want at least 80% of the time, and for rectilinear rasters is the same thing as its extent.

**Comment by rouault** [comment]
aren't we going to be burnt alive at the stake by OGC folks (and GeoJSON ones, right ?) if we use bbox without the xmin,ymin,xmax,ymax order...  As much as I hate standards those days, I'd hope we can rely on established ones for that...

**Comment by sgillies** [comment]
Right! I mis-typed. GeoJSON is `left, bottom, right, top`.
