### ISSUE TITLE
drv_geojson.html documentation error

### ISSUE THREAD

**Issue by nmtoken** [OSGeo/gdal#1155]
Under the section RFC 7946 write support, there is a section that says:

> Coordinates must be in longitude/latitude over the WGS 84 ellipsoid, hence if the spatial reference system specified at layer creation time is not EPSG:4326, on-the-fly reprojection will be done by the driver.

This appears to be incorrect, as it implies that EPSG:4326 is WGS 84 ellipsoid in longitude/latitude order, however it is not.  [EPSG:4326](https://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::4326&reportDetail=short&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code&title=EPSG:4326) is WGS 84 ellipsoid in latitude/longitude order

**Comment by rouault** [comment]
One may argue a long time about this, but one could say that GDAL applies an implicit coordinate mapping function, to switch from longitude/latitude to latitude/longitude

**Comment by nmtoken** [comment]
I suppose it depends what it is we might argue on :)

I'm not sure you can argue about the coordinate order as defined by EPSG, they are the authority on the  coordinate reference system EPSG:4326.  It may well be however that GDAL does an implicit coordinate axis switch, if it is the case, it should be documented (better).

**Comment by jratike80** [comment]
Could you suggest exact wording? What happens is probably axis mapping, not switch, because there are many other formats which use longitude-latitude order natively in a similar way than GeoJSON (GML2, WKT/EWKT, OpenJUMP JML, MapInfo MIF etc.).

**Comment by jratike80** [comment]
With WKT I meant the well known text presentation of geometries as in the Simple features standard http://portal.opengeospatial.org/files/?artifact_id=25355. But I do know also that MySQL developers in the latest version have decided to make WKT geometries axis order aware https://mysqlserverteam.com/axis-order-in-spatial-reference-systems/.

A mail from today that deals also with the axis order question https://lists.osgeo.org/pipermail/gdal-dev/2018-December/049501.html.

**Comment by jratike80** [comment]
I have started to think that the whole sentence could be re-phrased. The effects of following RFC 7946 are from the user's point of view 
a) -t_srs given by the user is omitted if it is not EPSG:4326
b) even without defining -t_srs data will be automatically converted into longitude/latitude over the WGS 84 ellipsoid (CRS:84)
c) b) means that data which are not natively in  EPSG:4326 (of EPSG:4258) will be re-projected, otherwise only the order of coordinates is set to longitude-latitude

That the order of coordinates is longitude-latitude is not a change to GeoJSON 2008 specification but the forced re-projection is. I am sure that as an experienced editor you can write a nice and compact sentence that makes clear for GDAL users in which circumstances such re-projection of data occurs that will lead to change in coordinate values.
