### ISSUE TITLE
Building GDAL With MinGW - Error while executing "make"

### ISSUE THREAD

**Issue by elenaVal** [OSGeo/gdal#1170]
Hello,

I am very new to GDAL library. I am trying to build GDAL from source using MinGW for windows to get libgdal-1.dll, libgdal-1.dll.a. 
I follow the instructions given on the GDAL website https://trac.osgeo.org/gdal/wiki/BuildingWithMinGW

I install the MinGW and using msys configure the GDAL source using "./configure" command. but when i give the "make" command it gives me error:

> 
> make[1]: *** [cpl_vsil_gzip.lo] Error 1
> make[1]: Leaving directory `/c/gdal240/gdal-2.4.0/port'
> make: *** [port-target] Error 2

Do you have any idea of how to solve this issue?
Thank you in advance,

PS. My main goal is to build the GDAL lib in order to link it with a qt (c++) project. So, if you think that there is any other way to do this, please give me some feedback.

**Comment by rouault** [comment]
There are binary builds of GDAL at http://gisinternals.com/

**Comment by yvrig** [comment]
> There are binary builds of GDAL at http://gisinternals.com/

Are you suggesting that those MSVC binaries are working with MinGW as the OP was trying to do? Of course for the OP it might be possible to switch compilers, but that is not an option for me.
It would be very helpful if there were understandable instructions on how to setup GDAL with MinGW on Windows (preferably with Qt). Thanks!

**Comment by rouault** [comment]
> Are you suggesting that those MSVC binaries are working with MinGW as the OP was trying to do?

What is OP ? I believe MSVC binaries should be OK for use with MinGW compiled programs as long as you stick with the GDAL C API.

Maybe you could output the full error with mingw, because what you provided is just the end, the interesting part must be a bit before, with a line like "error: blablabla"

**Comment by yvrig** [comment]
OP -> Original Post(er)
That a great idea, I had not thought of using just the C API, thanks!

Some of prerequisite tools mentioned on https://trac.osgeo.org/gdal/wiki/BuildingWithMinGW refer to dead links. Since using Qt I think I would also need a newer GCC version (7.3.0). There is not really an explanation on what to do (just "prepare" everything and than run a command), so it just became a mess every time..

**Comment by jamesmcclain** [comment]
I do not know how helpful this will be (or if you are still interested), but it transpires that Fedora has a [mingw-gdal package](https://apps.fedoraproject.org/packages/mingw-gdal).  The most recent version appears to be 2.3.2, but the [source RPM](https://kojipkgs.fedoraproject.org//packages/mingw-gdal/2.3.2/6.fc30/src/mingw-gdal-2.3.2-6.fc30.src.rpm) linked-to from [this page](https://koji.fedoraproject.org/koji/buildinfo?buildID=1209094) appears to contain the patches that they applied to upstream.

This is (probably) far from a complete solution, but could provide a starting point if you want to try to compile a more recent version with mingw.

For my particular issue, I ended up taking Even's advice and sticking to the C API.

**Comment by rouault** [comment]
Closing as invalid / wontfix
