### ISSUE TITLE
GML: SRS lost when using ogr2ogr and GML driver

### ISSUE THREAD

**Issue by GreatEmerald** [OSGeo/gdal#1219]
## Expected behavior and actual behavior.

Using ogr2ogr to convert any file into a GML results in a GML with no SRS. (Worse, this also propagates to anything using the library, see https://github.com/r-spatial/sf/issues/958 )

## Steps to reproduce the problem.

```bash
ogr2ogr -f GML nc.gml nc.shp
ogrinfo -al nc.shp
ogrinfo -al nc.gml
```

The coordinate system is lost.

The shapefile is from https://github.com/r-spatial/sf/tree/master/inst/shape (but anything else doesn't work just as well)

## Operating system

Ubuntu 16.04 64 bit, Windows 7

## GDAL version and provenance

2.1.3

**Comment by rouault** [comment]
The SRS is not completely lost. It is encoded in the .gml file per features (at least with recent enough GDAL version, >= 2.3.0), but the GML driver is conservative on reading and doesn't retrieve it since it would require a full initial scan of the file to make sure that the SRS is the same on all features.

**Comment by GreatEmerald** [comment]
Ah, yes, I tested with GDAL 2.3.2 now and indeed the SRS is now put into the file. And reading with `-oo FORCE_SRS_DETECTION=YES` does load it correctly. Still, that's a bit unfortunate, since that means that such files, when created, cannot be read in properly by e.g. QGIS.

**Comment by jratike80** [comment]
QGIS allows to select FORCE_SRS_DETECTION=YES/NO when opening GML data.
Tested with QGIS 3.17.
