### ISSUE TITLE
gdal.FillNodata distance of 1 used only some of adjacent pixels to fill NODATA values on edge

### ISSUE THREAD

**Issue by ValerieAnne563** [OSGeo/gdal#1228]
`gdal.FillNodata` with `maxSearchDist = 1` seems to have only considered some of the immediately adjacent pixels. Is neighbor selection near the edge of an array heavily weighted in one direction more than the other?

## Expected behavior and actual behavior.
In this example, the filled values seem to use values from the same column, but are unaffected by their neighbor in the same row. The output lists the array before and after calling gdal.FillNodata.

```
[[   50     4     8    50]
 [  100 -9999 -9999   100]]
[[ 50   4   8  50]
 [100   4   8 100]]
```

`maxSearchDist=2` did the following
```
[[   50     4     8    50]
 [  100 -9999 -9999   100]]
[[ 50   4   8  50]
 [100   6  54 100]]
```

## This script will reproduce, change maxSearchDist on line 9

```
#!/usr/bin/env python
from osgeo import gdal
import numpy as np

output_nodata = -9999
dt = gdal.GDT_Int16
out_filename = "fills.tif"

maxSearchDist = 1

def create_raster(filename, array, dt, nodata=output_nodata):
    array = np.array(array)
    cols = array.shape[1]
    rows = array.shape[0]

    driver = gdal.GetDriverByName('GTiff')
    outRaster = driver.Create(filename, cols, rows, 1, dt)
    outband = outRaster.GetRasterBand(1)
    outband.WriteArray(array)
    outband.SetNoDataValue(nodata)

    outband.FlushCache()

    return(outRaster)

if __name__=='__main__':

    ds = create_raster(out_filename, [[4, 4, 8, 4], [16, output_nodata, output_nodata, 16]], dt)

    print ds.GetRasterBand(1).ReadAsArray()
    gdal.FillNodata(targetBand = ds.GetRasterBand(1), maxSearchDist = maxSearchDist, maskBand = None, smoothingIterations = 0)
    print ds.GetRasterBand(1).ReadAsArray()
        # != 1:
        # raise Exception('warp failed')

    gdal.Unlink(out_filename)

```

## Operating system

Ubuntu 16.04.5 LTS

## GDAL version and provenance

GDAL version 2.4.0

**Comment by rouault** [comment]
@ValerieAnne563 I've merged in master https://github.com/OSGeo/gdal/pull/1270 which bring a few small fixes in that area I foun while investigating the implementation, while perhaps not completely delivering the result you expect. The fundamental thing to understand in the algorithm is that for each target pixel to fill, it considers fourth quadrant. Quadrant 0 is the upper-left quadrant, including the line and column of the pixel. Quadrant 1 is the upper-right quadrant, including the line of the pixel, starting one column at its right. etc. So in your example, for the -9999 on the left, the 4 at top and the 100 at right belong to the same quadrant, and only one value per quadrant is considered for the implementation, and given how the implementation works it starts at 4.
For the other -9999 there was indeed an issue since the 8 above and the 100 at the right below to different quadrants. This is now fixed and it returns
```
[[ 50   4   8  50]
 [100   4  54 100]]
```
