### ISSUE TITLE
//usr/local/lib/libgdal.so: undefined reference to `ompi_mpi_comm_null'

### ISSUE THREAD

**Issue by jiapei100** [OSGeo/gdal#1260]
I failed to build **gdal apps** ? The shared library **libgdal.so** has been successfully built. However, there are still a lot of **ERROR** messages:

```console
make[1]: Entering directory '....../gdal/gdal/apps'
/bin/bash ....../gdal/gdal/libtool --mode=link --silent g++ -L/opt/ogdi/lib -logdi -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi -lgdal -L/opt/ogdi/lib -logdi -lrasterlite2 -lspatialite -L/usr/lib/x86_64-linux-gnu -lxerces-c -lepsilon -lmpi gdalinfo_bin.lo  ....../gdal/gdal/libgdal.la  -o gdalinfo
//usr/local/lib/libgdal.so: undefined reference to `ompi_mpi_cxx_op_intercept'
//usr/local/lib/libgdal.so: undefined reference to `gtSetCSVFilenameHook'
//usr/local/lib/libgdal.so: undefined reference to `MPI::Win::Free()'
//usr/local/lib/libgdal.so: undefined reference to `MPI::Datatype::Free()'
//usr/local/lib/libgdal.so: undefined reference to `MPI::Comm::Comm()'
collect2: error: ld returned 1 exit status
GNUmakefile:82: recipe for target 'gdalinfo' failed
```

**My configuration was:**

```console
./configure --enable-shared LDFLAGS="-L/opt/ogdi/lib -logdi -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi" CPPFLAGS="-I/opt/ogdi/ogdi/include" CXXFLAGS="-Wall -std=c++11" --with-poppler=yes --with-ogdi=yes --with-geos --with-geotiff --with-jpeg --with-png --with-expat --with-libkml --with-xerces --with-openjpeg --with-geos --with-pg --with-curl --with-spatialite=yes --with-rasterlite2=yes --with-expat --with-qhull=yes --with-epsilon=yes  --with-podofo=yes --with-armadillo=yes --with-cryptopp=yes --with-liblzma=yes
```

What did I miss?

**Comment by rouault** [comment]
Why do you need "-L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi" ?

**Comment by tigerfoot** [comment]
I've the same error gtSetCSVFilenameHook with gdal 2.4.1 and geotiff 1.5.0

**Comment by rouault** [comment]
@tigerfoot You may need to apply https://github.com/OSGeo/libgeotiff/commit/f4956251737b29ccc3f6366cd5b21520689f21d9 
Note also that geotiff 1.5.0 is more intended to be used with not-yet released GDAL 2.5.0

**Comment by tigerfoot** [comment]
Thanks @rouault  geotiff 1.5.0 is so appealing with its proj6 support :-)

**Comment by fxcoudert** [comment]
Seeing the same build failure in Homebrew building process: https://github.com/Homebrew/homebrew-core/pull/38399

It makes our life shipping this software so difficult, because versions of related and interdependent projects (gdal, geotiff, proj) are released without concertation, and because the latest stable version of each are not interworking :(

**Comment by rouault** [comment]
> It makes our life shipping this software so difficult, because versions of related and interdependent projects (gdal, geotiff, proj) are released without concertation, and because the latest stable version of each are not interworking :(

It want to correct that it is not true that the projects are released without concertations, and this has been discussed on their mailing lists those past months. I'm a project steering member of the 3 you mention above. Yes PROJ 6 is a breaking change, with a number of technological and functional disruptions, and we are aware that's a complicated situation from a packaging point of view which takes time to solve. Typically,  the ""guaranteed"" working combination is PROJ 6 + libgeotiff 1.5 + GDAL 2.5 (not yet released)

There are also other packages downsteam that are not PROJ 6 ready, so yes we are aware it might take a few months before it can widely be adopted.
I know that Debian has this concept of experimental distribution where packages are uploaded as soon as they are ready, but they won't be able to migrate them to testing until all packages are made PROJ 6 ready.

I apologize for the unwanted breakage of libgeotiff 1.5 with GDAL 2.4.1 which requires https://github.com/OSGeo/libgeotiff/commit/f4956251737b29ccc3f6366cd5b21520689f21d9 (but from a functional point of view, the combination PROJ 6 + libgeotiff 1.5 + GDAL 2.4.1 will be a bit odd, since GDAL will use a different version of the EPSG database than libgeotiff & PROJ)

**Comment by fxcoudert** [comment]
> the combination PROJ 6 + libgeotiff 1.5 + GDAL 2.4.1 will be a bit odd

It is what we will be shipping, since it is at the current time the combination of each project's latest released stable software version. 

It is surprising, from an outsider perspective, disappointing that the concertation between projects does not lead to either:
- simultaneous release of compatible versions
- at least, each project releasing minor versions with partial support (i.e. enough to get things compilable and running, even though they may not be the ideal combination) for other projects' stable releases.

**Comment by rouault** [comment]
>     * simultaneous release of compatible versions

PROJ, libgeotiff and GDAL are just a small part of the whole picture. There's also all other downstream projects to consider, so simultaneous release wasn't possible. And we needed a earlier PROJ release so that it is "shaken" a bit by early adopters to uncover issues due to all the changes that have been done

> at least, each project releasing minor versions with partial support 

would have been technically hard and lead to situations of semi-working/semi-broken state that wouldn't have been usable. compiling is one thing, working properly at runtime is a harder one.

**Comment by rouault** [comment]
libgeotiff 1.5.1 has been released with the '#define SetCSVFilenameHook gtSetCSVFilenameHook' fix

**Comment by tigerfoot** [comment]
Thanks a lot Even

On March 29, 2019 10:03:24 PM GMT+01:00, Even Rouault <notifications@github.com> wrote:
>libgeotiff 1.5.1 has been released with the '#define SetCSVFilenameHook
>gtSetCSVFilenameHook' fix

--
Bruno Friedmann 
Ioda-Net Sàrl www.ioda-net.ch 
Send from my mobile. Please excuse my brevity.

**Comment by frank0123** [comment]
hi，I got the same error except the `gtSetCSVFilenameHook', with proj6 and libgeotiff = 2.1.2. @jiapei100 How did you solve the MPI problem?

**Comment by venabled** [comment]
> Why do you need "-L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi" ?

Just for reference, this is still an issue on Ubuntu 18.04, I think the HDF5 library used in one of the dependencies is compiled with MPI support, and those flags are probably missing from whatever pkg-config file is in there.

**Comment by rouault** [comment]
You may need to install libhdf5-serial-dev instead of libhdf5-dev to avoid the MPI issues
