### ISSUE TITLE
Manipulating OGRSpatialReference object leads to heap corruption

### ISSUE THREAD

**Issue by Reyien** [OSGeo/gdal#1263]
## Expected behavior and actual behavior.
I tried to use OGRSpatialReference object with my project linked to gdal C++ library. I have a crash when releasing that object. In a second time i tried differently and it didn't crash although it implicitly do the same thing. 

## Steps to reproduce the problem.
The code that crash :
`#include <ogr/ogr_spatialref.h>

int main()
{
    OGRSpatialReference* p = new OGRSpatialReference;
    OGRSpatialReference::DestroySpatialReference(p);
    return 0;
}`

The code that does not crash:
`#include <ogr/ogr_spatialref.h>

int main()
{
    OGRSpatialReference* p = reinterpret_cast<OGRSpatialReference *>(OSRNewSpatialReference(nullptr));
    OGRSpatialReference::DestroySpatialReference(p);
    return 0;
}`

## Operating system
windows 8.1 64bits 

## GDAL version and provenance

GDAL v2.2.4 or v2.3.3 (from tag) built with ms vc12 (for 2.2.4) or vc14 (for 2.3.3).

**Comment by rouault** [comment]
It sounds like you have cross-heap issues due to a different C++ runtime (or build options like /Md vs /MD) between your application and GDAL. In the first snipped, you allocate the object with the C++  new operator of your application, but you deallocate it indirectly with the C++ delete operator of GDAL.

**Comment by Reyien** [comment]
thank you for your time :)
