### ISSUE TITLE
ERROR 4: Unable to open EPSG support file gcs.csv.  

### ISSUE THREAD

**Issue by SaowaluckT** [OSGeo/gdal#1302]
How to fix this error 
![image](https://user-images.githubusercontent.com/38277831/53107638-0055ba80-3568-11e9-8740-202691bd21fc.png)
I don't know what caused it, but I think it's happened with I use osgeo.ogr lib.
p.s. I'm just writre python
Thank you 
## Operating system

window 10 64 bit
Python 3.7
## GDAL version and provenance
GDAL-2.3.3

**Comment by rouault** [comment]
You need to set the GDAL_DATA environmenet variable to the path where gcs.csv is installed

**Comment by jamiecook** [comment]
@rouault  - I know this has been closed, but I'm running into the same problem and wondering why this env var needs to be set, given that there is a set of gcs.csv files shipped with the gdal wheel - surely this isn't something that a user would be expected to know about before using basic functionality?

Turns out, you don't... you just need to make sure it's not set wrongly.... In my case I had an old installation of pg that had set this in my environment. Clearing the variable is sufficient to get things working

![image](https://user-images.githubusercontent.com/151124/75939096-0a2d3000-5ed5-11ea-81ca-20996c1facf3.png)
