### ISSUE TITLE
Add GRA_Sum option to gdalwarpkernel

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/gdal#1437]
This feature request is to allow the sum of values to be reported from a gdalwarp operation, using a suggested method `GRA_Sum`. This already done in [gdal/alg/gdalwarpkernel.cpp](https://github.com/OSGeo/gdal/blob/master/gdal/alg/gdalwarpkernel.cpp) for determining `GRA_Average`, i.e., just skip dividing `dfValueReal` or `dfValueImag` by `nCount` around [gdalwarpkernel.cpp#L6002-L6006](https://github.com/OSGeo/gdal/blob/fa2676737e01040b4457b2a637db5e73eb9c744f/gdal/alg/gdalwarpkernel.cpp#L6002-L6006).

(Migrated from: https://trac.osgeo.org/gdal/ticket/6015 from June 2015)

**Comment by rouault** [comment]
To do it properly, this is not as trivial as it appears to be. The current GRA_Average doesn't take into account the weight of each contributing source pixel, so using it to derive a sum would lead to a non-conservation of the total sum. For example imagine you have a 3x1 source image with values 1, 1, 1, and you do a reduction to a 2x1 source image. If you don't take into account the fact that the middle pixel of the source image only intersects 1/2 of the final pixel, then you'd get summed values 2, 2, instead of 1.5, 1.5.
What complicates things is that in the general case where reprojection occurs, the extent of the target pixel reprojected on source pixels is generally not a rectangle. But that would be extra complication. Probably that the rectangle approximation would be a first good step.
