### ISSUE TITLE
MBTile and SQLite 

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/gdal#1504]
The following snipped used by tilexyz QGIS processing algorithm is working for GDAL 2.2 but not for GDAL 2.4.x

issue: https://issues.qgis.org/issues/21958
fix by using sqlite3 instead of ogr: https://github.com/qgis/QGIS/pull/9918

```
import ogr
import gdal
import os

def test1():

  filename="/Users/peter/tmp/tilesxyz/test1.mbtiles"
  if os.path.exists(filename):
    os.remove(filename)

  tile_format = 'PNG'
  if tile_format == 'JPG':
    tile_format = 'JPEG'
    options = ['QUALITY=%s' % tile_params.get('quality', 75)]
  else:
    options = ['ZLEVEL=8']
  driver = gdal.GetDriverByName('MBTiles')
  ds = driver.Create(filename, 1, 1, 1, options=['TILE_FORMAT=%s' % tile_format] + options)
  ds = None
  sqlite_driver = ogr.GetDriverByName('SQLite')
  print(sqlite_driver)
  ds = sqlite_driver.Open(filename, 1)
  ds.ExecuteSQL("INSERT INTO metadata(name, value) VALUES ('{}', '{}');".format('minzoom', min_zoom))
  ds.ExecuteSQL("INSERT INTO metadata(name, value) VALUES ('{}', '{}');".format('maxzoom', max_zoom))
  # will be set properly after writing all tiles
  ds.ExecuteSQL("INSERT INTO metadata(name, value) VALUES ('{}', '');".format('bounds'))

test1()
```

**Comment by rouault** [comment]
OK, well, this is expected. Just doing Create() on a MBTiles without setting GeoTransform() results in a partially valid .mbtiles. Since GDAL 2.3 and vector tiles support, the MBTiles driver may try to open .mbtiles in vector update mode, but it will fail because this is not a vector .mbtiles. The solution here is to do ds = sqlite_driver.Open('SQLITE:' + filename, 1) to force the sqlite driver to open it.
Counter intuitevely, sqlite_driver.Open() or ogr.Open() are equivalent. In sqlite_driver.Open() the SQLite driver does not know that it will be the only driver that will be probeb, and seeing a .mbtiles extension, it just gives up thinking that the mbtiles driver will take care of the file.

**Comment by PeterPetrik** [comment]
thanks. that make sense now, but I was struggling to understand why it's happening.

For furure, is it possible somehow find out why `ds = sqlite_driver.Open(filename, 1)` failed without debugging GDAL code in debugger?

**Comment by rouault** [comment]
> For furure, is it possible somehow find out why `ds = sqlite_driver.Open(filename, 1)` failed without debugging GDAL code in debugger?

The MBTIiles driver emits an error message "Cannot find min and max zoom_level". Not sure what you would expect. This is a rather particular use case

**Comment by PeterPetrik** [comment]
thanks.
