### ISSUE TITLE
SRTM driver: AREA_OR_POINT=Point

### ISSUE THREAD

**Issue by egouden** [OSGeo/gdal#1505]
Dear GDAL developers,

I rely heavily on GDAL for developing hydrometeorological products.
Thank you for your amazing work.

After reading the documentation ( [here](https://grasswiki.osgeo.org/wiki/HOWTO_import_SRTM_elevation_data) is a summary), it appears that most SRTM height data are based on averaging original satellite radar measurement data and should therefore be interpreted as areas and not points.
Do I understand correctly that the AREA_OR_POINT metadata should be set accordingly to "Area"?
Is this metada used in any of the resampling algorithms?

Best regards,

Edouard Goudenhoofdt

**Comment by jratike80** [comment]
Gdal-dev list is the place to ask questions and there you can reach much wider audience. Citation from the page where you created the ticket:

**Comment by rouault** [comment]
> Is this metada used in any of the resampling algorithms?

No, this is informational only.
It appears that AREA_OR_POINT=Point was introduced per 332ecbacb8036ed78335bf641005e614d10a6cd1as a result of https://trac.osgeo.org/gdal/ticket/1884

**Comment by egouden** [comment]
Thank you for your reply.
I have read this ticket before submitting my bug report.
The reporter maintains that the SRTM data should be interpreted as points, which is wrong for the NASA datasets following the documentation.
Apart from that the reader is correct for NASA SRTM 2.1 and 3.0 !

**Comment by jratike80** [comment]
Because it has been AREA_OR_POINT=Point for 9 years now and there must be other users who deal with SRTM data I think it should not be changed before discussing about the matter on the mailing list first. If it is only informative metadata for SRTM driver then it should not make any difference, but in some other cases pixel-is-point vs. pixel-is-area leads to half a pixel shifts in georeferencing.

**Comment by piyushrpt** [comment]
My understanding is that the AREA_OR_POINT field is meant to convey information about the grid on which the data is laid out rather than the contents themselves. SRTM uses a pixel (center) convention, as opposed to most other DEMs (https://www.usgs.gov/land-resources/eros/topochange/science/srtm-ned-vertical-differencing?qt-science_center_objects=0#qt-science_center_objects) and GDAL's internal (area) model. This field is merely used to apply the correct half pixel shift when reporting the GeoTransform in a consistent manner. Other tools also have to use a similar mechanism to handle grid definitions - e.g, grid line registration or pixel registration in GMT.
