### ISSUE TITLE
GeoJSON file is unreadable depending on order of fields

### ISSUE THREAD

**Issue by danshapero** [OSGeo/gdal#1537]
## Expected behavior and actual behavior.

I expected to be able to open [this GeoJSON file](https://github.com/icepack/icepack-data/blob/master/meshes/larsen/larsen_inflow.geojson) but I get an error message:

    FAILURE:
    Unable to open datasource `meshes/larsen/larsen_inflow.geojson' with the following drivers.

followed by a long list that includes GeoJSON. I *am* able to open this [modified version](https://github.com/icepack/icepack-data/blob/larsen-inflow/meshes/larsen/larsen_inflow.geojson) which consists of a trivial reordering of the fields, putting `"type": "LineString"` before the coordinates rather than after.

I asked [this question](https://gis.stackexchange.com/questions/322640/unreadable-geojson-file-in-qgis-fixed-by-trivial-reordering?noredirect=1#comment525148_322640) on the GIS stack exchange about the problem. Another commenter found that the bug is suppressed if the `"crs"` field is moved too. A different commenter found that the bug doesn't appear when reading the file directly from the URL.

## Steps to reproduce the problem.

I have found the bug using gdal-2.3.2, 2.4.0, 2.4.1, and 3.0.

    # fails
    git clone https://github.com/icepack/icepack-data && cd icepack-data
    ogrinfo meshes/larsen/larsen_inflow.geojson

    # succeeds
    git checkout --track origin/larsen-inflow
    ogrinfo meshes/larsen/larsen_inflow.geojson

*But* I also tested it on gdal-2.1.3 and everything works fine.

## Operating system

Both Arch Linux and Debian buster, the latter through docker.

## GDAL version and provenance

gdal-2.3.2 installed via pacman on Arch Linux;
gdal-2.4.0 installed via apt-get on Debian buster;
and gdal-2.4.1, 3.0, and 2.1.3 installed from source on Debian buster.

**Comment by jratike80** [comment]
Operating system does not make difference, I can see the same behavior on Windows with the GDAL 3.1.0dev binaries from gisinternals.com.

**Comment by NiklasDallmann** [comment]
I cannot view the linked files because they don't exist anymore but I believe this bug still exists. I need to process files containing isochrones which were generated by Open Route Service. Depending on where inside the file `"type": "FeatureCollection"` occurs, opening the file through GDAL either fails or succeeds.

Files to reproduce:
[Succeeds](https://gist.github.com/NiklasDallmann/cccaefa0ba58a64b9ac32c195bf00ea4)
[Fails](https://gist.github.com/NiklasDallmann/27e339dd78d1942d524fbcd179f9fdcf)

# Operating System
Manjaro Linux

# GDAL versions
- GDAL 3.0.4 from the Manjaro package
- GDAL 3.2.0 built by myself
