### ISSUE TITLE
gdalwarp fails to apply vshiftgrid with "-ct" option and proj4 pipeline

### ISSUE THREAD

**Issue by vilaa** [OSGeo/gdal#1561]
## Expected behavior and actual behavior.

Gdalwarp fails to apply a vgridshift using the *"-ct"* command option with a proj4 pipeline.
The input file is in WGS84, the used girds is the egm96_15.gtx. 

## Steps to reproduce the problem.

[sample_4326.zip](https://github.com/OSGeo/gdal/files/3213279/sample_4326.zip)

```bash
gdalwarp -ct "+proj=vgridshift +grids=egm96_15.gtx" sample_4326.tif sample_4326_egm96.tif 
ERROR 1: Too many points (441 out of 441) failed to transform, unable to compute output bounds.
```
and 
```bash
gdalwarp -ct "+proj=pipeline +step +proj=vgridshift +grids=egm96_15.gtx" sample_4326.tif sample_4326_egm96.tif 
```
both lead to the following error : 
```bash
ERROR 1: Too many points (441 out of 441) failed to transform, unable to compute output bounds.
```
## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

Gdal 3.0.0 and Proj 6.1 executed in a docker container. 
Docker image was built from the Dockerfile provided on the repo

**Comment by rouault** [comment]
The vgridshit operations takes and outputs horizontal coordinates as long/lat values in radians, and EPSG:4326 in in lat/long degrees,  so you likely need to do

 -ct "+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=axisswap +order=2,1 +step +proj=vgridshift +grids=egm96_15.gtx +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=rad +xy_out=deg" 

But anyway the vertical shift transformation will not be taken into account due to how gdalwarp works.

You should be able to make it work with:
-s_srs EPSG:4979 -t_srs "+proj=longlat +datum=WGS84 +geoidgrids=egm96_15.gtx"

... hum except that it is broken in GDAL 3.0 . Axis order issue with the output result.
