### ISSUE TITLE
Sphinx documentation for NGW driver no vector page

### ISSUE THREAD

**Issue by BishopGIS** [OSGeo/gdal#1573]
There were two pages with documentation for NextGIS Web driver:

- vector (https://github.com/OSGeo/gdal/blob/release/3.0/gdal/ogr/ogrsf_frmts/ngw/drv_ngw.html)
- raster (https://github.com/OSGeo/gdal/blob/release/3.0/gdal/ogr/ogrsf_frmts/ngw/drv_ngw_raster.html)

Currently the only raster part is present and located at vector driver section.

**Comment by mloskot** [comment]
The `.rst` for drivers were automatically converted. So, the issue is due to the fact `drv_ngw_raster.html` should have never lived inside `ogrsf_frtms` space, IMO.
Could you help to fix it?

1. Convert the `drv_ngw.html` to `drivers/vector/ngw.rst`
2. Move `drv_ngw_raster.html` to `drivers/raster/ngw.rst`

**Comment by rouault** [comment]
Fixed

**Comment by BishopGIS** [comment]
Thank you!
