### ISSUE TITLE
Gdalwarp bug if reproject and merge at same time

### ISSUE THREAD

**Issue by maewart** [OSGeo/gdal#1620]
## Expected behavior and actual behavior.

I'm getting what I think is a bug in the gdalwarp when I merge multiple tiles together and project to a different CRS. This only happens if I merge and resample/project in one single gdalwarp command. If I pre-project the individual tiles and then merge the files using gdal warp then I do not get the issue.

I have looked at this over both the Himilayas and Alaska mountains and they get the same behaviour. Here is an example over the Himilayas.

I downloaded all the TandemX tiles between N24E056 and N53E106. Now TandemX changes to a different resolution north of N50 so a small number of tiles are a different resolution to the rest.

We can demonstrate the problem by merging all the tiles together using the commands:
```diff
gdalbuildvrt FileList.vrt downloadfolder/*.tif

gdalwarp -overwrite -r cubic -tr 90 90 -t_srs +proj=aea +lat_1=25 +lat_2=47 +lat_0=36 +lon_0=85 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs  -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER FileList.vrt merged.tif
```

We then cut the merged data back to the size of a single tile (i.e. TDM1_DEM__30_N27E086_DEM.tif):
```diff
gdalwarp -overwrite -te 97545.546 -1011183.579 197445.546 -898053.579 merged.tif cut.tif
```

We then create a resampled version of the original single tile:
```diff
gdalwarp -overwrite -r cubic -tr 90 90 -t_srs +proj=aea +lat_1=25 +lat_2=47 +lat_0=36 +lon_0=85 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs  -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER TDM1_DEM__30_N27E086_DEM.tif single.tif
```

Finally, we compare the single.tif to the cut.tif which in theory should be the same:
```diff
gdal_calc.py -A cut.tif -B single.tif --calc=A-B --outfile diff.tif
```

This is what we find when looking at the difference.

In all cases, the color scale of the differences is (in meters):
![image](https://user-images.githubusercontent.com/9765043/58973965-2ae71e80-87b9-11e9-9f82-c4aa4bd223dd.png)

1) Difference of Single tile vs HMA merge when including different pixel sizes north of 50 degrees:
![image](https://user-images.githubusercontent.com/9765043/58974010-4baf7400-87b9-11e9-9e6b-7eedca366b18.png)
Here we see a regular stripping artifact.

This is caused by including tiles of different pixel sizes north of 50 degrees.

2) Difference of Single tile vs HMA merge when excluding tiles above 50 degree with different pixel sizes:
![image](https://user-images.githubusercontent.com/9765043/58974088-80233000-87b9-11e9-95bc-46b6dddb2f04.png)

This no longer has the stripping, but some of these differences are pretty big - there are lots of reds and blues with differences in some cases more than a few hundred metres.

3)  Difference when pre projecting the individual tandemX tiles:
![image](https://user-images.githubusercontent.com/9765043/58974137-a34ddf80-87b9-11e9-875a-3708c2d62c8d.png)
This is more like what we want - there are few little areas with small differences but otherwise the difference is close to 0.
All we did here was run the gdalwarp command individually on all tiles first. e.g. looping command is run on all tiles like so:
```diff
gdalwarp -overwrite -r cubic -tr 90 90 -t_srs +proj=aea +lat_1=25 +lat_2=47 +lat_0=36 +lon_0=85 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs  -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER TDM1_DEM__30_N27E086_DEM.tif TDM1_DEM__30_N27E086_DEM_projected.tif 
```

Therefore pre-projecting the tiles appears to fix the issue, however something is going wrong if we reproject and merge all in the same command.

I have found that this happens with all projections (even resampling in latlon).

I hope I've provided enough information here. To recreate it you will need to download the data from the TandemX website and unzip:
[TDM90-url-list_hma.txt](https://github.com/OSGeo/gdal/files/3258158/TDM90-url-list_hma.txt)
Sorry, it is pretty large.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

2.4.0 version from ubuntugis-unstable PPA
I have tried with version 3.0.0 and still get the issue.

**Comment by rouault** [comment]
> Now TandemX changes to a different resolution north of N50 so a small number of tiles are a different resolution to the rest.

That's probably the issue. gdalbuildvrt creates a virtual mosaic by default at some intermediate resolution. You perhaps need to play with the -resolution switch of gdalbuildvrt (like -r highest), as well as -r cubic.

**Comment by maewart** [comment]
Thanks - I'll try that with the vrt to see if it fixes the stripping.

However, that still leaves the issue with large differences seen when I exclude the tiles with a different resolution (the 2nd image).

**Comment by maewart** [comment]
I've investigated and can now confirm that use of the VRT is causing the stripping problem.

However, the 2nd issue of having large differences is still there even if you just pass a list of files and exclude all files with the different pixel size. The only way I can avoid getting large differences is by pre-projecting the input tiles.

This issue is still there in both v2.4 and v3.0.

**Comment by rouault** [comment]
Your bug description is extensive, but if you could reduce the issue to a minimal case (like with just 2 rasters of a few tens of pixels), that would be preferable.

**Comment by maewart** [comment]
Sure - now that we separated this from the VRT issue, I should be able to reduce it. I'll set to work on reducing it and respond on here with a small set of rasters.

**Comment by maewart** [comment]
I've created an example in the attached zip:
[Example.zip](https://github.com/OSGeo/gdal/files/3260994/Example.zip)

There is a data folder with 2 files and an Example.sh which you can run and it will demonstrate the problem. In the Example.sh I have given explanations of the output.

**Comment by rouault** [comment]
The following will fix part A:
```
gdalwarp -overwrite -r cubic -tr 90 90 -t_srs "+proj=aea +lat_1=25 +lat_2=47 +lat_0=36 +lon_0=85 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs" -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER  original_FileList.vrt merged.tif -tap  -et 0 -wo XSCALE=0.925 -wo YSCALE=1.047
gdalwarp -overwrite -r cubic -tr 90 90 -t_srs "+proj=aea +lat_1=25 +lat_2=47 +lat_0=36 +lon_0=85 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs" -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER data/TDM1_DEM__30_N27E086_DEM.tif single.tif -tap -et 0  -wo XSCALE=0.925 -wo YSCALE=1.047
gdalwarp -overwrite -te  97470.000 -1011240.000 197460.000 -898020.000 merged.tif cut.tif
gdal_calc.py -A cut.tif -B single.tif --calc=A-B --outfile diff.tif --overwrite
```
The difference with your code is the addition of  `-tap -et 0  -wo XSCALE=0.925 -wo YSCALE=1.047` at the end of the 2 first gdalwarp invocations, as well as a change of the -te in the merged.tif->cut.tif step.

Explanations:
- the main error came from the creation of cut.tif from merged.tif which cause a ~1 pixel shift, because merged.tif and single.tif did not have origin points whose difference in coordinates was a multiple of 90m. Adding `-tap` creates files whose origin is a multiple of 90m, and hence the subwindowing doesn't introduce pixel shifts
- a more subtle issue comes from the fact that an linear approximator of coordinate reprojection is used by default. You can use exact coordinate reprojection with `-et 0`
- the most subtle bit is `-wo XSCALE=0.925 -wo YSCALE=1.047`. With that, you'll get a 0 difference everywhere, except in the top part of diff.tif (which is expected since cutting after reprojection of a mosaic is not the same as reprojecting a single tile of the mosaic). Those warping options are in fact undocumented currently. When using a non-nearest resampling kernel, the resampler must take into account the ratio of number_of_target_pixels / number_of_souce_pixels to appropriately take into account the weight of source pixels. Currently this value is computed for each warping chunk. Given that the size of the rasters and the default warping memory, a single chunk is used to reproject the mosaic or the single tile. So when working with the VRT mosaic or the single tile, you'll get very subtle differences in those ratios due to non-linearity of reprojection effects and/or raster dimensions being integer values. The value of the scale factors I've selected are the ones that applies for the single tile: 0.925 = 1111. / 1201 and 1.047 = 1258. / 1201. Ideally the warper should probably compute those scale factor for each target pixel, instead of each warping chunk, but that would have computational cost.

**Comment by maewart** [comment]
Thanks for the detailed explanation. I've been through and changed the code and my Part A and B now give the same results. However I am still getting small differences in Part C where I don't use a VRT. I've added the updated script - do you know why this would be the case?
[Example.zip](https://github.com/OSGeo/gdal/files/3262402/Example.zip)

Also, regarding the scaling factors, how did you determine that xscale is 1111. / 1201 for example? The reason I'm asking is because I also need to do the same using a latlon projection and so I'm trying to understand how to derive x and y scale.

**Comment by rouault** [comment]
>  However I am still getting small differences in Part C where I don't use a VRT. I've added the updated script - do you know why this would be the case?

Yes, this is due to -wo XSCALE=0.925 -wo YSCALE=1.047 in your first gdalwarp invokation in Part C. As you are not reprojecting, you are not changing the aspect ratio, so the scale factors should be left at their default value = 1. Setting them to != 1 actually causes a cubic resampling, whereas you are just mosaicing here since the input datasets have the same projection than the output projection, same resolution that the target resolution and the difference of their origin is a multiple of the resolution.

> how did you determine that xscale is 1111. / 1201 for example?

This is the width (in pixels) of single.tif divided by the width of data/TDM1_DEM__30_N27E086_DEM.tif.

**Comment by maewart** [comment]
Brilliant - thanks!

**Comment by dshean** [comment]
Did you try `-r cubic` in your `gdalbuildvrt FileList.vrt downloadfolder/*.tif` command?

Do you see any difference if you use `-r cubic` in your original `gdalwarp -overwrite -te 97545.546 -1011183.579 197445.546 -898053.579 merged.tif cut.tif` command?

Also, what do you see if you use a utility like https://github.com/dshean/demcoreg/blob/master/demcoreg/compute_diff.py to generate a difference map between your original vrt and the original single tile?  This should handle all of the warping on the fly.  

For reference: http://osgeo-org.1560.x6.nabble.com/gdal-dev-vrt-warping-precision-issues-and-tile-offsets-td5387989.html

**Comment by maewart** [comment]
Hi - I realise this is closed but just wanted to answer David's questions.

Without using `-tap` I found that `-r cubic` didn't make a difference to the gdalbuildvrt. However `-r cubic` did make quite a difference to the original `gdalwarp -overwrite -te 97545.546 -1011183.579 197445.546 -898053.579 merged.tif cut.tif`. It doesn't get the differences down to 0 but it is much smaller. If I use compute_diff.py I also get this same small differences.

However, even though the differences are small, there does appear to be a regular slightly curved artifact introduced:

![image](https://user-images.githubusercontent.com/9765043/59097948-d22d9800-8916-11e9-81a3-06d04742d769.png)

This is however the closest I have got without using tap. I need to also investigate what happens if some of the input are different pixel sizes.

Finally, thanks for sending the reference gdal-dev issue. It was interesting reading and it looks like I'm running into a related issue. I'm quite new to using gdal and these sub-pixel issues are up there with some of the most complicated quantitative models I've come across. It's incredibly powerful and I'm enjoying (and going slightly crazy) getting my head around all the subtleties of the different parameters :-)

**Comment by maewart** [comment]
Hi David,

I'm happy to do that and would be good for other users to avoid the issue.

Is there any review of my solution needed before other users start using it
or are you happy with what I believe is a good solution? I can provide
evidence too if that helps?

Cheers,

Martin
