### ISSUE TITLE
Using 'BAG' driver option CreateCopy() appears to shift the input data

### ISSUE THREAD

**Issue by Casiano-Koprowski** [OSGeo/gdal#1643]
## Expected behavior and actual behavior.

Using 'BAG' driver option CreateCopy(name, gdal.Dataset) appears to shift the input data

## Steps to reproduce the problem.

The .bag file I have been using for this testing can be found here:
[https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/H12001-H14000/H12525/BAG/H12525_MB_4m_MLLW_1of2.bag](https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/H12001-H14000/H12525/BAG/H12525_MB_4m_MLLW_1of2.bag)

Code used to reproduce the problem:
```
test = gdal.Open('H12525_MB_4m_MLLW_1of2.bag')
driver = gdal.GetDriverByName('BAG')
driver.CreateCopy('Test.bag', test)
```

## Operating system

Windows 10 64 bit

## GDAL version and provenance

Python 3.6.7
Version 2.4.1

**Comment by rouault** [comment]
What make you think that there's a shift ? My tests don't confirm that:
```
$ gdal_translate H12525_MB_4m_MLLW_1of2.bag out.bag
$ python swig/python/scripts/gdalcompare.py H12525_MB_4m_MLLW_1of2.bag out.bag
Files differ at the binary level.
Metadata value difference for key "BagVersion"
  Golden: "1.6.0"
  New:    "1.6.2"
Metadata value difference for key "BAG_DATETIME"
  Golden: "2018-05-14T18:38:18"
  New:    "2019-06-13T19:17:52"
Differences Found: 3
```
So from GDAL point of view, the source and output files are identical except some minor metadata differences.

**Comment by Casiano-Koprowski** [comment]
Ahh; so I guess this may stem a display issue based on the version of the bag and the software I am using.  Rounding issues that are moving the data.

Sorry, I should have seen this; Thank you for your help!

**Comment by Casiano-Koprowski** [comment]
Hello:

I just wanted to follow up quickly;  While the test using gdalcompare only yielded differences in the timestamp and version of the files, the metadata.xml of the BAG files created using this method also contained some differences.  In opening the metadata of both files, it seems that the values for resolution and extent are slightly different.  When using GetGeoTransform() on the object the values are also different.  I have attached the .xml files as .txt files for both; they were pulled from the files of the same process as the original steps to reproduce. 

The original: [H12525_MB_4m_MLLW_1of2.txt](https://github.com/OSGeo/gdal/files/3315276/H12525_MB_4m_MLLW_1of2.txt)
- Resolution: 4.000000000000
- Extents: 605260.000000000000,4483924.000000000000 620528.000000000000,4494888.000000000000
- GetGeoTransform: (605257.999475891, 4.00104821802935, 0.0, 4494890.000729927, 0.0, -4.001459854014598)

The new file created using CreateCopy(): [VerifyMeta.txt](https://github.com/OSGeo/gdal/files/3315348/VerifyMeta.txt)
- Resolution: 4.00104821802935007
- Extents: 605260,4483924 620528,4494888
- GetGeoTransform: (605257.999475891, 4.00104821802935, 0.0, 4494890.000729927, 0.0, -4.001459854014598)

My main question now is: why are the values from GetGeoTransform() different from the values displayed in the metadata.xml?

**Comment by rouault** [comment]
My understanding is that  H12525_MB_4m_MLLW_1of2.bag uses a non-standard convention, in which the cornerPoints extent are not the ones of the center of pixel (that GDAL corrects by extending its geotransform with a half-pixel on all sides, because it uses a different convention), but the extent of the corner of pixels whose center would be the grid points (which is the GDAL convention...). I've added a heuristics to detect that convention, and adjust properly extent/resolution. I've also added a creation option to be able to use that convention on writing if needed. Messy, as usual with center-of-pixel vs corner-of-pixel convention issues...

**Comment by GlenRice-NOAA** [comment]
My understanding is that the BAG standard is node centered rather than cell centered.  See section 2.5 of the [BAG spec](https://github.com/OpenNavigationSurface/BAG/blob/master/docs/BAG_FSD_Release_1.6.3.doc?raw=true).  Given that, should any other convention be considered error if written into a BAG?  Transforming between the GDAL data model and the BAG standard makes sense, but in either case the resolution doesn't seem like it needs to change, just the extents.  If the resolution does not need to change, I'm confused by the [code to calculate the resolution from the extents and number of rows and columns in the BAG driver](https://github.com/OSGeo/gdal/commit/47bb96d22a5aea4df46bd02d17033e10ea259902?diff=unified#diff-df0809dfa0a16db305cee2451e9a4996R3379).  Should this be the value directly from the BAG metadata with the extents changed by 1/2 this value?

**Comment by rouault** [comment]
> should any other convention be considered error if written into a BAG?

Probably. But apparently there are products in error, and software that expect that error, hence this creation option for those edge cases.

> Should this be the value directly from the BAG metadata with the extents changed by 1/2 this value?

Taking the resolution from the metadata could indeed be an option. But actually BAG is overspecified since we have the number of pixels, the resolution and the extent. So they might have inconsistencies between all of them. If they are all consistent, then whatever you use will be fine . If they are not, then you're in trouble since you don't know if that's the resolution or the extent which is faulty.

**Comment by GlenRice-NOAA** [comment]
[This file shows a brief analysis of a few BAGs](https://github.com/OSGeo/gdal/files/3322683/BAGdata.txt).  For the most part they seem to have a geotransform resolution that is not commensurate with the BAG xml.  It would seem the resolution is the easiest variable to get right, so that should probably be constrained.  From there it is a question of if the number of rows/column or the northeast corner is what should give.

Asking around the ONSWG it looks like 2.3 [here](http://www.opennavsurf.org/meetings/onswg_mtg_2017-03-21.pdf) is relevant.  We will do some more research and report back.

It is worth noting that NOAA Coast Survey is going through some significant effort to clean up incorrect data at [NOAA NCEI](https://www.ngdc.noaa.gov/mgg/bathymetry/hydro.html) right now, so we would like to know about these files and fix them.

**Comment by GlenRice-NOAA** [comment]
The representative feedback I got from the Open Navigation Surface Working Group is as follows:

> The axiomatic definitions for BAG files are location of the SW estimation node, spacing between nodes (could be different in the two axes), and number of estimation nodes in each direction.  Anything else is computed, and if we’re not certain that it’s being computed correctly, we should ignore it.

**Comment by ouyang-means-ouyang** [comment]
我有一个问题想请教您？在GDAL中如何创建一个不是朝北的图像，我的意思是说G(2)和G(4)不为零。创建一幅角度为30度或者270度的图像。我希望您能给我做一个示例，用来教我如何去使用这六个参数，尤其是旋转参数的定义。
I have a question for you? How to create an image not facing north in GDAL? I mean g (2) and G (4) are not zero. Create an image with an angle of 30 or 270 degrees. I hope you can give me an example to teach me how to use these six parameters, especially the definition of rotation parameters

**Comment by avautour** [comment]
I'm a bit confused by this work. Shouldn't the pixel convention be determined by the MD_CellGeometryCode enumeration (https://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_CellGeometryCode), which is defined by:
```
<!-- === MD_CellGeometryCode === -->
<codelistItem>
    <CodeListDictionary gml:id="MD_CellGeometryCode">
        <gml:description>code indicating whether grid data is point or area</gml:description>
        <gml:identifier codeSpace="ISOTC211/19115">MD_CellGeometryCode</gml:identifier>
        <codeEntry>
            <CodeDefinition gml:id="MD_CellGeometryCode_point">
                <gml:description>each cell represents a point</gml:description>
                <gml:identifier codeSpace="ISOTC211/19115">point</gml:identifier>
            </CodeDefinition>
        </codeEntry>
        <codeEntry>
            <CodeDefinition gml:id="MD_CellGeometryCode_area">
                <gml:description>each cell represents an area</gml:description>
                <gml:identifier codeSpace="ISOTC211/19115">area</gml:identifier>
            </CodeDefinition>
        </codeEntry>
    </CodeListDictionary>
</codelistItem>
```
and not via an option?

**Comment by GlenRice-NOAA** [comment]
The BAG pixel convention is not an option.  It is determined by the spec.  Are you saying it should be defined in the BAG XML for clarity?  There is an Open Navigation Surface Working Group Meeting next week at US Hydro if you are interested in discussing further.
