### ISSUE TITLE
Poor performance of construction of CoordinateTransformation in 3.0.

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#1662]
## Expected behavior and actual behavior.

I am using the C# bindings for gdal and I am experiencing bad performance in version 3.0.

The problem is the constructor of the CoordinateTransformation class.

I have tested many transformations and in Gdal 2.4, it takes between 0.1ms and 1ms. If I do the same in version 3.0, I get results between 10ms up to 300ms.

This is how I time it and I tried it with many different source and destination spatial references:
```
Stopwatch sw = Stopwatch.
CoordinateTransformation result = new CoordinateTransformation(sourceSpatialReference, destinationSpatialReference);
sw.Stop();
var time = sw.Elapsed.TotalMilliseconds;
```

I saw that a new constructor was added with CoordinateTransformationOptions, but I don't think this is relevant for my case. 

## Operating system

Windows 10, 64 bit

**Comment by rouault** [comment]
This is expected. Creation of coordinate transformation with PROJ 6 involves a lot more operations, due to the look up done in the PROJ database to find the appropriate transformation(s). You should try to reuse CoordinateTransformation objects as much as possible.

An alternative, if you work with a fixed set of source & target SRS, is to explicitly pass the string expressing the PROJ pipeline through the CoordinateTransformationOptions you noticed. See https://github.com/OSGeo/gdal/blob/master/autotest/osr/osr_ct.py#L334 for an example on how to do this in Python. Should be straighforward to transpose to C#.

You can get the PROJ string to pass by using gdaltransform for example
```
$ gdaltransform -s_srs EPSG:4326 -t_srs EPSG:32631 --debug on
OGRCT: proj=pipeline step proj=axisswap order=2,1 step proj=unitconvert xy_in=deg xy_out=rad step proj=utm zone=31 ellps=WGS84 (UTM zone 31N)
OGRCT: proj=pipeline step inv proj=utm zone=31 ellps=WGS84 step proj=unitconvert xy_in=rad xy_out=deg step proj=axisswap order=2,1 (Inverse of UTM zone 31N)
```
The string to use is the first one mentionned in the log trace (after OGRCT: and before the name in parenthesis), so `proj=pipeline step proj=axisswap order=2,1 step proj=unitconvert xy_in=deg xy_out=rad step proj=utm zone=31 ellps=WGS84`
```
$ gdaltransform -ct "proj=pipeline step proj=axisswap order=2,1 step proj=unitconvert xy_in=deg xy_out=rad step proj=utm zone=31 ellps=WGS84"
```
Of course by doing so, you won't benefit from the automated selection of the best coordinate operation that takes into account the coordinates you transform (in situations where there can have different datum shift parameters according to the area you consider)

**Comment by ktheijs** [comment]
Okay, thanks. 

I'll have to see how I can best handle this in our solution then.
