### ISSUE TITLE
netCDF CF 1.8 SG: error logic in netcdfsg.cpp

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1770]
@wchen329 CoverityScan (issue CID 1404242, please mention it in commit message) detects that `bool dim_set = false;` at line 360 is tested afterwards, but never modified, which is smelly. I tried the following patch but it causes an error in the test suite, so I let you did what is the correct fix

```
diff --git a/gdal/frmts/netcdf/netcdfsg.cpp b/gdal/frmts/netcdf/netcdfsg.cpp
index a3fff75..88d79c0 100644
--- a/gdal/frmts/netcdf/netcdfsg.cpp
+++ b/gdal/frmts/netcdf/netcdfsg.cpp
@@ -357,7 +357,8 @@ namespace nccfdriver
          * (3) there are at least two node coordinate variable ids
          */
 
-        int all_dim = INVALID_VAR_ID; bool dim_set = false;
+        int all_dim = INVALID_VAR_ID;
+        bool dim_set = false;
         int dimC = 0;
         //(1) one dimension check, each node_coordinates have same dimension
         for(size_t nvitr = 0; nvitr < nodec_varIds.size(); nvitr++)
@@ -380,6 +381,7 @@ namespace nccfdriver
             if(!dim_set)
             {
                 all_dim = inter_dim[0];
+                dim_set = true;
             }    
 
             else
```

**Comment by wchen329** [comment]
Thanks for reporting this problem and having a possible fix ready @rouault, I'll go take a look and see what is the intended result.

**Comment by wchen329** [comment]
@rouault yours is the logical fix I think. I think it's also correct. The way I wrote the specific failing assert for unmatched x, y dims I wrote was just a way to be ("lenient") to certain netCDF files which may have same length dimensions but different node coordinate dimensions. But I don't think this is necessary, not to mention there might be some other edge cases with this type of capability. Whatever I wrote there at some point seems like it wasn't meant to support this use cases after all. We should probably just change the test case so it asserts `None is None` instead, I think, and remove the "no longer fatal" comment and use your patch :+1: .

So, since you were the one who fixed this would you like to make the necessary changes? If you are too pressed with other issues, I can make a PR, please let me know.

**Comment by rouault** [comment]
I prefer if you make the PR

**Comment by wchen329** [comment]
Alright, sounds good. I'll make it then.
