### ISSUE TITLE
netCDF SG Writer: WBuffer::subCount() might underflow

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1772]
@wchen329 

WBuffer::subCount(unsigned long long memfree)  { this->used_mem -= memfree; } is called with used_mem = 0 and memfree = 8 by test_write_buffer_restrict_correctness test. This can be detected by adding a CPLAssert()
```
diff --git a/gdal/frmts/netcdf/netcdfsgwriterutil.h b/gdal/frmts/netcdf/netcdfsgwriterutil.h
index 643ef98..f43b662 100644
--- a/gdal/frmts/netcdf/netcdfsgwriterutil.h
+++ b/gdal/frmts/netcdf/netcdfsgwriterutil.h
@@ -88,7 +88,7 @@ namespace nccfdriver
             /* subCount(...)
              * Directly subtracts the specified size from used_mem
              */
-             void subCount(unsigned long long memfree) { this->used_mem -= memfree; }
+             void subCount(unsigned long long memfree) { CPLAssert(this->used_mem >= memfree); this->used_mem -= memfree; }
              unsigned long long& getUsage() { return used_mem; }
 
              void reset() { this->used_mem = 0; }
```

While technically C defined behaviour (operations on unsigned types are well defined and wrap around), it feels like this is unexpected (at least to me) that we substract more used memory than used (thus getUsage() will return garbage)

Note: I discovered this while trying to run GDAL with-fsanitize=unsigned-integer-overflow (many other changes needed to make it pass), which triggers an abort whenever a overflow/underflow occurs on unsigned operations (a number of them are legit, others might be bug).

```
Thread 1 "python" received signal SIGABRT, Aborted.
0x00007ffff6d1b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  0x00007ffff6d1b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff6d1d02a in __GI_abort () at abort.c:89
#2  0x00007ffff1f454d3 in CPLErrorV (eErrClass=CE_Fatal, err_no=7, fmt=0x7ffff2d0f5ce "Assertion `%s' failed in file `%s', line %d", args=0x7fffffff71d0) at cpl_error.cpp:466
#3  0x00007ffff1f44c11 in CPLError (eErrClass=CE_Fatal, err_no=7, fmt=0x7ffff2d0f5ce "Assertion `%s' failed in file `%s', line %d") at cpl_error.cpp:315
#4  0x00007ffff1f46cee in _CPLAssert (pszExpression=0x7ffff2c617bf "this->used_mem >= memfree", pszFile=0x7ffff2c617a8 "./netcdfsgwriterutil.h", iLine=91) at cpl_error.cpp:1319
#5  0x00007ffff1983df2 in nccfdriver::WBuffer::subCount (this=0x1f1c450, memfree=8) at ./netcdfsgwriterutil.h:91
#6  0x00007ffff19809b1 in nccfdriver::OGR_NCScribe::commit_transaction (this=0x1f1c448) at netcdfsgwriterutil.cpp:594
#7  0x00007ffff194fa61 in netCDFDataset::SGCommitPendingTransaction (this=0x1f1c0c0) at netcdflayersg.cpp:300
#8  0x00007ffff18fbaca in netCDFDataset::~netCDFDataset (this=0x1f1c0c0) at netcdfdataset.cpp:2168
#9  0x00007ffff18ff4f9 in netCDFDataset::~netCDFDataset (this=0x1f1c0c0) at netcdfdataset.cpp:2147
```

**Comment by wchen329** [comment]
Hmm, looks like there might be a place where more subtractions are being performed then necessary (or perhaps, the size of operators are not matched are maybe there is some size changes between invokations). Ultimately the intent was to make it so that adds and subtracts of this are matched with pushing in and popping of the buffer. Thanks for reporting this @rouault, I'll go investigate this.

`hors sujet: pourquoi ton GDB n'utilse pas le français mais ton "shell" l'utilise?`

**Comment by wchen329** [comment]
Okay so I started looking at this, and yeah, after writing a simple CPLAssert to check this out, I can confirm that this is indeed an issue.

```
  unsigned long long oldmem = this->used_mem;
  this->used_mem -= memfree;
  CPLAssert(used_mem <= oldmem);
  /* detect underflow cases- if we subtract, then the new value better not 
   * be larger!
   */
```


Looking for a fix- since it doesn't occur on any of the previous tests, I'm guessing that the error is to be found somewhere in the counting when logging (but not a hundred percent sure, as this can be an error in some other part that just somehow "seeped in").

When I give a fix, would you like to keep the Assert there (maybe conditionally compiled on whatever is set by --enable-debug (--with-debug?) for future use? If so what would that macro be?
