### ISSUE TITLE
TransformPoints and vertical shift

### ISSUE THREAD

**Issue by egouden** [OSGeo/gdal#1773]
The following code was tested on Fedora 30 with gdal 2.3.2:

```
from gdal import osr

sr1 = osr.SpatialReference()
projstr = "+proj=longlat +datum=WGS84 +geoidgrids=egm96_15.gtx +vunits=m +no_defs"
sr1.ImportFromProj4(projstr)

sr2 = osr.SpatialReference()
sr2.ImportFromEPSG(4979)

ct = osr.CoordinateTransformation(sr1,sr2)
ct.TransformPoints([[2,54,300],[5,50,300],[10,40,300]]) 
```
Only the first point is transformed correctly for the z coordinate:

[(2.0, 54.0, 342.691), (4.999, 50.0, 300.0), (9.999, 39.999, 300.0)]

**Comment by rouault** [comment]
This works with GDAL 2.4.2 with PROJ 5.1 or GDAL 3.0 with PROJ 6
[(2.0, 54.0, 342.6918601989746), (4.999999999999999, 50.0, 346.7087821960449), (9.999999999999998, 39.99999999999999, 345.7256546020509)]

I can't remember of a bug fix in that area (either in GDAL or PROJ), but there might have been one...
Closing as fixed in later versions
