### ISSUE TITLE
PDS4: update to latest schemas

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1851]
I see the latest PDS4 schemas are https://pds.nasa.gov/datastandards/schema/released/pds/v1/PDS4_PDS_1C00.xsd and https://pds.nasa.gov/datastandards/schema/released/cart/v1/PDS4_CART_1B10_1931.xsd , the later incorporating the changes regarding semi axis names. @thareUSGS Are those OK for you ?

**Comment by rouault** [comment]
@thareUSGS are you fine with the above mentioned schema versions ?

**Comment by thareUSGS** [comment]
Actually, I need to send this off to JPL (to get another update for CART). Unfortunately, I still need help taking the "LDD" version and creating the final CART Schema. This is created during the run of the special JPL program to do this (LDDTool). Here are my latest updates (not that you need to look at this): https://github.com/thareUSGS/ldd-cart/tree/master/src/1.C.0.0 
 
**Now, I don't think the new updates will actually change anything for you**. Everything I added was for a new Planetary Rings map projection section (still under review) and a couple optional additions under the body definition. Nothing that GDAL currently needs to deal with.

So that said, yes, you should be good to go with PDS4_CART_1B10_1931.xsd  This new version should not impact you.

thanks for checking

**Comment by rouault** [comment]
Thanks for the confirmation. We can always consider the update to later versions, especially if only changes in schema numbers are involved.

**Comment by thareUSGS** [comment]
Please find CART 1.C.0.0 has been posted: https://pds.nasa.gov/datastandards/schema/released/#cart

**Comment by rouault** [comment]
@thareUSGS I believe https://pds.nasa.gov/datastandards/schema/released/cart/v1/PDS4_CART_1C00_1932.xsd has an error. The schemaLocation for the "http://pds.nasa.gov/pds4/geom/v1" namespace is https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_null_1700.xsd , whose name is suspicious and that doesn't exist
(The previous version of the CART schema linked to  https://pds.nasa.gov/pds4/geom/v1/PDS4_GEOM_1B10_1700.xsd)

**Comment by thareUSGS** [comment]
Yep - thanks for catching that. Looks like during the schema creation I need to watch out for the paths. Sending up to JPL but might take a day or so.

**Comment by rouault** [comment]
@thareUSGS The correction is now online. However, there is another problem. The Xerces-C library used by GDAL to test validity of the produced XML labels against the .xsd schemas complains about non-validity of the .xsd itself. It throws the following errors:
```
ERROR 1: /vsicurl_streaming/https://pds.nasa.gov/datastandards/schema/released/cart/v1/PDS4_CART_1C00_1932.xsd:763:44 no complete functional mapping between particles
ERROR 1: /vsicurl_streaming/https://pds.nasa.gov/datastandards/schema/released/cart/v1/PDS4_CART_1C00_1932.xsd:528:46 no complete functional mapping between particles
```
Digging a bit, those errors are legitimate, because the `Point_Perspective` complex type adds a `target_center_distance` element, but `Point_Perspective` is a restriction of `Map_Projection_Base`, thus all elements of the former must be in the later, which is not the case. Similarly for `Oblique_Cylindrical`
The following patch adding the missing elements in `Map_Projection_Base` fixes the issue:
```
--- /home/even/schematron/PDS4_CART_1C00_1932.xsd	2019-10-14 17:57:59.000000000 +0200
+++ PDS4_CART_1C00_1932_corrections_Map_Projection_Base.xsd	2019-10-15 08:49:52.132120961 +0200
@@ -480,6 +480,17 @@
         <xs:element name="Oblique_Line_Point" type="cart:Oblique_Line_Point"> </xs:element>
       </xs:choice>
       <xs:element name="latitude_of_projection_origin" type="cart:latitude_of_projection_origin" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="target_center_distance" type="cart:target_center_distance" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="reference_latitude" type="cart:reference_latitude" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="reference_longitude" type="cart:reference_longitude" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="map_projection_rotation" type="cart:map_projection_rotation" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="oblique_proj_pole_latitude" type="cart:oblique_proj_pole_latitude" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="oblique_proj_pole_longitude" type="cart:oblique_proj_pole_longitude" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="oblique_proj_pole_rotation" type="cart:oblique_proj_pole_rotation" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="oblique_proj_x_axis_vector" type="cart:oblique_proj_x_axis_vector" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="oblique_proj_y_axis_vector" type="cart:oblique_proj_y_axis_vector" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="oblique_proj_z_axis_vector" type="cart:oblique_proj_z_axis_vector" minOccurs="0" maxOccurs="1"> </xs:element>
+      <xs:element name="look_direction" type="cart:look_direction" minOccurs="0" maxOccurs="1"> </xs:element>
     </xs:sequence>
   </xs:complexType>
 
```
I'm also attaching the corrected version: 
[PDS4_CART_1C00_1932_corrections_Map_Projection_Base.xsd.zip](https://github.com/OSGeo/gdal/files/3727711/PDS4_CART_1C00_1932_corrections_Map_Projection_Base.xsd.zip)

**Comment by thareUSGS** [comment]
Yes JPL found those also. Thanks for the description, upon first look I wasn't sure what was happening. It is not good that I assumed building from the input Local Data Dictionary, all checks are made and validated. For future builds, I will make sure to validate using (1) Oxygen and (2) the JPL tool validate. 

I will have a an update posted (again) soon.

**Comment by thareUSGS** [comment]
Your recommendations helped me understand the issue, but the real issue which also fixed CART to validate was to run a new version of LDDtool (which converts the Local Data Diction of CART to the CART schema).  It is slightly different placement for the invalid items but should work for GDAL.

**Comment by rouault** [comment]
@thareUSGS It seems https://pds.nasa.gov/datastandards/schema/released/cart/v1/PDS4_CART_1C00_1932.xsd hasn't still been updated with the changes in Map_Projection_Base

**Comment by thareUSGS** [comment]
I would like to get your thoughts on Map_Projection_Base. I understand what the original authors tried to do by grouping common map projection parameters into a single class. They defined it as _"An abstract class that serves as the parent class to all the map projections."_ But due to the many different styles of projections allowed including typical cartographic map projections (used in GDAL), landed (in-situ) projections (used in VICAR), and now rings projections, there is not really a common group of projection parameters to try to abstract away.

The use of this abstract class also seems to hide what is required for each map projection.  For example, with Equirectangular, it is not clear that standard_parallel_2 isn't really needed as the user is given a choice of 3 from the abstract class.

I feel like perhaps Map_Projection_Base should be removed, such that each defined projection can list concretely exactly what parameters are required. 

Am I overthinking this?

Disregard this next sentence, it is for another ticket not for here. But, I also noticed that false_easting and false_northing do not currently exist. For planetary we don't use those (or assume they are 0.0), but if we ever wanted to use a PDS4 for Earth we would need to add those in.

**Comment by rouault** [comment]
> Am I overthinking this?

Yes, I don't really see value in this Map_Projection_Base class. If there were common parameter(s) to all projection methods, they could be there, and the actual projection methods would be *extensions* of Map_Projection_Base instead of being *restrictions* as currently. But just removig the Map_Projection_Base class would be totally fine to me (no impact on GDAL side)

**Comment by thareUSGS** [comment]
FYI, New 1.D.0.0 for CART has been [pushed to github](https://github.com/pds-data-dictionaries/ldd-cart/pull/7/files) (not just yet to main JPL site), so you might need to wait for the final path which should be, once uploaded by JPL: https://pds.nasa.gov/datastandards/schema/released/cart/v1/PDS4_CART_1D00_1933.sch

1. removed MAP_Projection_Base (probably no impact for GDAL)
2. added Orthographic, Mercator, and Lambert Azimuthal Equal-area (I think you already had these coded-up in the driver, hopefully no impact)
3. There was an attribute removal for polar stereographic (**which does impact GDAL**). I removed straight_vertical_longitude_from_pole and changed to use longitude_of_central_meridian (more standard use).

These are listed in the 1.9.3.3 update notes here: https://github.com/pds-data-dictionaries/ldd-cart/blob/48375158d0340641f345fba8a2ee85a44ca5bb45/src/1.D.0.0/PDS4_CART_1D00_IngestLDD_CART_1933.xml#L131

Lastly, this also updates to PDS 1.D.0.0, which I think should not have an impact:
https://pds.nasa.gov/datastandards/schema/released/pds/v1/PDS4_PDS_1D00.sch

**Comment by rouault** [comment]
Update to 1D00_1933 per https://github.com/OSGeo/gdal/pull/1981 . Beyond the impacts you listed, there were a couple changes in the order of projection parameters
