### ISSUE TITLE
ISIS3: support the Bandbin group

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1853]
The ISIS3 Bandbin group contains the band names. This task is about propagating the ISIS3 band names using existing metadata areas in GDAL. ISIS3 can use two keywords for band names, thus the driver shall first look for “Name” under the Bandbin group and if that doesn’t exist, fallback to “FilterName” (if the Bandbin group exists at all)

@thareUSGS Can you point to ISIS3 datasets that have Bandbin.Name and Bandbin.FilterName ?

**Comment by thareUSGS** [comment]
So apparently the BandBin group is not well defined. I mostly see "FilterName" and primary and then I have seen "Name" and then also "BandSuffixName" and of course then some with no Name. Is there a method to look for anything with "*Name*" instead of trying to bounce through "FilterName", then "Name" and then "BandSuffixName". Keep it simple as it shouldn't fail if missing or if BandBin group doesn't exist.

Here are some test files: https://www.dropbox.com/s/45mrt0z807pve1d/ISIS3_bandbin.zip?dl=1
