### ISSUE TITLE
Converting to NITF has incorrect corner coordinates

### ISSUE THREAD

**Issue by jsvrcek** [OSGeo/gdal#1936]
## Expected behavior and actual behavior.

When using gdalwarp or gdal_translate with an output file of NITF the corner coordinates should be the same as the input corner coordinates, if the source file has the same coordinate system.  However when converting from geopackage to NITF the coordinates are different.   There does not seem to be an issue converting from gpkg to nitf.  

## Steps to reproduce the problem.
Using the attached sample...
[washington_dc.zip](https://github.com/OSGeo/gdal/files/3731977/washington_dc.zip)

Print out the gdalinfo to view the reported coorindates...
`gdalinfo washington_dc.gpkg`
```
Driver: GPKG/GeoPackage
Files: washington_dc.gpkg
Size is 80, 77
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
Origin = (-77.050952911376996,38.903303146362298)
Pixel Size = (0.000021457672119,-0.000021457672119)
Metadata:
  DESCRIPTION=Created with Mapproxy.
  IDENTIFIER=default
  ZOOM_LEVEL=15
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  ( -77.0509529,  38.9033031) ( 77d 3' 3.43"W, 38d54'11.89"N)
Lower Left  ( -77.0509529,  38.9016509) ( 77d 3' 3.43"W, 38d54' 5.94"N)
Upper Right ( -77.0492363,  38.9033031) ( 77d 2'57.25"W, 38d54'11.89"N)
Lower Right ( -77.0492363,  38.9016509) ( 77d 2'57.25"W, 38d54' 5.94"N)
Center      ( -77.0500946,  38.9024770) ( 77d 3' 0.34"W, 38d54' 8.92"N)
```

Additionally the coordinates from the file can be verified using sqlite3...
`sqlite3 washington_dc.gpkg -cmd "select * from gpkg_contents;"`
```
default|tiles|default|Created with Mapproxy.|2019-10-15T00:51:44.858Z|-77.050952911377|38.9016437521787|-77.0492362976074|38.9033031463623|4326
```

Convert the file to NITF...
`gdalwarp -of nitf -co ICORDS=G washington_dc.gpkg washington_dc_nitf.nitf`
```
Using band 4 of source image as alpha.
Creating output file that is 80P x 77L.
ERROR 6: Requested color interpretation (Alpha) not supported in NITF.
Processing washington_dc.gpkg [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
```

View the gdalinfo of the new file to verify that the the corner coordinates (are different).
`gdalinfo washington_dc_nitf.nitf`
```
Driver: NITF/National Imagery Transmission Format
Files: washington_dc_nitf.nitf
       washington_dc_nitf.nitf.aux.xml
Size is 80, 77
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
Origin = (-77.050843881856537,38.903344298245607)
Pixel Size = (0.000021097046413,-0.000021929824561)

Corner Coordinates:
Upper Left  ( -77.0508439,  38.9033443) ( 77d 3' 3.04"W, 38d54'12.04"N)
Lower Left  ( -77.0508439,  38.9016557) ( 77d 3' 3.04"W, 38d54' 5.96"N)
Upper Right ( -77.0491561,  38.9033443) ( 77d 2'56.96"W, 38d54'12.04"N)
Lower Right ( -77.0491561,  38.9016557) ( 77d 2'56.96"W, 38d54' 5.96"N)
Center      ( -77.0500000,  38.9025000) ( 77d 3' 0.00"W, 38d54' 9.00"N)
```

## Operating system

Ubuntu 18.04 (64-bit)

## GDAL version and provenance

GDAL 2.4.1 installed via miniconda (conda-forge)

**Comment by jratike80** [comment]
I think you should have sent this rather as a question to the gdal-dev mailing list because there may not be a bug involved but instead something about how georeferencing is stored into NITF format. Mailing list is reaching GDAL users much better and some other user might be able to help you. On the other hand, mails on the mailing list work better as a help desk archive than comments in bug reports. 

By reading https://gdal.org/drivers/raster/nitf.html I do not quite understand how NITF images are georeferenced. At least GDAL seems to work in a consistent way with different source formats and with different utilities. I made a test by convertiong your geopackage image into tif and then a) convert gpkg into nitf with gdalwarp, b) convert tif into nitf with gdalwarp, and c) convert tif into nitf with gdal_translate.

In all three cases the size of the resulting nitf image is 80x77 pixels and the origin and pixel size are
```
Origin = (-77.050843881856537,38.903344298245607)
Pixel Size = (0.000021097046413,-0.000021929824561) 
```

Other corner coordinates are defined by the pixel size and image size. 
I guessed that changed origo could be due to using the option ICORDS=G that is documented to mean "Set to “G” to ensure that space will be reserved for geographic corner coordinates (in DMS) to be set later via SetGeoTransform()" and thought that using ICORDS=D would keep the original origo but no, the result is different but not the same
```
Origin = (-77.051012658227847,38.903006578947370)
Pixel Size = (0.000025316455696,-0.000013157894737)
```
So unfortunately I couldn't explain you what happens.

**Comment by rouault** [comment]
NITF uses by default low precision (by today standard) georeferencing. This is all mentionned in https://gdal.org/drivers/raster/nitf.html . You might want to use the -co SDE_TRE=YES creation option. Closing
