### ISSUE TITLE
Page not found  for Java API

### ISSUE THREAD

**Issue by 269017583** [OSGeo/gdal#1996]
HEY，The Page  for Java API was not found now ，like the url “https://gdal.org/java/index.html”.
can anyone fix it ?
or may I download the Java API offline doc anywhere?

**Comment by rouault** [comment]
This is now fixed.

@mloskot The issue here was that yesterday the download.osgeo.org server was flaky, and this is where we extract the Java doc from (wget https://download.osgeo.org/gdal/for_doc/javadoc.zip -O /tmp/javadoc.zip). So the doc repo was regenerated without them ? Is there a way of making the pipeline fail if a step of the script fails ?

**Comment by mloskot** [comment]
@rouault Why did you close this? Resolved?

Sorry, I'm busy right not and can get to this problem later tonight.

**Comment by rouault** [comment]
> Why did you close this? Resolved?

I just had to do a dummy commit to restart the generation. My question was more to avoid that issue in the future, by failing the Azure pipeline instead of pushing an incomplete doc generation. There's no emergency. I'll open a dedicated ticket
