### ISSUE TITLE
This library does not support Chinese for c#

### ISSUE THREAD

**Issue by BlindProgrammer0** [OSGeo/gdal#2156]

**Comment by mloskot** [comment]
This is issue is vague, incomplete, lacking minimal example that would allow to reproduce the problem.  Please, do not ignore the [bug report template we provide](https://github.com/OSGeo/gdal/blob/master/.github/ISSUE_TEMPLATE.md) and spend some time on crafting a good bug report, instead of tossing a bad one at GDAL team.
