### ISSUE TITLE
ogr2ogr -dialect postgis

### ISSUE THREAD

**Issue by andrewharvey** [OSGeo/gdal#2160]
Feature request for ogr2ogr to support `-dialect postgis`, doing so will transparently load your source into a postgresql table, run your `-sql` directly within postgis, return the results back and cleanup the table.

This would be great for oneliner commands which need the power of PostGIS not offered by Spatialite while avoiding the overhead of first loading data, then cleaning up after.

**Comment by rouault** [comment]
Hum I am a bit skeptical about that. This might be super inefficient if the source dataset is large ! You'd better do that at hand by creating a custom PostGIS schema, and drop it afterwards. Or have some script that does that
You might also consider using https://github.com/pramsey/pgsql-ogr-fdw
-dialect sqlite has decent performance because it doesn't require loading the data in a real database, but use a virtual table mechanism.

**Comment by andrewharvey** [comment]
You're right it would be nothing more than a wrapper for:

    ogr2ogr -f PostgreSQL PG: source && psql -c 'sql' && ogr2ogr dest PG: && psql -c 'DROP TABLE'

I guess it's actually not too bad just doing ^ instead of trying to build this into the -sql and -dialect options of ogr2ogr... so I'll close this.

pgsql-ogr-fdw is good, but it works the other way, I want ogr2ogr to call pgsql not pgsql calling ogr.
