### ISSUE TITLE
handling multiple vector.pbf

### ISSUE THREAD

**Issue by sonfiree** [OSGeo/gdal#2177]
I have file.vector.pbf they are structured and have one zoom (zoom / x / y.vector.pbf (https://gdal.org/drivers/vector/mvt.html))
I want to make one big map that normalize the geometry and then translate it into GeoJson.
How can I merge all the data? Or immediately transfer the normalized data to GeoJson

**Comment by jratike80** [comment]
Didn't you read the notice on the page that you used for creating this issue?

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

**Comment by sonfiree** [comment]
If there was clear documentation there would be no questions

**Comment by jratike80** [comment]
I did  not say that you must not ask questions. Just that you should not ask questions in bug tracker. The mailing list has much bigger audience because also the GDAL users are there and one part of the power of open source projects is that users can help other users.

When you write your question to the mailing list I suggest to give a bit more details about what you want to do. Describe what you mean with "they are structured" and by "normalize the geometry" and by "merge all the data".
