### ISSUE TITLE
gdaltransform: Wrong horizontal transformation for compound CRS EPSG:7912 → EPSG:6319+3855

### ISSUE THREAD

**Issue by and-marsh** [OSGeo/gdal#2186]
## Expected behavior and actual behavior
Hello, i found an inconsistent behavior during some coordinate transformations:
Transformation `EPSG:7912(ITRF2014)` → `EPSG:6319(NAD83(2011))` works fine:

    echo \
    '10 10 0 2010
    10 10 0 2020' | ./gdaltransform -s_srs EPSG:7912 -t_srs EPSG:6319
    9.99997950181524 9.99999272827463 0.556627034209669
    9.99997954572174 9.99999047551283 0.556196286343038

After adding `EPSG:3855(EGM2008 Height)` to target system horizontal transformation stops working for `gdaltransform`:

    echo \
    '10 10 0 2010
    10 10 0 2020' | ./gdaltransform -s_srs EPSG:7912 -t_srs EPSG:6319+3855
    10 10 -21.5063400268555
    10 10 -21.5063400268555

But not for `cs2cs`:

    ./cs2cs  EPSG:7912  EPSG:6319+3855 <<EOF -d 20
    10 10 0 2010
    10 10 0 2020
    EOF
    9.99999272827462704072  9.99997950181524331015 0.55662703420966863632 2010
    9.99999047551283481994  9.99997954572174307941 0.55619628634303808212 2020

If try to invert this operation:  `EPSG:6319+3855` → `EPSG:7912` then `cs2cs` also isn't working correct: 

    ./cs2cs  EPSG:6319+3855  EPSG:7912 <<EOF -d 20
    10 10 0 2010
    10 10 0 2020
    EOF
    10.00000000000000000000 10.00000000000000000000 21.50634002685546875000 2010
    10.00000000000000000000 10.00000000000000000000 21.50634002685546875000 2020

I suppose that behavior isn't correct and horizontal transformation should work for all these cases as well.
## Operating system

macOS Catalina 10.15.2

## GDAL version and provenance

GDAL 3.0.2, PROJ 6.3.0

**Comment by rouault** [comment]
You should upgrade to GDAL 3.0.3, so as to be sure it uses the same algorithm as PROJ 6.3.0 's cs2cs.

That's said, when using cs2cs of PROJ 6.3.0, I don't get the same result as you. So I'm not sure if your installation is correct. Those results are also a bit questionable because 10,10 is out of the area of use of NAD83(2011)
```
even@even-i700:~/proj/6.3/build$ echo "10 10 0 2010" | PROJ_LIB=data src/cs2cs -d 20  EPSG:6319 EPSG:7912
10.00000727172776571194	10.00002049818828631089 -0.55662622023373842239 2010

even@even-i700:~/proj/6.3/build$ echo "10 10 0 2010" | PROJ_LIB=data src/cs2cs -d 20  EPSG:6319+3855 EPSG:7912
10.00000727172776571194	10.00002049818828631089 -0.55662622023373842239 2010

even@even-i700:~/proj/6.3/build$ echo "10 10 0 2010" | PROJ_LIB=data src/cs2cs -d 20  EPSG:7912 EPSG:6319+3855
9.99999272827462704072	9.99997950181524331015 0.55662703420966863632 2010

even@even-i700:~/proj/6.3/build$ echo "10 10 0 2010" | PROJ_LIB=data src/cs2cs -d 20  EPSG:7912 EPSG:6319
9.99999272827462704072	9.99997950181524331015 0.55662703420966863632 2010
```

But even with GDAL 3.0.3 + PROJ 6.3.0,  the following doesn't return the same result as cs2cs. I don't have an explanation for this yet
```
echo '10 10 0 2020' | gdaltransform -s_srs EPSG:7912 -t_srs EPSG:6319+3855
10 10 -21.5063400268555
```

**Comment by and-marsh** [comment]
Hmm, it looks like in your examples with `cs2cs` vertical correction isn't applied at all. Probably you have missed geoid? 
My `proj` has `v6.3.0`: 
```
./cs2cs
Rel. 6.3.0, January 1st, 2020
``` 
And after deleting `egm08_25.gtx` i got all the same results as yours, for example:
```
./cs2cs  EPSG:6319  EPSG:7912+3855 <<EOF -d 20
50 170 0 2010
EOF
49.99999520375848049980 169.99998794356133657857 1.26244744472205638885 2010
```

But with available geoid `egm08_25.gtx` `cs2cs` still isn't working, even inside bounds:
```
./cs2cs  EPSG:6319  EPSG:7912+3855 <<EOF -d 20
50 170 0 2010
EOF
50.00000000000000000000 170.00000000000000000000 -3.25556969642639160156 2010
```
 
So, i updated `gdal` to  `v3.0.3` and it works just like `cs2cs`:
 if geoid isn't available:
```
echo \
'170 50 0 2010' | ./gdaltransform -s_srs EPSG:6319 -t_srs EPSG:7912+3855
169.999987943561 49.9999952037585 1.26244744472206
```
And if geoid is available:
```
echo \
'170 50 0 2010' | ./gdaltransform -s_srs EPSG:6319 -t_srs EPSG:7912+3855
170 50 -3.25556969642639
```

Hope it will be helpful

**Comment by rouault** [comment]
> Probably you have missed geoid?

Ah obviously. That was it... OK, so now I've consistent results between GDAL and PROJ.

I'd note that in your latest post EPSG:7912+3855 is invalid, this is ITRF2014 3D + a height. You rather meant EPSG:9000+3855. Or EPSG:6319+3855 as in your initial exemple. But horizontal transform is still lacking when using +3855

So the conclusion of this is that it is a PROJ issue, and not a GDAL one. Hence closing this ticket. You may raise a ticket in the PROJ tracker, but I'm not super confident this can be easily fixed. PROJ is doing a lot of inferences to compute paths between NAD83(2011)<-->WGS84 and ITRF2014<-->WGS84, since WGS84 is the interpolation CRS of EGM2008, and gets confused by this complexity.

**Comment by and-marsh** [comment]
Ok, thank you!
