### ISSUE TITLE
Processing ECOSTRESS products

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/gdal#2217]
[ECOSTRESS](https://ecostress.jpl.nasa.gov/) is a mission that produces a series of thermal infrared related satellite products. The only tool that seems to be available for re-projecting from "its swath" is [ecostress_swath2grid](https://git.earthdata.nasa.gov/projects/LPDUR/repos/ecostress_swath2grid/browse).

Is there any consideration to support ECOSTRESS products using GDAL?

**Comment by rouault** [comment]
> Is there any consideration to support ECOSTRESS products using GDAL?

Apparently, from you, since you raised the topic ;-) GDAL is mostly a "bring-it-yourself" type of project (or "find-someone-to-bring-it-for-you").

But looking quickly at those products, I'm not sure a GDAL dedicated driver, or tuning the HDF5 driver to support those, would be the most natural thing, since you need to combine several .h5 files (the one with the high level information and the _GEO one) to get something meaningful.
If someone badly needed that, I guess a GDAL support could consist in attaching a GEOLOCATION array based on the _GEO .h5 file. For practical use, you'd need to run gdalwarp on it, and assuming that the generic geolocation transformer in GDAL works well enough for that.
So all in all, I'd say that using ecostress_swath2grid is probably the best option.

**Comment by NikosAlexandris** [comment]
Thank you @rouault.-

**Comment by NikosAlexandris** [comment]
Perhaps of anyone's interest, an attempt here to "rewrite" the official script: https://gitlab.com/thermopolis/public/ecor
