### ISSUE TITLE
FlatGeobuf: Source not valid for direct conversion

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#2252]
## Expected behavior and actual behavior.
*expected*: direct conversion from _GPKG_ to _FlatGeobuf_
*actual behaviour*
```
ERROR 1: Source not valid for direct conversion
ERROR 1: Unable to write feature 1 from layer test.
ERROR 1: Terminating translation prematurely after failed
translation of layer test (use -skipfailures to skip errors)
```

## Steps to reproduce the problem.
Layer `test` is a single-feature point layer (2D) in _EPSG:25832_, but `Geometry: Unknown (any)`.
```
ogrinfo test.gpkg -ro -so
INFO: Open of `test.gpkg'
      using driver `GPKG' successful.
1: test

ogr2ogr -progress -F FlatGeobuf test.fgb test.gpkg test
ogr2ogr -progress -F FlatGeobuf testdir test.gpkg
```

## Operating system
Microsft Windows 10, 64 bit - Version 10.0.17763.678

## GDAL version and provenance
GDAL 3.1.0dev, released 2019/99/99 from OSGeo4W (update 2020-02-17)

**Comment by rouault** [comment]
CC @bjornharrtell

**Comment by jratike80** [comment]
Test data would be highly appreciated.
I found some data of my own and you had correctly identified what is ariring the error and that is the generic GEOMETRY geometry type in your source data.

I do not know if conversion geometry -> geometry should work with flatgeobuf but because your table contains just points then this should work for you just as it worked for me with GDAL 3.1.0dev from last night.

`ogr2ogr -progress -F FlatGeobuf test.fgb test.gpkg test -nlt point`

**Comment by tobwen** [comment]
Yep, `Geometry: Unknown (any)` was the problem. Thanks. I'm closing this.

**Comment by jratike80** [comment]
Perhaps you were too fast, I do not think that this limitation is documented or if it is intentional. But let's see how Björn reacts.

**Comment by bjornharrtell** [comment]
Unintentional implementation limitation. At one time I didn't support unknown/mixed geometries in spec but spec version 2+ does and I would like to fix this when possible. I'll create a new issue to be able to track it myself.
