### ISSUE TITLE
No name differences between debug and release for plug-ins

### ISSUE THREAD

**Issue by OgreTransporter** [OSGeo/gdal#2309]
## Expected behavior and actual behavior.

When building GDAL the DLLs gdal310_d.dll (Debug) and gdal310.dll (Release) are created. For plugins there is no difference between debug and release version. For example, the HDF5 plugin is created as gdal_HDF5.dll (Debug) and gdal_HDF5.dll (Release). In all makefiles of the plugins everywhere

```
PLUGIN_DLL = gdal_HDF5.dll
```

should be replaced with something like

```
!IF "$(DEBUG)" == "1"
PLUGIN_DLL = gdal_HDF5_d.dll
!ELSE
PLUGIN_DLL = gdal_HDF5.dll
!ENDIF
```

## Steps to reproduce the problem.

Build debug version of gdal.

## Operating system

Windows 10 + MS Visual Studio 2017

## GDAL version and provenance

1afd3975652b91805829ec221631e6f0b7c9729b

**Comment by mloskot** [comment]
@OgreTransporter The subject and description is unnecessarily obscure and makes it difficult to understand what  *difference* you mean.

Are you expecting different name of the binaries?
Are you expecting different size of the binaries?
... or something else.

**Comment by OgreTransporter** [comment]
@mloskot I would actually like to build GDAL and distribute it as a package for development on other computers. This is no problem with the GDAL-DLL, because there is a difference between debug and release Version in file name. So I can copy both versions into a bin directory. The same applies to the files in the lib directory. But I can't copy the plugins together, because then the release plugin would overwrite the debug version because they have the same file name.

**Comment by mloskot** [comment]
@OgreTransporter IMO, this is not GDAL concern really. Load from different locations, see how others solve it, e.g. vcpkg. 

In fact, even the flags are not GDAL concern and GDAL could keep using whatever works for GDAL, then developers as well as package maintainers would have to adjust that to their own liking. Just like vcpkg does in https://github.com/microsoft/vcpkg/blob/c88974a2239b1de0facbf4cc096e0ad75c8e51a6/ports/gdal/0001-Fix-debug-crt-flags.patch for GDAL 2.x

It was Even's courtesy to change to `/MDd` for debug builds, see https://lists.osgeo.org/pipermail/gdal-dev/2017-September/047243.html.

**Comment by OgreTransporter** [comment]
Yes, the comments on the mailing list are correct. To work with debug versions on Windows you have to use /MDd (/MD for release) - see issue #2308. That's the reason why it's nice to have different file names. For example gdal_HDF5.dll (Release, /MD) and gdal_HDF5d.dll (Debug, /MDd) for the HDF5 plugin. It's not possible to mix debug/release libraries during linking. Of course you can access a release DLL without linking by using LoadLibrary and GetProcAddress from a debug program. But this is verry awful for a bigger library! Different names are working well for the main source with gdal310_d.dll (Debug) and gdal310.dll (Release).

**Comment by rouault** [comment]
@OgreTransporter I think a pull request implementing your suggestion would be fine if you want to have a try at that.

**Comment by mloskot** [comment]
@OgreTransporter FYI, I've been [well aware of /MDd vs /MD issues](https://trac.osgeo.org/gdal/ticket/3346) in GDAL for very long time. Referring to _must_-s or _have to_-s, mixing release and debug binaries are perfectly supported on Windows. The issue is that it's very easy to shoot in a foot and extreme caution is required.  

My point is, renaming binaries to use `_d` suffix convention for debug build is convenient and user-friendly indeed, but it is _not a requirement_ to get things work. So, your issues are not bug reports requesting a fix for broken GDAL. However, since @rouault agreed to accept PR with such renaming, you're good to go.

**Comment by rouault** [comment]
@mloskot  Since starting with 99d5c09a we postfix the gdal DLL for debug builds, it would seem more consistant now to do so as well with the plugins. Unless I'm missing something. Hum, thinking that the "missing something" might be that GDAL relies on what follows "gdal_" to find the entry point of the DLL. So the logic in https://github.com/OSGeo/gdal/blob/master/gdal/gcore/gdaldrivermanager.cpp#L834 should be adapted to strip a _d postfix

**Comment by mloskot** [comment]
@rouault Consistency is desirable, I agree.

>  thinking that the "missing something" might be that GDAL relies on what follows "gdal_" to find the entry point of the DLL

That is what I described as implications in https://github.com/OSGeo/gdal/issues/2309#issuecomment-597082434, I also wasn't sure if some of plugins are `LoadLibrary`/`dlopen`-ed  on demand, then DLL names are part of the interface and code changes would be necessary.
In other words, just fiddling with makefiles may not be enough, as you pointed.

**Comment by OgreTransporter** [comment]
Yes, this issue is not a bug report. It is more a suggestion for improvement.

> Since starting with 99d5c09 we postfix the gdal DLL for debug builds, it would seem more consistant now to do so as well with the plugins.

This fact irritated me and prompted me to create this ticket. I will try a PR, but it will take a few days to test everything.

**Comment by rouault** [comment]
With CMake builds, I believe there is a gdalplugins\Release and gdalplugins\Debug directory
