### ISSUE TITLE
Issue warnings/errors if ESRI Shapefile driver degrades invalid geometries on write 

### ISSUE THREAD

**Issue by rbuffat** [OSGeo/gdal#2340]
This is related to https://github.com/OSGeo/gdal/issues/1787

The following use case was reported to Fiona: https://github.com/Toblerity/Fiona/issues/868

In the following example, the ESRI Shapefile driver degrades a non-valid Multipolygon to a Polygon. Probably because the driver is sensitive to non-valid geometries: https://github.com/OSGeo/gdal/issues/1787#issuecomment-522250212

I was wondering if there would be the possibility to issue an error or warning when the driver is not able to write a geometry. 

```
from osgeo import gdal
from osgeo import ogr
import os

print("GDAL:", gdal.__version__)

gdal.UseExceptions()

coords_bad = [
    [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 0.0]],
    [[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0]],
]


for filename, driverName in [("abc.geojson", "GeoJSON"),
                             ("abc.gpkg", "GPKG"),
                             ("abc.shp", "ESRI Shapefile")]:

    drv = gdal.GetDriverByName( driverName )


    ds = drv.Create( filename, 0, 0, 0, gdal.GDT_Unknown )
    if ds is None:
        print("Creation of output file failed.\n")
        sys.exit( 1 )

    lyr = ds.CreateLayer( "abc", None, ogr.wkbMultiPolygon25D )
    if lyr is None:
        print("Layer creation failed.\n")
        sys.exit( 1 )

    field_defn = ogr.FieldDefn( "Name", ogr.OFTString )
    field_defn.SetWidth( 32 )

    if lyr.CreateField ( field_defn ) != 0:
        print("Creating Name field failed.\n")
        sys.exit( 1 )

    multipolygon = ogr.Geometry(ogr.wkbMultiPolygon25D)
    for cs in coords_bad:
        ring = ogr.Geometry(ogr.wkbLinearRing)
        for c in cs:
            ring.AddPoint(c[0], c[1], c[2])

        poly = ogr.Geometry(ogr.wkbPolygon25D)
        poly.AddGeometry(ring)
        multipolygon.AddGeometry(poly)

    name = "p1"

    feat = ogr.Feature( lyr.GetLayerDefn())
    feat.SetField( "Name", name )
    feat.SetGeometry(multipolygon)

    if lyr.CreateFeature(feat) != 0:
        print("Failed to create feature in shapefile.\n")
        sys.exit( 1 )

    feat.Destroy()

    ds = None


for filename, driverName in [("abc.geojson", "GeoJSON"),
                             ("abc.gpkg", "GPKG"),
                             ("abc.shp", "ESRI Shapefile")]:

    print("")
    print("Driver: {}".format(driverName))

    driver = ogr.GetDriverByName(driverName)
    dataSource = driver.Open(filename, 0)
    layer = dataSource.GetLayer()

    for feat in layer:
        geom = feat.GetGeometryRef()
        print(geom.ExportToWkt())


```

Output:

```
GDAL: 3.0.4

Driver: GeoJSON
MULTIPOLYGON (((0 0 0,1 0 0,0 0 1,0 0 0)),((0 0 0,0 1 0,1 0 0,0 0 0)))

Driver: GPKG
MULTIPOLYGON (((0 0 0,1 0 0,0 0 1,0 0 0)),((0 0 0,0 1 0,1 0 0,0 0 0)))

Driver: ESRI Shapefile
POLYGON ((0 0 0,0 1 0,1 0 0,0 0 0),(0 0 0,1 0 0,0 0 1,0 0 0))

```

```
ogrinfo -al -q -sql "select st_isvalid(geom) from abc" abc.gpkg 
GEOS warning: Too few points in geometry component at or near point 0 0 0

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalid(geom) (Integer) = 0
```

**Comment by rouault** [comment]
The issue here is that the geometry you're writing is a couple of non-coplanar faces.

The mapping between the Simple Features geometry model used by OGR and the GeoJSON or GPKG formats is straightforward. There is no need for any geometry/topology check. So OGR trusts the user to provide a valid SF geometry, and on reading, the same, it trust the encoded geometry to be SF compliant. If those assumptions are not met, then round-tripping is still possible because of the 1-1 match between SF and those encoding

For shapefile, the situation is different. Shapefile has no concept of Polygon vs MultiPolygon. This is the same geometry type. Only the winding order of rings determine what is a hole from a non-hole. But the concept of winding order only properly works with faces with a constant Z, and OGR on writing & reading of shapefiles just ignores the Z component to determine the winding order.

I'm not completely sure about what a fix could be. Running a validity test has a cost, and furthermore GEOS validity check is 2D only, so it rejects valid geometries that don't have a Z=constant plane.

**Comment by rbuffat** [comment]
@rouault Thanks for the information! We will document the valid geometry assumption within Fiona.
