### ISSUE TITLE
GTIFF_USE_DEFER_STRILE_LOADING needs to be documented

### ISSUE THREAD

**Issue by talaj** [OSGeo/gdal#2368]
I have found that such an important option as [`GTIFF_USE_DEFER_STRILE_LOADING`](https://github.com/OSGeo/gdal/blob/859e42f12732556ca197183f0a51babddea5e000/gdal/frmts/gtiff/geotiff.cpp#L12493-L12494) is nowhere documented.

I was expecting tile/strip offset/bytecount to load into memory during dataset opening to be able to share the memory with child processes after fork on linux. It took me some time to dig the option out of the code.

Setting the option to `NO` not only saves memory in my use case but it also improved performance of random read 5 times (!) in my case with `/vsiswift/`.

**Comment by talaj** [comment]
I'm sorry, the information about 5 times speedup is wrong. I accidentally tested it against different `/vsicurl/` which is way faster.

But the part with memory holds.

**Comment by rouault** [comment]
You are venturing in completely unsupported territory. Using the same GDALDataset* accross fork() is completely unspecified behaviour. That it works in your use case, using /vsicurl/ or derived filesystems, is a matter of pure luck, due to the way /vsicurl/ currently handles Curl handles. This could break at any time. If instead of using a /vsicurl/ file, you used a regular file, then it won't work at all since the underlying file resource would be shared by the parent and children processes, which would lead to racy reads.

So I will close this as wontfix. This option was mostly a provision for testing/debugging, not intended to be used in production.

**Comment by talaj** [comment]
I know that file descriptions are shared between parent and child process, but that can be workaround by mmaping them and using /vsimem/. Is that also wrong?

**Comment by rouault** [comment]
> hat can be workaround by mmaping them and using /vsimem/

Should probably work. One way of avoiding the explicit use of GTIFF_USE_DEFER_STRILE_LOADING is to read a first block in the parent process before forking the children. This will initialize the arrays for the tile offsets and byte counts.

**Comment by talaj** [comment]
> This will initialize the arrays for the tile offsets and byte counts.

Is it really always true? By experience and by reading https://github.com/OSGeo/gdal/commit/12e567f600dadddf4b4ea9bcc2e8120899297d8c it seems that reading a first block may not be suffissient to always preallocate all needed memory.

**Comment by rouault** [comment]
It should preallocate all the memory, unless my memories are bad. The values will be initialized to a dummy 0xFFFFFFFFFFFFFFFF value, which will be a hint for libtiff to lazy read the offset/bytecount value from the file.
