### ISSUE TITLE
building with ECW SDK 5.5 fails with undefined references

### ISSUE THREAD

**Issue by chrisgraf** [OSGeo/gdal#2657]
## Expected behavior and actual behavior.
I expect the build system to build GDAL or inform about missing or incompatible libraries
but I get (after a sucessful ./configure) the following error messages during make:
``` 
make[1]: Leaving directory '/home/graf/landscapelab/gdal/gdal'
(cd apps; make)
make[1]: Entering directory '/home/graf/landscapelab/gdal/gdal/apps'
/bin/bash /home/graf/landscapelab/gdal/gdal/libtool --mode=link --silent g++  gdalinfo_bin.lo  /home/graf/landscapelab/gdal/gdal/libgdal.la  -o gdalinfo
/usr/bin/ld: /home/graf/landscapelab/gdal/gdal/.libs/libgdal.so: undefined reference to `NCS::CString::utf8_str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/usr/bin/ld: /home/graf/landscapelab/gdal/gdal/.libs/libgdal.so: undefined reference to `NCS::CIOStream::GetStreamCounters[abi:cxx11]()'
/usr/bin/ld: /home/graf/landscapelab/gdal/gdal/.libs/libgdal.so: undefined reference to `NCS::CString::Utf8Encode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)'
/usr/bin/ld: /home/graf/landscapelab/gdal/gdal/.libs/libgdal.so: undefined reference to `NCS::CView::SetTransformList(int, std::__cxx11::list<NCS::API::ITransform*, std::allocator<NCS::API::ITransform*> >&)'
/usr/bin/ld: /home/graf/landscapelab/gdal/gdal/.libs/libgdal.so: undefined reference to `NCS::CString::Utf8Decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [GNUmakefile:90: gdalinfo] Error 1
make[1]: Leaving directory '/home/graf/landscapelab/gdal/gdal/apps'
make: *** [GNUmakefile:123: apps-target] Error 2
``` 

## Steps to reproduce the problem.

``` 
$ ./configure --with-ecw=/<path>/<to>/ERDAS-ECW_JPEG_2000_SDK-5.5.0 --with-libtiff=internal --with-geotiff=internal
$ make
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

latest sources from github (https://github.com/OSGeo/gdal/commit/3554675bbce8dc00030bac33c99d92764d0f3844)

**Comment by rouault** [comment]
I strongly suspect this is another symptom of https://github.com/OSGeo/gdal/issues/2394 , related to ECW SDK including a libstdc++ not compatible of the compiler you use

**Comment by chrisgraf** [comment]
thanks for your answer! What is the latest GDAL-Version and ECW SDK Version combination which is known to work?

**Comment by rouault** [comment]
This is not a matter of GDAL version, but more of operating system version / compiler you use. I don't know exactly. Perhaps @jbowman-hexagon would know

**Comment by chrisgraf** [comment]
i see. I have the latest Ubuntu (20.04) with gcc/g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0 .. would be great if anybody can help me with finding a working setup!

**Comment by rouault** [comment]
Works well for me on Ubuntu 16.04 with gcc 5.5

**Comment by jbowman-hexagon** [comment]
Hi all, I have a working Ubuntu 18.04 VM with kernel: 4.15.0-106-generic #107-Ubuntu SMP and gcc 7.5.0 (7.5.0-3ubuntu1~18.04). GDAL 3.2.0-dev with ECW SDK 5.5. I am investigating #2394, and may be able to look at this as well. @chrisgraf Currently building with your configure options (on Ubuntu 18) and will try to spin up an Ubuntu 20.04 vm and compile with that overnight.

**Comment by jbowman-hexagon** [comment]
@chrisgraf what was the GDAL and PROJ version (or commit) you are trying to use? Perhaps I'm doing something wrong but if I try to ./configure with PROJ latest the script exits with 'error: proj.h not found' at the checking for PROJ >= 6 step. As mentioned I am spinning up an Ubuntu 20 VM and will see what happens

**Comment by rouault** [comment]
> what was the GDAL and PROJ version (or commit) you are trying to use?

From my initial analysis, this is likely not relevant. GDAL >= 3 indeed needs PROJ >= 6. Ubuntu 20.04 has PROJ 6.3.1 available.

**Comment by chrisgraf** [comment]
@jbowman-hexagon PROJ Rel. 6.3.1, February 10th, 2020 and GDAL was master with the last commit 3554675bbce8dc00030bac33c99d92764d0f3844

**Comment by jbowman-hexagon** [comment]
@chrisgraf This may be related to the older/newer C++ ABI. As it appears you are not explicitly selecting either, GCC 9 would (I'm assuming) default to the new ABI. In that case, have a look in the ECW SDK directory for the 'lib' dir. If you can see two subdirectories, 'cpp11abi' and 'x64' - Try renaming x64 to something else (this is the old ABI, we won't be using it here), and moving/copying/symlink the x64 directory UNDER the cpp11abi dir, to be directly inside the top-level 'lib' dir. Under x64 there should be debug and release dirs, keep this structure otherwise as-is.

**Comment by jbowman-hexagon** [comment]
I'd forgotten that I needed to do this under Ubuntu 18. Currently building on Ubuntu 20, but it seems to have fixed the compilation/linking issue.
![ECWSDK LIBDIR LINK OLDNEWABI](https://user-images.githubusercontent.com/64939302/86560847-d997f880-bf91-11ea-8b72-f343b2c923d6.PNG)

**Comment by chrisgraf** [comment]
@jbowman-hexagon I tried to apply your change and build gdal from scratch but I get the same error messages :/

**Comment by jbowman-hexagon** [comment]
Yes, I discovered later that day I was incorrect. Apologies. Unfortunately I don't foresee having enough available time to look further into this in the immediate future, but I could suggest a couple of other things you might like to try, and I think have a chance to resolve things.
- Older GCC. We officially support 5.1 and 8.3, I've also used 7.x successfully IIRC.
- Older GDAL. Try 3.0.x as a starting point.

Apologies I cannot assist much further at least for now, I have a few bugs to track down including one Even mentioned above. If he proves to be correct in suspecting a link between that one and this, however, I'll post any extra relevant information I discover.

Also ECW SDK 5.5 Update 2 will be released in a month or so (roughly), this may or may not improve the situation.

**Comment by jmckenna** [comment]
I also hit these many 5.5 SDK issues a few months ago: solved with falling back to SDK 5.4

**Comment by jbowman-hexagon** [comment]
Thanks for comment @jmckenna . That seems slightly odd to me as I've been building and using 5.5SDK with multiple OSes , compilers and options. My only thought (at least off the top of my head) is that it then may be dependent on ./configure options and/or Unicode-related issue(s)

**Comment by jbowman-hexagon** [comment]
Or possibly as @rouault suggests, a compiler and/or OS related issue. If we can compile (no pun intended) information here I can at the very least refer to it in future if the priority somehow were to increase, or possibly relating to other issues. Sadly we cannot hunt all bugs all the time, and have not see this enough at this point in time to justify putting it ahead of others. Definitely appreciate the input, however.

**Comment by rduivenvoorde** [comment]
For reference, I hit this (building gdal 3.1 (because that is what ecw lib 5.5.0 mentions), gcc 10.2 on Debian Testing.

And after the 'move x64 dir, and link to cpp11abi/x64 dir'-trick mentioned above all succeeded \o/

**Comment by eusoubrasileiro** [comment]
@rduivenvoorde thanks a lot!!! After struggling here a lot.

I can confirm just made it work using the SDK 5.5.0 after hitting the same.  Following you after @jbowman-hexagon suggestion the `cpp11abi` folder is the solution. 

In make case I had to `export LD_LIBRARY_PATH=/your-hexagon-sdk-path/lib/cpp11abi/x64/release:$LD_LIBRARY_PATH` 
before `make -j$(nproc)` Don't know why

**Comment by slaicha** [comment]
I'm facing the same errors as those above. I downloaded ECW SDK 5.5. I wanted to try 5.4 but couldn't find it online. For GDAL, I tried the latest version 3.9, and two others 3.5.3 and 3.1.3. I couldn't compile the first one. For, the last two versions, I got the same errors as above. Any thoughts on how I can troubleshoot this?

**Comment by atirage21** [comment]
@parisa-hr
Description
[parisa-hr](https://github.com/parisa-hr)
opened [on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issue-1857661392) · edited by [parisa-hr](https://github.com/parisa-hr)

I want to load ECW maps in QGIS 3.22 In ubuntu 22.04
I ran the latest version (master repo) of the code with Qt 5.15 and also tried it by installing it ( QGIS 3.22.4-Białowieża)
In both ways, I can't load .ecw maps

I also tried StackOverflow questions said like [this](https://gis.stackexchange.com/q/27247/200592) or [this GitHub repo](https://github.com/bogind/libecwj2-3.3) but the problem is that these ways are too old and they didn't work.

    Invalid Data Source:
    /home/parisa/Downloads/apps/BlueMarble/ttMaps/Maps/BlueMarble/01.ecw
    is not a valid or recognized data source.

image

image

I also ask it in [this stack overflow thread](https://gis.stackexchange.com/questions/465362/how-open-ecw-maps-in-qgis-3-22) and I also download ECWJP2SDKSetup_5.5.0.2268-Update4-Linux.zip and run ECWJP2SDKSetup_5.5.0.2268.bin but it didnt help.
I don't know how add and install correct version of gdal in Ubuntu 22.04 to load ECW maps in QGIS.
Versions

QGIS 3.22.4-Białowieża

and

QGIS 3.28 and the latest version under development (master branch)

Please help me I am not a master in GIS.
Activity
rouault
rouault commented on Aug 19, 2023
[rouault](https://github.com/rouault)
[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1684939919)
Member

You need to build your QGIS version against the GDAL version with ECW support. Sorry I can't give more explanations as it would be too tedious and it is out of the scope of a ticket (which is about a bug, here it is "just" an installation issue)
A workaround is you have a GDAL version with ECW support is to use gdal_translate to convert those to cloud optimized geotiffs: gdal_translate your.ecw your.tif -of COG
[rouault](https://github.com/rouault)
closed this as [completed](https://github.com/OSGeo/gdal/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3Acompleted)[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#event-10136013315)
parisa-hr
parisa-hr commented on Aug 19, 2023
[parisa-hr](https://github.com/parisa-hr)
[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685086025) · edited by [parisa-hr](https://github.com/parisa-hr)
Author

@rouault Thanks for your response.
I tried all ways I could find in StackOverflow or others but they didn't work.
I can't find a way to install the GDAL version with ECW (I don't know what is the correct way to build it).

    I download ECWJP2SDKSetup_5.5.0.2268-Update4-Linux.zip from [hexagon](https://supportsi.hexagon.com/s/article/ERDAS-ECW-JP2-SDK-Read-Only-Redistributable-download)
    chmod +x ECWJP2SDKSetup_5.5.0.2268.bin
    ./ECWJP2SDKSetup_5.5.0.2268.bin
    sudo ln -s /usr/local/Desktop_Read-Only/lib/x64/release/libNCSEcw.so.5.5.0 /usr/local/lib/libNCSEcw.so.5.5.0

and I also install proj-8.2.1

cd proj-8.2.1
mkdir build
cd build
cmake ..
make -j$(nproc)
sudo make install

But I cant build gdal -with-ecw=/usr/local/lib/libNCSEcw.so.

I tried

wget -c http://download.osgeo.org/gdal/3.4.1/gdal-3.4.1.tar.gz
tar -xvzf gdal-3.4.1.tar.gz
cd gdal-3.4.1
./configure --with-ecw=/usr/local/lib/libNCSEcw.so.5.4.0

# Compile- takes a lot of time... 
make -j$(nproc)

sudo make install

and also the latest version of Gdal 3.7.1.

In Gdal 3.7.1. I don't know how to build and link it with Ecw because it uses CMake and doesn't have ./configure on the other hand I never succeeded to build gdal-3.4. by the way I said it seems it doesn't compatible with ECWJP2SDKSetup_5.5.0.

please help me, although it seems that it's an installation issue I am stuck in it and I have no idea.

I follow this instructions :

https://gis.stackexchange.com/questions/429214/installing-qgis-with-ecw-support-on-ubuntu-20-04/434980?noredirect=1#comment760078_434980

and also ask it in this thread:

https://gis.stackexchange.com/questions/465362/how-open-ecw-maps-in-qgis-3-22
rouault
rouault commented on Aug 19, 2023
[rouault](https://github.com/rouault)
[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685087747)
Member

hum from your screenshot, it seemed you already have a GDAL build with ECW support
try cmake -DECW_ROOT=/path/to/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only with GDAL 3.7.1 . cf https://gdal.org/development/building_from_source.html#ecw
.
parisa-hr
parisa-hr commented on Aug 19, 2023
[parisa-hr](https://github.com/parisa-hr)
[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685093075)
Author

    hum from your screenshot, it seemed you already have a GDAL build with ECW support try cmake -DECW_ROOT=/path/to/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only with GDAL 3.7.1 . cf https://gdal.org/development/building_from_source.html#ecw .

Thank you So much @rouault for your help and response.

now I got :

/usr/bin/ld: ../libgdal.so.33.3.7.1: undefined reference to `NCS::CView::SetTransformList(int, std::__cxx11::list<NCS::API::ITransform*, std::allocator<NCS::API::ITransform*> >&)'
/usr/bin/ld: ../libgdal.so.33.3.7.1: undefined reference to `NCS::CString::Utf8Decode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ../libgdal.so.33.3.7.1: undefined reference to `NCS::CString::utf8_str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const'
/usr/bin/ld: ../libgdal.so.33.3.7.1: undefined reference to `NCS::CString::Utf8Encode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)'
/usr/bin/ld: ../libgdal.so.33.3.7.1: undefined reference to `NCS::CIOStream::GetStreamCounters[abi:cxx11]()'
collect2: error: ld returned 1 exit status
gmake[2]: *** [apps/CMakeFiles/gdalinfo.dir/build.make:98: apps/gdalinfo] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:9835: apps/CMakeFiles/gdalinfo.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2


image

I find this :
https://lists.osgeo.org/pipermail/gdal-dev/2016-December/045683.html

Do you know how can I fix this too?
rouault
rouault commented on Aug 19, 2023
[rouault](https://github.com/rouault)
[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685094807)
Member

what is the output of "grep ECW CMakeCache.txt" ?

on my system:

ECW_INCLUDE_DIR:PATH=/home/even/hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only/include
ECW_LIBRARY:FILEPATH=/home/even/hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only/lib/cpp11abi/x64/release/libNCSEcw.so
ECW_ROOT:UNINITIALIZED=/home/even/hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only
GDAL_ENABLE_DRIVER_ECW:BOOL=ON
//Set ON to build GDAL ECW driver as plugin
GDAL_ENABLE_DRIVER_ECW_PLUGIN:BOOL=ON
//Set ON to use ECW
GDAL_USE_ECW:BOOL=ON
//ADVANCED property for variable: ECW_INCLUDE_DIR
ECW_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: ECW_LIBRARY
ECW_LIBRARY-ADVANCED:INTERNAL=1
//Details about finding ECW
FIND_PACKAGE_MESSAGE_DETAILS_ECW:INTERNAL=[/home/even/hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only/lib/cpp11abi/x64/release/libNCSEcw.so][/home/even/hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only/include][v5.5()]
//Old value of option GDAL_ENABLE_DRIVER_ECW_PLUGIN
GDAL_ENABLE_DRIVER_ECW_PLUGIN_OLD_VAL:INTERNAL=ON

parisa-hr
parisa-hr commented on Aug 19, 2023
[parisa-hr](https://github.com/parisa-hr)
[on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685101074)
Author

    ECW_INCLUDE_DIR

I changed  cmake -DECW_ROOT=/usr/local/Desktop_Read-Only/ .. to  cmake -DECW_ROOT=/usr/local/lib/ .. and after that it build and installed successfully without errors.

image


//Path to a library.
ECWC_LIBRARY:FILEPATH=/usr/local/lib/libNCSEcwC.so

//Path to a library.
ECWJ_LIBRARY:FILEPATH=ECWJ_LIBRARY-NOTFOUND

//Path to a file.
ECW_INCLUDE_DIR:PATH=/usr/local/include

//Path to a library.
ECW_LIBRARY:FILEPATH=/usr/local/lib/libNCSEcw.a

//No help, variable specified on the command line.
ECW_ROOT:UNINITIALIZED=/usr/local/lib/

//Path to a library.
ECWnet_LIBRARY:FILEPATH=/usr/local/lib/libNCSCnet.so

//Enable Deflate64 decompression
ENABLE_DEFLATE64:BOOL=ON

//Build GNM (Geography Network Model) component
ENABLE_GNM:BOOL=ON

//Enable Inter-Procedural Optimization if possible
ENABLE_IPO:BOOL=OFF

//Set ON to enable Persistent Auxiliary Metadata (.aux.xml)
ENABLE_PAM:BOOL=ON

//The directory containing a CMake configuration file for EXPAT.
EXPAT_DIR:PATH=/usr/lib/x86_64-linux-gnu/cmake/expat-2.4.7

//Expected libjpeg version number
EXPECTED_JPEG_LIB_VERSION:STRING=

//Use find_package2 for dependency ARCHIVE
FIND_PACKAGE2_ARCHIVE_ENABLED:BOOL=TRUE

//Use find_package2 for dependency CFITSIO
FIND_PACKAGE2_CFITSIO_ENABLED:BOOL=TRUE

//Use find_package2 for dependency Crnlib
FIND_PACKAGE2_Crnlib_ENABLED:BOOL=TRUE

//Use find_package2 for dependency GTA
FIND_PACKAGE2_GTA_ENABLED:BOOL=TRUE

//Use find_package2 for dependency HEIF
FIND_PACKAGE2_HEIF_ENABLED:BOOL=TRUE

//Use find_package2 for dependency JXL
FIND_PACKAGE2_JXL_ENABLED:BOOL=TRUE

//Use find_package2 for dependency JXL_THREADS
FIND_PACKAGE2_JXL_THREADS_ENABLED:BOOL=TRUE

//Use find_package2 for dependency KEA
FIND_PACKAGE2_KEA_ENABLED:BOOL=TRUE

//Use find_package2 for dependency PDFIUM
FIND_PACKAGE2_PDFIUM_ENABLED:BOOL=TRUE

//Path to a file.
FREEXL_INCLUDE_DIR:PATH=/usr/include

//Path to a library.
FREEXL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfreexl.so

//Path to a library.
FYBA_FYBA_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfyba.so

//Path to a library.
FYBA_FYGM_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfygm.so

//Path to a library.
FYBA_FYUT_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libfyut.so

But gdalinfo --formats | grep ECW still said

ECW -raster- (rw): ERDAS Compressed Wavelets (SDK 3.x)
JP2ECW -raster,vector- (rw+v): ERDAS JPEG2000 (SDK 3.x)

image
[parisa-hr](https://github.com/parisa-hr)
parisa-hr commented [on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685101778)
parisa-hr
on Aug 19, 2023
Author

another question, should I reinstall QGIS now?
Because I still cant open .ecw maps there .
parisa-hr
[parisa-hr](https://github.com/parisa-hr) commented [on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685106387)
parisa-hr
on Aug 19, 2023
Author

image

gdalinfo --version
GDAL 3.7.1, released 2023/07/06 (debug build)
Segmentation fault (core dumped)

why it said Segmentation fault (core dumped)?

am I installing it correctly?
[rouault](https://github.com/rouault)
rouault commented [on Aug 19, 2023](https://github.com/OSGeo/gdal/issues/8239#issuecomment-1685111583)
rouault
on Aug 19, 2023
Member

    why it said Segmentation fault (core dumped)?

cf https://github.com/OSGeo/gdal/issues/7100
[timlinux](https://github.com/timlinux)
mentioned this [on Jan 16](https://github.com/OSGeo/gdal/issues/8239#event-1931375971)

    [Update information about ECW support in FAQ qgis/QGIS-Website#522](https://github.com/qgis/QGIS-Website/pull/522)

atirage21
atirage21 commented 13 minutes ago
[atirage21](https://github.com/atirage21)
[13 minutes ago](https://github.com/OSGeo/gdal/issues/8239#issuecomment-3393684246) · edited by [atirage21](https://github.com/atirage21)

I tried and tried with succesful steps for ERDAS ECW/JP2 SDK v5.5 Update 6:

unzip ECWJP2SDKSetup_5.5.0.2421-Update6-Linux.zip
cd ECWJP2SDKSetup_5.5.0.2421-Update6-Linux
chmod +x ./ECWJP2SDKSetup_5.5.0.2421.bin
./ECWJP2SDKSetup_5.5.0.2421.bin

dir to home/
sudo cp -r hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only /usr/local/hexagon
sudo ln -s /usr/local/hexagon/lib/x64/release/libNCSEcw.so /usr/local/lib/libNCSEcw.so

sudo unzip proj-9.4.1.zip
cd proj-9.4.1.zip; mkdir build
cd build; sudo cmake ..
sudo make -j$(nproc)
sudo make install

unzip gdal-3.11.3.zip; cd gdal-3.11.3
cmake -DCMAKE_PREFIX_PATH=/home/user_name/gdal-3.11.3 -DECW_ROOT=/usr/local/hexagon
cmake --build .
sudo cmake --build . --target install

and after then for activation in qgis:

sudo cp /usr/local/lib/* /lib/
export LD_LIBRARY_PATH=//usr/local/hexagon/lib/cpp11abi/x64/release:$LD_LIBRARY_PATH
echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.profile
echo 'export LD_LIBRARY_PATH=/usr/local/lib' >> ~/.bashrc
GDAL_DATA="/usr/local/share/gdal"
sudo ldconfig
