### ISSUE TITLE
Static GDAL for R packages

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/gdal#2672]
This may be related to https://github.com/OSGeo/gdal/issues/2669, and this is referred to by https://github.com/OSGeo/PROJ/issues/2084. Brian Ripley (with permission) comments on building GDAL 3.0.1 static using PROJ 7.0.1 static:

```
GDAL.  They have

  --with-proj=ARG Compile with PROJ.x (ARG=yes or path)
  --with-proj-extra-lib-for-test=ARG   Additional libraries to pass the 
detection test, but not used for libgdal linking (i.e. -lcurl -ltiff ...).
Mainly for static libproj

but it seems they only implemented the second if --with-proj= is a path. 
 So easy patch:

--- configure.ac.orig   2020-05-04 10:18:28.000000000 +0100
+++ configure.ac        2020-06-10 09:49:22.000000000 +0100
@@ -1230,7 +1230,7 @@

   if test "x$with_proj" = "xyes" -o "x$with_proj" = "x"; then
     ORIG_LIBS="$LIBS"
-    LIBS="-lproj $ORIG_LIBS"
+    LIBS="-lproj -lsqlite3 $with_proj_extra_lib_for_test $ORIG_LIBS"
     AC_LANG_PUSH([C++])
     AC_CHECK_LIB(proj,proj_create_from_wkt,PROJ_FOUND=yes,PROJ_FOUND=no,)
     AC_LANG_POP([C++])

```
On master the lines start at 1451, rather than 1231; the affected line is 1453 in master.

**Comment by SpaceIm** [comment]
This is probably not related to #2669 because #2669 is about `NMake` build, not `autotools`.

Anyway, having created GDAL recipe for conan (many triplets supported), I can say that GDAL's `autoconf.ac` is very fragile.
This is the patch for conan (which might not work for other package managers, since it relies on pkconfig files generated for several dependencies, and also because conan always prefer external libs): https://github.com/conan-io/conan-center-index/blob/master/recipes/gdal/all/patches/fix-autotools.patch
