### ISSUE TITLE
Opening a File GDB changes a date/time field

### ISSUE THREAD

**Issue by rgnixon** [OSGeo/gdal#2719]
I extract a File Geodatabase from ArcGIS Online.
I drag and drop it into QGIS 3.14 64-bit (Windows 10).
My locale is correct as New Zealand, timezone +1200.

The bottom two (out of four) Date/Time fields are changed.
![qgis_datetime](https://user-images.githubusercontent.com/28893310/85499636-1aa91800-b636-11ea-8e41-3afdb747e67d.jpg)

**Comment by rouault** [comment]
Can you attach a zip with the .gdb that shows this ?

**Comment by rgnixon** [comment]
I think this is the one with the above data.
[Extract_Data_23_Jun_2020__8_22_40_AM.zip](https://github.com/OSGeo/gdal/files/4824434/Extract_Data_23_Jun_2020__8_22_40_AM.zip)

**Comment by rouault** [comment]
Note for other readers: this ticket comes from https://github.com/qgis/QGIS/issues/37369

Checking with ogrinfo, I see it reports dates as in the QGIS screen capture:
```
OGRFeature(surveyPoint):359
  globalid (String) = {25A021A0-5E0D-4B9C-A882-BF5161F20447}
  what_did_you_kill (String) = male
  CreationDate (DateTime) = 2020/06/22 07:49:36
  Creator (String) = tahrNZ
  EditDate (DateTime) = 2020/06/22 07:49:36
  Editor (String) = tahrNZ
  POINT (171.000360362 -43.550532545)

OGRFeature(surveyPoint):360
  globalid (String) = {04B40304-CF22-400E-A63B-2CC45D77B49D}
  what_did_you_kill (String) = male
  CreationDate (DateTime) = 2020/06/22 09:15:06
  Creator (String) = tahrNZ
  EditDate (DateTime) = 2020/06/22 09:15:06
  Editor (String) = tahrNZ
  POINT (169.91684956 -44.0882653789999)

OGRFeature(surveyPoint):361
  globalid (String) = {4762601C-02FA-4F09-BF0F-C0CD31110AB4}
  what_did_you_kill (String) = male
  CreationDate (DateTime) = 2020/06/22 19:42:50
  Creator (String) = tahrNZ
  EditDate (DateTime) = 2020/06/22 19:42:50
  Editor (String) = tahrNZ
  POINT (170.877577309 -43.2116482869999)

OGRFeature(surveyPoint):362
  globalid (String) = {46BB623D-5E6D-48CA-9762-4B9B3756B609}
  what_did_you_kill (String) = male
  CreationDate (DateTime) = 2020/06/22 19:42:52
  Creator (String) = tahrNZ
  EditDate (DateTime) = 2020/06/22 19:42:52
  Editor (String) = tahrNZ
  POINT (170.890896575 -43.206170014)
```
OGR sets those datetime with a tzflag = 0 which means unknown. Looking a bit around, I can't really determine if there's a convention regarding the timezone of datetime fields in FileGeodatabase (unknown, localtime, GMT... ?). @nyalldawson any idea ?

Actually I see from https://support.esri.com/en/technical-article/000015876 that exports from ArcGIS online use UTC convention, but I'm not sure if this is just a specific behaviour of this workflow, or if all FileGeodatabae are supposed to use UTC.

In any case, OGR would not do any UTC <--> localtime conversion. So the issue here is to determine if it must qualify the datetime with a unknown, localtime or UTC timezone flag. Then that QGIS decides to do or not do a conversion to localtime is a QGIS behaviour.

**Comment by nyalldawson** [comment]
Hm - if you look in the "GDB_Items" table (a0000000004) the definition XML contains an attribute:

    <IsTimeInUTC>true</IsTimeInUTC>

(at least in some data files I checked)

My suspicion: a GDB table is either in UTC or local time (for the creator). I suspect that the process of uploading to AGOL is converting the gdb to use UTC. I can do some more digging/testing though...

**Comment by rouault** [comment]
> <IsTimeInUTC>true</IsTimeInUTC>

Good catch. I now use that hint to explicitly set UTC timezone when it is found. From a doc I found at https://enterprise.arcgis.com/en/sdk/latest/windows/IClassSchemaEdit4_IsTimeInUTC.html, the alternative to this is "database" time, whatever that exactly means. So for now, if <IsTimeInUTC>true</IsTimeInUTC> isn't found, the OGR datetime is let with a timezone flag = 0 = unknown.
