### ISSUE TITLE
ogr2ogr fails converting a valid geoJSON to shape file

### ISSUE THREAD

**Issue by belash2** [OSGeo/gdal#2720]
## Expected behavior and actual behavior.

I attempted to convert the attached GeoJSON file into a shape file however the conversion fails due to being unable to open the datastore. The file is a valid geoJSON and it has been verified against the Polygon GeoJSON schema so I expect the conversion to occur successfully.

## Steps to reproduce the problem.

```
ogr2ogr output.sh mod.json
```
where `mod.json` is the supplied file. [mod.zip](https://github.com/OSGeo/gdal/files/4828029/mod.zip)
 
## Operating system

CentOS Linux release 8.2.2004 x64

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28 from EPEL repo

**Comment by jratike80** [comment]
I would say that this is rather a question that belongs to gdal-dev mailing list because it is not sure that you have found a bug. It is also possible that you believed that GDAL works differently that it intentially does. Let's see what will be the conclusion.

GDAL expects that GeoJSON geometries appear inside Feature-geometry structure. Add this into the beginning of your JSON and a couple of closing curly brackets and it will work

```
{"type": "Feature",
"geometry":{
	"coordinates" : 
```
There is a somehow related change into ESRI JSON code in commit https://github.com/OSGeo/gdal/commit/38b0feed67f80ded32be6c508323d862e1a14474#diff-9a29bbc20a853d9a45f8122b9b80f466

I can't say if it is right to require that Feature and geometry exists. Perhaps plain geometry could be enough for some special use cases. The specification is here

https://tools.ietf.org/html/rfc7946#section-3
3.  GeoJSON Object

   A GeoJSON object represents a Geometry, Feature, or collection of
   Features.

The examples in the specification are mostly features. 

```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```
