### ISSUE TITLE
Can not solve libgeotiff unknow symbols

### ISSUE THREAD

**Issue by francoamato** [OSGeo/gdal#2733]
Hi,
I followed the Even Rouault's hint who suggested me to use internal libgeotiff. So i left commented out the GEOTIFF_INC and GEOTIFF_LIB in nmake.opt in shit way:

if using an external libtiff library. Must be libtiff >= 4.0
#TIFF_INC = -Ic:/warmerda/libtiff/libtiff
#TIFF_LIB = c:/warmerda/libtiff/libtiff/libtiff_i.lib

if using an external libgeotiff library
#GEOTIFF_INC = -Ic:/warmerda/libgeotiff -Ic:/warmerda/libgeotiff/libxtiff
#GEOTIFF_LIB = C:/warmerda/libgeotiff/geotiff_i.lib

Unfortunately i am still getting the same errors that I am unable to solve: 

\gdal\frmts\gtiff\gt_wkt_srs.cpp(1318): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_wkt_srs.cpp(1348): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_wkt_srs.cpp(1450): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_wkt_srs.cpp(1640): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_overview.cpp(178): error C2065: 'TIFFTAG_LERC_PARAMETERS': undeclared identifier
\gdal\frmts\gtiff\geotiff.cpp(10942): error C2065: 'LIBGEOTIFF_WARNING': undeclared identifier
\gdal\frmts\gtiff\geotiff.cpp(10953): error C3861: 'GTIFNewEx': identifier not found
\gdal\frmts\gtiff\geotiff.cpp(10956): error C3861: 'GTIFAttachPROJContext': identifier not found

Could it be that proj is the problem? I installed it via OSGeo4W64 package so the conf in nmake.opt are:

# PROJ stuff (required dependency: PROJ >= 6)
PROJ_INCLUDE = -IC:\OSGeo4W64\include
# Note: shell32.lib is needed starting with PROJ 7.0 in some circumstances
PROJ_LIBRARY = C:\OSGeo4W64\lib\proj.lib shell32.lib

**Environment:**
Windows 10 PRO
Visual Studio 2019 Community Edition
GDAL v3.1.1

I hope to get help
Regards

**Comment by rouault** [comment]
Please do not create tickets for that. github issues are not for support requests. That's likely a build issue on your side. Please use the other support channels suggested in the github issue template

**Comment by friesga** [comment]
The compilation problem occurs because a wrong geotiff.h is included. GDAL is dependent on the PROJ header file (proj.h) and library. As https://proj.org/install.html suggests, the simplest way to install PROJ on Windows is to use the OSGeo4W distribution. This distribution however contains much more than just PROJ and the OSGeo4W include folder not only contains proj.h, but also a geotiff.h. Because of the order of include paths this geotiff.h is used, instead of the GDAL's geotiff.h.

The problem can be solved by changing the order of the include paths in gdal-3.1.2\frmts\gtiff\makefile.vc. Put $(TIFF_INC) $(GEOTIFF_INC) in front of $(PROJ_INCLUDE) in EXTRAFLAGS, resulting in "EXTRAFLAGS = -I.. $(PROJ_FLAGS) $(TIFF_INC) $(GEOTIFF_INC) $(PROJ_INCLUDE) $(JPEG_FLAGS) $(LERC_INC) $(ZSTD_FLAGS) $(WEBP_FLAGS) $(ZLIB_FLAGS)".
