### ISSUE TITLE
netcdf subdataset utf-8 path fails to open on windows

### ISSUE THREAD

**Issue by dirkvdb** [OSGeo/gdal#2763]
## Expected behavior and actual behavior.
I would expect the file to open
The file does not open

## Steps to reproduce the problem.
```
{
    auto* ds = GDALOpenEx(u8"C:/België/latlon.nc", GDAL_OF_READONLY | GDAL_OF_RASTER, nullptr, nullptr, nullptr);
    assert(ds != nullptr); // this is ok
}
{
    auto* ds = GDALOpenEx(u8"NETCDF:\"C:/België/latlon.nc\":lat", GDAL_OF_READONLY | GDAL_OF_RASTER, nullptr, nullptr, nullptr);
    assert(ds != nullptr); // this asserts
}
```

My investigation results:
- netcdfdataset:7386 `status2 = nc_open(osFilenameForNCOpen, nMode, &cdfid);` is called with a non utf8 path
- in the netcdf library `nc4_open_file` is called with the non utf-8 path
- the hdf5 `H5Fopen` function gets called which ends up in the `Wopen_utf8` in the hdf5 file H5System.c 
- As this expects a utf-8 path the open fails

## Operating system
Windows 10

## GDAL version and provenance
Gdal version 3.1.2
Netcdf-c: 4.7.4
Hdf5: 1.12.0

**Comment by rouault** [comment]
The situation is quite messy as it is highly dependent on the actual versions of netcdf-c and HDF5. It appears from https://github.com/Unidata/netcdf-c/issues/1786 that since libhdf5 1.10.6, UTF-8 filenames are now expected when using libhdf5 as you spotted. And from https://github.com/Unidata/netcdf-c/pull/1794/files it appears that a candidate fix would be in libnetcdf itself, and there's probably no workaround possible in GDAL itself

When using the HDF5 driver directly (which is the one likely triggered by your first call since the netCDF one fails), things are different since GDAL plugs its own I/O layer in libhdf5 and can thus expects UTF-8 encoded filenames whatever the libhdf5 version.

**Comment by dirkvdb** [comment]
Thanks for the info! Applying https://github.com/Unidata/netcdf-c/pull/1794 to netcdf solved the issue for me.
