### ISSUE TITLE
gdal_sieve: non-georeferenced images get flipped 

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#2830]
If gdal_sieve.py is applied to a non-georeferenced image, the script sets default geotranformation into the output
https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/scripts/gdal_sieve.py#L201
and the pixel size will be
Pixel Size = (1.000000000000000,1.000000000000000)

If the source file is of common top-to-bottom type (png, jpeg) this means that the result image opens flipped around the topmost pixel line in georeferencing-aware software like QGIS.

I suggest to add a de-flip swich to the script or just use negative pixel size for y as a default
`SetGeoTransform([0,1,0,0,0,-1])`.

Similarly gdal_polygonize mirrors the polygons around the top row if source image is a plain png file.

QGIS seems to have some override when it open png images because it does not flip them on screen. However, running raster-conversion-polygonize for such png creates vectors above the image and mirrored.

**Comment by rouault** [comment]
> I suggest to add a de-flip swich to the script or just use negative pixel size for y as a default

I've just done a change to not write a geotransform to the target file when the source has none. This will result in a non-georeference image consistent with the source

> Similarly gdal_polygonize mirrors the polygons around the top row if source image is a plain png file.

That's a different topic. I'm not sure flipping is the right solution, at least by default

**Comment by jratike80** [comment]
I am not sure what would be the right solution either. I was trying to help a user in gis.stackexchange and what happens now  may indeed feel weird for a new GDAL and QGIS user. 

<img width="150" alt="flipped_vectors" src="https://user-images.githubusercontent.com/1751612/89517364-45b08b00-d7e2-11ea-8160-d3f227d1cfa3.png">

**Comment by rouault** [comment]
probably creating a worldfile that results in a  [0,1,0,0,0,-1] geotransform before running polygonize

**Comment by glebpinigin** [comment]
> I am not sure what would be the right solution either. I was trying to help a user in gis.stackexchange and what happens now may indeed feel weird for a new GDAL and QGIS user.
> 
> <img alt="flipped_vectors" width="150" src="https://user-images.githubusercontent.com/1751612/89517364-45b08b00-d7e2-11ea-8160-d3f227d1cfa3.png">

The sorce of problem is a way how non-referenced rasters are interpreted. Y coordinate axis of an arbitrary raster follows the direction from upper side to lower. But for GIS' crs the opposite is true. When GDAL creates polygonized raster it follows numerical values of pixel coordinates (which are positive). When you than open the result vector file in QGIS, it interprets positive y values as values __above__ y-axis' zero. However, QGIS interprets non-georegerenced raster as an arbitrary image and renders positive pixel y values __below__ y-axis' zero to preserve initial image structure. You can notice, that for georeferenced rasters pixel height is usually negative.

So, the solution is following:
1. Open your raster _read-only_
2. Redefine GeoTransform of your raster in such a way that pixel height becomes negative. This step makes sense because you actually want for your result vector files coordinates to be negative
3. Run polygonization

Be aware of opening raster non-read-only. If you change GeoTransform of simpy opened raster, GDAL will white .aux.xml file with new geotransform for this file. Than, it will let QGIS to interpret this raster as a georeferenced image and all this procedure will lose any sense.

Anyway, you should imply this technique if and only if you are working with not georeferenced raster.

For native gdal python wrapper you can use this code:

```
from osgeo import gdal, ogr, osr
from osgeo.gdalconst import GA_ReadOnly
import matplotlib.pyplot as plt
import numpy as np

in_path = 'raster.tiff'

out_path = 'polygonized.shp'

src_ds = gdal.Open(in_path, GA_ReadOnly)

geoTransform = src_ds.GetGeoTransform()
originX = geoTransform[0]
originY = geoTransform[3]
pixelWidth = geoTransform[1]
pixelHeight = geoTransform[5]

src_ds.SetGeoTransform((originX, pixelWidth, 0, -originY, 0, -pixelHeight))
srcband = src_ds.GetRasterBand(1)

targetSR = osr.SpatialReference()
targetSR.ImportFromWkt(src_ds.GetProjectionRef())

srcband = src_ds.GetRasterBand(1)
dst_layername = 'polygonized'
drv = ogr.GetDriverByName("ESRI Shapefile")
dst_ds = drv.CreateDataSource(out_path)

dst_layer = dst_ds.CreateLayer(dst_layername, srs = targetSR )

fld = ogr.FieldDefn("HA", ogr.OFTInteger)
dst_layer.CreateField(fld)
dst_field = dst_layer.GetLayerDefn().GetFieldIndex("HA")

gdal.Polygonize(srcband, None, dst_layer, dst_field, [], callback=None)

del src_ds
del dst_ds
```
