### ISSUE TITLE
World files with non latin letters (on MacOS)

### ISSUE THREAD

**Issue by oskarlin** [OSGeo/gdal#2903]
## Expected behavior and actual behavior.

I expected GDAL to understand my world files but it seems it doesn't pick up filenames with å ä ö in the filenames.

## Steps to reproduce the problem.

This world file is picked up by for example gdalinfo:
file.tif
file.tfw

This not:
föle.tif
föle.tfw

## Operating system

MacOS

## GDAL version and provenance

2.4.2

**Comment by rouault** [comment]
I can't reproduce on Linux. This might be Mac specific, although I'm not sure why

**Comment by jratike80** [comment]
Works in Finland on Windows

```
gdalinfo föle.tif
Driver: GTiff/GeoTIFF
Files: f├Âle.tif
       f├Âle.tfw
Size is 24, 700
```
Console print looks nicer if I change the codepage into UTF8 with chcp 65001. But it is still a bit complicated:
- Running gdal_translate under codepage 850 yields different output file "föle" than running the command with codepage 65001
- If I copy some tif ->föle.tif and tfw->föle.tfw then tfw is not fould; it is found if I create them both together with gdal_translate - weird, isn't it?
- föle.tif is found always by gdalinfo if I play by changing the code page, but föle.tfw only if it is created using the same codepage that I am running the console at the moment, and evan then not always if tfw is created by a copy with Windows
- For testing it is also good to know that .tfw is not read if tiff is a GeoTIFF or if .tif.aux.xml file exists; make clean test data with `gdal_translate -co profile=baseline -co tfw=yes`

If you want to have troubles, use åäö everywhere, if not, don't.

**Comment by dg0yt** [comment]
I can confirm this issue for gdal 3.1.3 on macOS 10.15.6.

**Comment by rouault** [comment]
Would be good if someone with a Mac could investigate that. 
This post seems somewhat relevant : https://stackoverflow.com/questions/6153345/different-utf8-encoding-in-filenames-os-x . I suspect that there might be an issue with ReadDir() returning a UTF8 encoding of ä/ö for the .tfw file that is different from the one of the .tif file, which confuses identification of the .tfw file. Relevant function to break into would be GDALReadWorldFile2(), and checking the value of pszBaseFilename vs the ones of papszSiblingFiles

**Comment by dg0yt** [comment]
I'm trying to investigate on macOS, but with limited macOS know-how. The problem is hard: running the same gdalinfo binary and arguments fails to find the world file on the console, but succeeds in Qt Creator (for debugging). IIUC there is decomposition of some characters. But I don't understand which environment parameter makes the difference, or what is the actual contract.

**Comment by dg0yt** [comment]
> running the same gdalinfo binary and arguments fails to find the world file on the console, but succeeds in Qt Creator (for debugging). 

But if I create data filenames in the shell (by `cp`), I get the opposite pattern: works in the Terminal, but fails in Qt Creator...

**Comment by rouault** [comment]
You need to compare values of GDALReadWorldFile2() parameters byte by byte. I'm afraid solving this will involve some UTF-8 'normalization' logic instead of doing plain C string equalitytesting. Probably hardcoding a few frequent cases, like the one of that ticket, could be a good enough band-aid.

**Comment by dg0yt** [comment]
The problem lies in the string-based approach which is used when the list of sibling files is provided to `GDALReadWorldFile2`. When I disable that part, the function uses regular filesystem calls (`stat`), and everything goes well: The Apple File System will use its regular hash-based approach to resolve normalization, and succeed.

Instead of hardcoding anything (in addition to the already hardcoded capitalization variants), I would suggest to fall through to the filesystem approach on failure even if sibling files are provided. That means removing just one line in `GDALReadWorldFile2`:
https://github.com/OSGeo/gdal/blob/cb2eb771cc5cfc9c53e10549b9eac49103a74b0e/gdal/gcore/gdal_misc.cpp#L2052

However, the same pattern is applied for other sidecar files.

**Comment by rouault** [comment]
> Instead of hardcoding anything (in addition to the already hardcoded capitalization variants), I would suggest to fall through to the filesystem approach on failure even if sibling files are provided.

This could have performance impact, particularly on network based filesystems, so I'd be -1 on this

**Comment by dg0yt** [comment]
> This could have performance impact, particularly on network based filesystems, so I'd be -1 on this

That's the answer which I expected. However, I wonder if impact of `stat` can be that significant, after collecting the names of *all* sibling files.

Anyway, I will try with `GDAL_DISABLE_READDIR_ON_OPEN` set to `TRUE` later. I expect this to provide the desired change in behaviour.

**Comment by dg0yt** [comment]
Setting `GDAL_DISABLE_READDIR_ON_OPEN` to `TRUE` makes `gdalinfo` find worldfiles in all my tests. Maybe this is enough to deal with this problem, as it can be set by users as well by application software when consistent behaviour counts more than performance. However, the option is not in the current documentation, and it effects a number of different sidecar files.

**Comment by rouault** [comment]
I'd appreciate if a Mac user could give a try to https://github.com/OSGeo/gdal/pull/2937 to confirm it fixes the issue
