### ISSUE TITLE
Zoom not working properly in QGIS got referred here to GDAL

### ISSUE THREAD

**Issue by antoniolocandro** [OSGeo/gdal#3091]
Originally asked in the QGIS issue tracker https://github.com/qgis/QGIS/issues/39538 but they mentioned I should ask with the gdal team why the zoom is apparently not working properly. Feature seem to be placed in the correct location. Also there is a bit of a regression on understanding one of the xml nodes "Airspace" from previous version

**Comment by jratike80** [comment]
It does not seem that there is a confirmed bug in GDAL, at least not confirmed yet. The gdal-dev mailing list is our forum for asking questions.

Ogrinfo shows some errors. Perhaps you could have a look and fix the data first if the errors are real?

ogrinfo EA_AIP_DS_FULL_20170701.xml
ERROR 1: Invalid exterior ring
ERROR 1: Non-closed ring
ERROR 1: Invalid exterior ring
ERROR 1: Non-closed ring
ERROR 1: Invalid exterior ring
ERROR 1: segments: Got NULL geometry as Member instead of curve.
ERROR 1: Curve: Got NULL geometry as Member instead of segments.
ERROR 1: Invalid exterior ring

**Comment by jratike80** [comment]
More details:
ERROR 1: Geometry of feature 10 uuid.028e6905-f99a-4ca7-a736-2c0787cdcf58 cannot be parsed: Invalid exterior ring. You may set the GML_SKIP_CORRUPTED_FEATURES configuration option to YES to skip to the next feature

And something really goes wrong with reporting the extent of the geoborder layer also with ogrinfo. The coordinates in the extent are lat-lon while the coordinates in the geometry are lon-lat. Same reason must make QGIS to zoom to wrong place.
```
ogrinfo EA_AIP_DS_FULL_20170701.xml geoborder
INFO: Open of `EA_AIP_DS_FULL_20170701.xml'
      using driver `GML' successful.

Layer name: GeoBorder
Geometry: Line String
Feature Count: 1
Extent: (49.966670, -33.399440) - (56.145560, -30.182780)
...
OGRFeature(GeoBorder):890
  identifier (String) = 6118ba76-0d46-4ba7-af63-17f29755e890
  beginPosition (String) = 2009-01-01T00:00:00Z
  interpretation (String) = BASELINE
  sequenceNumber (Integer) = 1
  timeSlice|GeoBorderTimeSlice|featureLifetime|TimePeriod|beginPosition (String) = 2009-01-01T00:00:00Z
  name (String) = REPUBLICOFDONLON
  type (String) = STATE
  LINESTRING (-31.3833333333333 49.9666666666667,
```

**Comment by antoniolocandro** [comment]
Thank you it works for the most part but I will need to see if the issue is with the file encoding as there are many ways to implement the xml output.
