### ISSUE TITLE
Allow use of km and [nmi_i] for <gml:radius uom="">

### ISSUE THREAD

**Issue by antoniolocandro** [OSGeo/gdal#3118]
Please see attached file, if you try to load in QGIS it will interpret the **km** as degrees and the **[nmi_i]** will prevent the circle from being loaded. However both these units are under UCUM (https://ucum.org/) acceptable. I add the ticket here as previously most of these small issues have been in the gdal driver

Validator
https://ucum.nlm.nih.gov/ucum-lhc/demo.html

![image](https://user-images.githubusercontent.com/4627073/97368716-1fded380-1871-11eb-9af7-6437077f79ad.png)
![image](https://user-images.githubusercontent.com/4627073/97368730-2a00d200-1871-11eb-94cb-489df3a29c9e.png)

These are the two areas I would want to render

![image](https://user-images.githubusercontent.com/4627073/97368804-4e5cae80-1871-11eb-81dd-2f36611b94eb.png)

[test.zip](https://github.com/OSGeo/gdal/files/5448412/test.zip)

**Comment by jratike80** [comment]
Interesting thing and not necessarily a small job to implement. Using projected units with lat-lon coordinates means that the buffered area is oval when it is converted back to lat-lon like in this image.

http://downloads2.esri.com/MappingCenter2007/blog/Mar11Images/Tissots_WGS84.png

**Comment by antoniolocandro** [comment]
To be honest if I use m for meters or NM for Nautical miles it works already (like you mention the area is Oval in WGS84 and a circle in a projected coordinate system) so I was just wanting to extend to be able to use km for kilometers directly and [nmi_i] for Nautical Miles due to the files I receive from the aviation domain.

Would it be too much to just add the ability to understand the two new proposed units as it already does for m and NM?

**Comment by jratike80** [comment]
I do not know how much it would mean. But because you clarified that m an NM are already supported it does probably mean not so much. I suppose that km and nmi_i are included in the OGC GML schemas as uom names.

As you may guess, I am a GDAL user just like you and I try to help other users to improve their bug reports so that the developers have it easier to start thinking about how to resolve the issues. I admit that this time my comment was not so useful. Welcome to community, as an aviation expert you will probably find also other issues to fix.

**Comment by antoniolocandro** [comment]
@jratike80 you are doing an excellent job! It is great you do this to make things easier to devs!

**Comment by rouault** [comment]
[nmi_i] is handled since GDAL 3.1.0 . https://github.com/OSGeo/gdal/pull/3129 will add support for km
