### ISSUE TITLE
Poor Quality in gdal2tiles.py compared to MapTiler

### ISSUE THREAD

**Issue by markhalonen** [OSGeo/gdal#3162]
## Expected behavior and actual behavior.

For the attached PDF, gdal2tiles.py renders tiles with quality such as this: (`17/33136/46115.png`):
![image](https://user-images.githubusercontent.com/7853605/98591845-d5ad1780-229e-11eb-9041-eeff8ffb57b2.png)

It is not as good as MapTiler output:

![image](https://user-images.githubusercontent.com/7853605/98591873-e2ca0680-229e-11eb-87a9-3fffa0a4a629.png)

## Steps to reproduce the problem.
1. Download [916-0013_Harvest_Map.pdf](https://github.com/OSGeo/gdal/files/5513103/916-0013_Harvest_Map.pdf)
2. Run `mkdir out_tiles && gdal2tiles.py --xyz --zoom=12-18 --resampling=cubic 916-0013_Harvest_Map.pdf out_tiles`

`

## Operating system

I am running from my own Dockerfile on Mac that uses `FROM osgeo/gdal:alpine-normal-latest`

## GDAL version and provenance

`FROM osgeo/gdal:alpine-normal-latest`

I have tried `average` `bilinear` and `cubic` sampling methods to no avail. 

I would pay MapTiler for their service, but sadly their command line app fails on my PDF. Their good output is from the Desktop app but I need a scripted version. 

If anyone has any suggestions of options to tweak, I'd be happy to hear them! 

This issue is perhaps similar to https://github.com/OSGeo/gdal/issues/1087

**Comment by markhalonen** [comment]
Ok I found the option `--config GDAL_PDF_DPI 1200`, I saw it mentioned in https://github.com/OSGeo/gdal/issues/2950

It seems much slower, but I can probably figure it out from here. I did not see this option in the `gdal2tiles.py`, I have never used this software so perhaps it's common knowledge that there are some general config values available. 

Maintainers can close this issue unless they want to take action on it

**Comment by jratike80** [comment]
We hope that at least it is common knowledge that there are config options. However, with hundreds of drivers and tens of utility programs it is challenging to document all the features that they have and still keep the documentation rather compact. There is an initiative to collect all configuration options into one page https://gdal.org/user/configoptions.html but the page is far from perfect. For example GDAL_PDF_DPI is still missing, and even when it is added to the page it might not be linked with gdal2tiles because the option is generic and has an effect on any place where PDF is used. Perhaps a better option could be to add a note "Config options of the **input** drivers may have an effect on the output of gdal2tiles" into https://gdal.org/programs/gdal2tiles.html. What do you think, would it have helped you to resolve your issue faster? But also that is common for all the other raster utilities as well. We have a special page for the common options https://gdal.org/programs/raster_common_options.html but unfortunately users often do not find it, probably because search engine hits point directly to the main pages of the utilities.

Every documentation page has also a button "Edit me on GitHub" if you want to take an action on improving the documentation.
