### ISSUE TITLE
i cannot find the definition of struct _CPLMutex

### ISSUE THREAD

**Issue by wise101** [OSGeo/gdal#3184]
i compile a c++ source code which linked GDAL library (the version is 3.1.2).   the envirment is windows 10, VS 2015 x64 . in release mode it is ok，but in debug mode there is a linker error :  pcidskd.lib(pcirasterblock.obj) : error LNK2001: Unresolved external symbols  "public: __cdecl CPLMutexHolder::CPLMutexHolder(void * *,double,char const *,int,int)" (??0CPLMutexHolder@@QEAA@PEAPEAXNPEBDHH@Z)
1>..\..\..\OutDir\Debug_x64\\PixIOd.dll : fatal error LNK1120: 1 external command that cannot be resolved

      i   have checked the related code：

`CPLMutexHolderD( &hRBMutex );`

and i check the definition of CPLMutexHolderD:
`#define CPLMutexHolderD(x)  CPLMutexHolder oHolder(x,1000.0,__FILE__,__LINE__);`

CPLMutexHolder is a class ,its contractor is ：
```
    explicit CPLMutexHolder( CPLMutex **phMutex, double dfWaitInSeconds = 1000.0,
                    const char *pszFile = __FILE__,
                    int nLine = __LINE__,
                    int nOptions = CPL_MUTEX_RECURSIVE);
```
       and i have finded definition of  CPLMutex:
```
#ifdef DEBUG
typedef struct _CPLMutex  CPLMutex;
typedef struct _CPLCond   CPLCond;
typedef struct _CPLJoinableThread CPLJoinableThread;
#else
#define CPLMutex void
#define CPLCond void
#define CPLJoinableThread void
#endif
```

    so you can see in release mode CPLMutex is void type ,in debug mode CPLMutex  is struct _CPLMutex.  the problem is i cannot find the definition of struct _CPLMutex.

**Comment by rouault** [comment]
> there is a linker error : pcidskd.lib(pcirasterblock.obj)

Seeing pcidskd.lib, are you building against an external PCIDSK lib ? If so, that might be the issue if it was built with the non-debug flags of GDAL.
The issue is not that struct _CPLMutex is not exposed (it is intended to be an opaque type), but rather a mix of objects built in debug and release modes.

**Comment by wise101** [comment]
> > there is a linker error : pcidskd.lib(pcirasterblock.obj)
> 
> Seeing pcidskd.lib, are you building against an external PCIDSK lib ? If so, that might be the issue if it was built with the non-debug flags of GDAL.
> The issue is not that struct _CPLMutex is not exposed (it is intended to be an opaque type), but rather a mix of objects built in debug and release modes.

yes, i am building against an external PCIDSK lib. in fact, in external PCIDSK code project   CPLMutexHolderD is used,  it only need to  included header file of  GDAL，not need to link  the lib of GDAL.  when the third party application link PCIDSK lib, at the same time need to link with the lib of GDAL. i confirmed that  in debug mode the lib of GDAL which was linked was built with the debug flags of GDAL.

**Comment by mpdaly** [comment]
@rouault 

I think this is caused by an arguably backwards-incompatible change in the switch to CMake.

These are the old `OPTFLAGS` from https://github.com/OSGeo/gdal/blob/release/3.5/nmake.opt

```
!IF "$(DEBUG)" == "0"
OPTFLAGS= $(CXX_ANALYZE_FLAGS) $(CXX_PDB_FLAGS) /nologo /MP$(CPU_COUNT) /MD /EHsc /Ox /FC /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DNDEBUG
!ELSE
OPTFLAGS= $(CXX_ANALYZE_FLAGS) $(CXX_PDB_FLAGS) /nologo /MP$(CPU_COUNT) /MDd /EHsc /FC /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DDEBUG
!ENDIF
```

Note the `/DDEBUG` on the end of the debug flags.

With CMake builds post-3.5, this line:

https://github.com/OSGeo/gdal/blob/95b5fe12411c2a2acb23fb99d97f99386b4fa608/gdal.cmake#L192

is only present for non-`MSVC` builds. That can affect which `CPLMutex` definition is used, depending on the client compiler flags, and can therefore lead to a mismatch with the compiled `cpl_multiproc.obj` in the GDAL library, and the one expected by the client.

Adding:

`SET CL=/DDEBUG %CL%`

before doing a debug build of GDAL is a simple workaround.

**Comment by rouault** [comment]
> I think this is caused by an arguably backwards-incompatible change in the switch to CMake.

@mpdaly Interesting analysis which causes me to queue https://github.com/OSGeo/gdal/pull/9064
