### ISSUE TITLE
gdalwarp for Orthorectification is not working properly

### ISSUE THREAD

**Issue by WalidGharianiEAGLE** [OSGeo/gdal#3298]
## Expected behavior and actual behavior.

I expect when using gdalwarp along with satellite imagery containing embedded RPC tags and a DEM to Orthorectify the imagery but using a dem does not change the supposed orthorectified imagery  

Im trying to orthorectify satellite data from OrbView-3 and SkySat Basic scene products both comes with embedded RPC metadata. For each product I did get a srtm dem that cover the scenes; here I shared the data from OrbView-3 along the srtm dem (it comes with at WGS 84): 
https://github.com/WalidGharianiEAGLE/orthorectification_python_tutorial/tree/master

## Steps to reproduce the problem.

with srtm 
`gdalwarp --config CPL_DEBUG ON -overwrite -s_srs EPSG:4326 -t_srs EPSG:32632 -rpc -to 'RPC_DEM=srtm.tif' SatData.tif SatData_ortho.tif`
or without srtm data
`gdalwarp --config CPL_DEBUG ON -overwrite -s_srs EPSG:4326 -t_srs EPSG:32632 -rpc SatData.tif SatData_ortho.tif`

I get the same SatData_ortho.tif with both ways which implies that  -to 'RPC_DEM=srtm.tif' is not working properly!

## Operating system

Windows 10 64-bit

## GDAL version and provenance

GDAL 3.0.4

**Comment by underchemist** [comment]
I don't know if relevant, but these are some things I've run into with RPC and GDAL:
- RPC are by definition relative to the WGS84 ellipsoid (in terms of height) and I believe starting in GDAL 3 no vertical shift is done if the DEM SRS has no explicit vertical component, as is the case with SRTM DEMs. I've worked around this by changing the DEM SRS to EPSG:4326+5773. Alternatively, in GDAL >= 3.2 RPC_DEM_SRS is a transformer option which will override the DEM SRS. This doesn't explain your issue, but may be something you run into down the line in order to get accurate orthorectification.
- PROJ_DEBUG=3 would be useful to check if you're getting debug messages related to the DEM to verify GDAL is doing vertical shifting when sampling DEM height values.

**Comment by rouault** [comment]
> I get the same SatData_ortho.tif with both ways which implies that -to 'RPC_DEM=srtm.tif' is not working properly!

I've tried with GDAL master
gdalwarp --config CPL_DEBUG ON -overwrite  -t_srs EPSG:32632 -rpc  3v050905m0000880351a520001100172m_001659557.tif out.tif
and
gdalwarp --config CPL_DEBUG ON -overwrite -s_srs EPSG:4326 -t_srs EPSG:32632 -rpc  3v050905m0000880351a520001100172m_001659557.tif out2.tif -to RPC_DEM=srtm.tif
and the files are definitely different (and processing with RPC_DEM is much slower as expected)

**Comment by WalidGharianiEAGLE** [comment]
As a follow up: 
@rouault The issue was simply related to the use of ' ' in the argument 'RPC_DEM=srtm.tif', with this the dem will not be taken into account for the orthorectification, instead using RPC_DEM=srtm.tif or "RPC_DEM=srtm.tif" will take make it work.

So the supposed orthorectified imagery definitely removed the terrain distortion in the scene especially in the south where high altitudes are recorded from the srtm; this can can be done by displaying the supposed ortho-scene on top of google base map in qgis, Yet the geometric accuracy is not great which I would assume is related to the elevation errors from srtm ( https://www.frontiersin.org/articles/10.3389/feart.2018.00225/full) during the orthorectification.

@underchemist Thank you for the hint! could you elaborate more on this RPC_DEM_SRS=EPSG:4326+5773? The srtm dem are already provided as WGS84 ellipsoidal heights.
Here what I added as arguments after your suggestion:
`gdalwarp --config CPL_DEBUG ON 3v050905m0000880351a520001100172m_001659557.tif 3v050905m0000880351a520001100172m_001659557_gdal_M2_ORdem_26.tif -rpc -to SRC_METHOD=RPC -to RPC_DEM="srtm.tif" -to RPC_DEM_SRS=EPSG:4326+5773` and then (for reprojection) `gdalwarp --config CPL_DEBUG ON -overwrite -s_srs EPSG:4326 -t_srs EPSG:32632 3v050905m0000880351a520001100172m_001659557_gdal_M2_ORdem_26.tif 3v050905m0000880351a520001100172m_001659557_gdal_M2_ORdem_32.tif`
Adding -to RPC_DEM_SRS=EPSG:4326+5773 is not changing anything here!

To refine the geometric accuracy of ortho-scene i took some sample points as reference from google imagery in order to extract the x/y shift needed then took the mean for each, and with R i simply shifted the scene using the shift function https://www.rdocumentation.org/packages/raster/versions/3.4-5/topics/shift, in this case I used `dx=(-7.247), dy=(35.08)` with this, the ortho-scene is much better. 
This could be done with gdal_translate if Im not mistaken as well, so you will have to define the bounding box of the new ortho-scene. 
Any opinion on this with be highly valued by whoever interested in the orthorectification of satellite data! @rouault

**Comment by underchemist** [comment]
@WalidGharianiEAGLE if you're data is already in WGS84 ellipsoid height, then I don't think this provides any benefit. I was speaking from my past experience with SRTM data that had an implicit vertical datum (EGM96) instead of an explicit one, thereby not having any way for GDAL to identify when a vertical shift was necessary.
