### ISSUE TITLE
Error adding feature to FGDB annotation layer

### ISSUE THREAD

**Issue by langefz** [OSGeo/gdal#3431]
When I tried to add features to the FGDB annotation layer by Layer.CreateFeature(Feature feature), it threw an exception like "Failed at writing Row to Table in CreateFeature. (The user does not have permission to execute the operation.)". Is there anyone can help me?

**Comment by mloskot** [comment]
>  Is there anyone can help me?

Yes, if anyone here has a magic crystal ball to guess what you are doing step by step, otherwise
- seek support via https://gdal.org/community.html#mailing-list, not GitHub issues
- if you suspect a bug, then [write a proper bug report](https://www.google.com/search?q=how+to+write+a+good+bug+report) - scraps thrown in lazily don't count as such
