### ISSUE TITLE
OGR datastore (GDB) Unknown geometry type: 3005

### ISSUE THREAD

**Issue by steelraiden** [OSGeo/gdal#3434]
Upgrading geoserver from 2.17.1 to 2.18.2 results in different behaviour when reading layers from the same .gdb data source.
The error I'm getting is
Caused by: java.io.IOException: Unknown geometry type: 3005
	at org.geotools.data.ogr.FeatureTypeMapper.getGeometryBinding(FeatureTypeMapper.java:285)
	at org.geotools.data.ogr.FeatureTypeMapper.getFeatureType(FeatureTypeMapper.java:70)
	at org.geotools.data.ogr.OGRFeatureSource.buildFeatureType(OGRFeatureSource.java:469)
	at org.geotools.data.store.ContentFeatureSource.getAbsoluteSchema(ContentFeatureSource.java:327)

These are my setups:

Configuration that works
- CentOS8
- geoserver 2.17.1
- gdal 3.1 with ecw, with proj 6
- jdk 8

Configuration that doesn't work
- Debian 11
- geoserver 2.18.2
- gdal 3.2.1 with ecw, with proj 7.2.1
- openjdk 11

running "ogrinfo -al file.gdb" returns no errors

let me know if I can supply more info

thanks in advance

**Comment by jratike80** [comment]
You have not identified any bug in GDAL so you should not create a bug report either. We have a mailing list for questions. Gis.stackexchange is also a fine forum for asking questions.

This does not feel like a GDAL bug because obviously GDAL is sending data to Geoserver. It is Geoserver (actually Geotools) that does not know what to do with the data.

Geometry type 3005 is 3D MultiPoint. That does not feel too exotic.

You can make some tests with your Geoserver by creating 3D Multipoint test data into some datastore that Geoserver can read directly without GDAL. I recommend PostGIS. Failure -> Geoserver has problem with any 3D MultiPoint data. Success -> the problem seems to be in the combination of 3D MultiPoints coming from GDAL.

Then you can make GDAL to read 3D MultiPoints from some other source than DGB. I recommend PostGIS. Then you will learn if the problem is exactly FGB->GDAL->Geotools.

A third test that you can do is to convert 3D multipoints into 2D multipoints in your geodatabase. If 2D works it confirms that just 3D MultiPoints make the problem.

What makes it difficult is that you have configurations with 4 different components. Systematic way would be to change just on component at a time but I understand that you may not have control on the whole environment.

**Comment by rouault** [comment]
> Geometry type 3005 is 3D MultiPoint.

no, it is a MultiLineStringZM

But anyway it doesn't sound like a GDAL bug, but more a Geotools limitation in handling that type of geometry. Should be reported to them
