### ISSUE TITLE
ECW in docker

### ISSUE THREAD

**Issue by carlogarro** [OSGeo/gdal#3535]
Hello, is it supported ECW files in the docker version?
I am using the ubuntu full image, and when I do gdalinfo --formats, it does not show up.

Thank you for your help!

**Comment by rouault** [comment]
No, it is not. It is proprietary software, so we prefer not distributing it due to the additional restrictions it impose. You may customize the build recipee of the Docker images to include support for it if you need to.

And please respect the purpose of github issues: "IMPORTANT: Do NOT use GitHub to post any questions or support requests!
They will be closed immediately and ignored."
