### ISSUE TITLE
bag_template.xml fix

### ISSUE THREAD

**Issue by ericgyounkin** [OSGeo/gdal#3605]
Using conda installed GDAL 3.2.1
issue related to https://github.com/OSGeo/gdal/commit/1d2e7bc8fcde059de853335fee390479d457be06

I originally posted on the osgeo lists about the bag_template having the x/y switched.  See https://lists.osgeo.org/pipermail/gdal-dev/2021-March/053711.html for more information.

We've been looking at this more, and found some interesting things.  First, using the original bag_template (without switching the x/y) in GDAL 2.4 works.  That would be using the MEM driver, and then creating a copy from MEM as a BAG.  It almost seems like you need a different template in 2.4 vs 3.2.  If this is because something changed under the hood, that is OK, just making sure that this is expected.

Second, we think that the resolution should not be flipped.   With the commit, you have row/width/x as equivalent.  I believe this should be row/width/y and column/height/x.  If that makes sense.  Therefore, I think we should take the commit referenced above, and not switch the resolution.

Thanks,
Eric

**Comment by rouault** [comment]
You're right. My original fix was invalid. The issue came from a code blunder in https://github.com/OSGeo/gdal/commit/1f20a37b315b4287f3c76a3d5d9666710a41ffa2  . The right fix is in https://github.com/OSGeo/gdal/pull/3606 : undo my recent change, and fix the code where the width/height erroneous inversion was done.
The workaround, only valid for with GDAL 3.2.0, .1 and .2,  is to just swith {WIDTH} and {HEIGHT} in the template

**Comment by ericgyounkin** [comment]
That is great, thanks for the quick reply.
