### ISSUE TITLE
Bulleted lists missing from rendered docs

### ISSUE THREAD

**Issue by atlight** [OSGeo/gdal#3658]
https://gdal.org/drivers/vector/dxf.html is missing all bulleted lists. I think they were there before I committed 6dde8310a38de0a9002fe15a919229c4ff2fe78c, but when the page was re-rendered they disappeared.

@rouault do you know who is maintaining this?

(also as a bonus issue, the canonical link tag in the HTML is missing a slash: `<link rel="canonical" href="https://gdal.orgdrivers/vector/dxf.html"/>`)

**Comment by jratike80** [comment]
Seems to be a general behavior that bullets are not rendered from rst into html, see for example https://github.com/OSGeo/gdal/blob/master/gdal/doc/source/drivers/raster/bag.rst and https://gdal.org/drivers/raster/bag.html.

**Comment by jratike80** [comment]
Could there be something wrong in Sphinx or Read the docs? I guess that even this tutorial page does not show bullets as supposed https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html.

**Comment by rouault** [comment]
> I think they were there before I committed [6dde831](https://github.com/OSGeo/gdal/commit/6dde8310a38de0a9002fe15a919229c4ff2fe78c), but when the page was re-rendered they disappeared.

I doubt you should expect bulleted list if you don't prefix with "- "

> the canonical link tag in the HTML is missing a slash

Fixed per 89ae388734c1046cb0f1d51819ba4e78e4ae1f79

**Comment by atlight** [comment]
The `<ul>`s are still in the page source. I think @jratike80 is right, something is wrong with the Sphinx styling.

**Comment by rouault** [comment]
> The `<ul>`s are still in the page source. I think @jratike80 is right, something is wrong with the Sphinx styling.

ah sorry I missed what you mean. I now see the issue. So the issue is some version of the sofware stack used by the Azure pipeline job at https://github.com/OSGeo/gdal/blob/master/gdal/doc/.azure-pipelines.yml . I don't have that issue locally since my versions are a bit older. The Azure pipeline job strongly rely on the osgeo/proj-docs Docker image ( https://github.com/OSGeo/PROJ/blob/master/docs/docbuild/Dockerfile ) that is now re-created and pushed to Docker hub at each change in OSGeo/PROJ github repository.
I'm trying to spot which version bump caused the issue which is the use of <section id=""> (not working) vs <div class="section"> (working)

**Comment by atlight** [comment]
It works! Thanks @rouault and @jratike80 for making the docs readable again 😄
