### ISSUE TITLE
Doxygen main documentation page is empty

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#3689]
The Doxygen main documentation page at https://gdal.org/doxygen/index.html is empty.

![image](https://user-images.githubusercontent.com/16253859/115140615-6cdd7e80-a038-11eb-87ce-d0bf9984c090.png)

The Doxygen main documentation page at https://gdal.org/doxygen/index.html is linked in the GDAL documentation » API page at https://gdal.org/api/ as Full Doxygen output.

**Comment by rouault** [comment]
Yes it is empty, and so what :-) ? It is there mostly so that people can go through the Classes or Files tab. For a more structured view, https://gdal.org/api/ present a bit the different categories. Or perhaps there should be some short word in this doxygen/index.html page to tell people to go to the Classes and Files tab ?

**Comment by agiudiceandrea** [comment]
> Or perhaps there should be some short word in this doxygen/index.html page to tell people to go to the Classes and Files tab ?

Yes, and possibly a serch box too. Something like the QGIS doxigen main page

![image](https://user-images.githubusercontent.com/16253859/115141063-b929be00-a03a-11eb-8401-241a717f81e9.png)
