### ISSUE TITLE
Incorrect mapping of mapinfo point symbols to ogr-sym ids

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#3826]
The current mapping of mapinfo marker symbol number to ogr style id used at https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/mitab/mitab_feature.cpp#L8925 appears incorrect.

The screenshot below shows a rendering in MapInfo (10.5) with the labels showing the "field1" values:

![image](https://user-images.githubusercontent.com/1829991/117595625-abbcab00-b184-11eb-9a2b-73e034e0a44c.png)

Querying the tab gives this output:

```
OGRFeature(marker_styles):2
  Field1 (String) = 2
  Style = SYMBOL(a:0,c:#5050ff,s:36pt,id:"mapinfo-sym-32,ogr-sym-6")
  POINT (-1.337792 0.688963)

OGRFeature(marker_styles):3
  Field1 (String) = 3
  Style = SYMBOL(a:45,c:#ff5820,s:36pt,id:"mapinfo-sym-33,ogr-sym-6")
  POINT (-1.13378 0.698997)

...
````

So feature 2 (with mapinfo symbol number 32), which is shown in mapinfo as a square is being mapped to "ogr-sym-6: triangle (not filled)". The rest of the mappings show similar errors, and the results are all over the place.

Here's how the layer renders in QGIS when using the ogr-sym identifiers and rendering as per the illustration on https://gdal.org/user/ogr_feature_style.html:

![image](https://user-images.githubusercontent.com/1829991/117595857-41f0d100-b185-11eb-87f4-0a1b5971bc28.png)

I'm happy to fix this mapping, but I'm unsure if there's any historical context I'm missing here or if the mapping has been incorrect ever since it was first introduced in 2000...

**Comment by rouault** [comment]
So this was introduced in 4284c5cc851 in 2000 by Stéphane Villeneuve. I've no idea how we could reach him nowadays. I see @drons tweaked a few things in styling recently. Maybe he could comment if he noticed issue on the symbol side ? Otherwise @nyalldawson just go ahead.

**Comment by drons** [comment]
Hi!

Function of symbol translation  from MapInfo to OGR  is not most accurate.

I found ancient documentation in my chest (~2001). [MID_MIF_mifinterchange_file.pdf](https://github.com/OSGeo/gdal/files/6454271/MID_MIF_mifinterchange_file.pdf)

And it looks like the interpretation of symbols has not changed since then. It only expanded a little. 

But, page 690 says:
> The standard set of symbols includes symbols 32
through 67, inclusive, but the user can customize the symbol set by using the Symbol
application.

May be Stéphane Villeneuve made an implementation for some custom symbol table.

P.S. I'm looking first for "mapinfo-sym-X" in my applications, "ogr-sym-X" next time only.
The symbol table from MapInfo is richer.

**Comment by nyalldawson** [comment]
> I found ancient documentation in my chest (~2001). MID_MIF_mifinterchange_file.pdf

Thanks -- page 18 clearly shows that the current map is incorrect. I'll fix.
