### ISSUE TITLE
Reading NITF with GDALINFO and problem in RPC content / JSON output

### ISSUE THREAD

**Issue by Overesch** [OSGeo/gdal#408]
Hello,
I'm trying to read a NITF file that contains RPC Information. I call
gdalinfo -json -mm -hist -nogcp -nomd -norat -noct -nofl "filepath"

Because there are some problems with RPC Information the line
"RPC Extension not Populated!"
is printed to the output.
After that the metadata of the file is printed as a correct JSON string.

The problem is that I'm not able to parse the output of gdalinfo correctly as a JSON object.
Is there an option to avoid this warning, so I can get a correct JSON output?

Thank you
Markus Overesch

**Comment by rouault** [comment]
This error message is outputed on the standard error stream, and not the standard output stream, so that shouldn't interfere with the JSON content if you just keep the standard output.
Alternativey you can use the GDALInfo() function to directly get a string: http://gdal.org/gdal__utils_8h.html#a39aaaa537474fead1ef4575e61e9b96d
