### ISSUE TITLE
Deprecated script is still documented as functioning

### ISSUE THREAD

**Issue by adriantre** [OSGeo/gdal#4128]
I found `gdalcompare.py` from the [docs](https://github.com/OSGeo/gdal/blob/master/gdal/doc/source/programs/gdalcompare.rst). The script itself [says it is deprecated](https://github.com/OSGeo/gdal/blob/aead0f03707d3717331987cd02f2d0a74ffdafd2/gdal/swig/python/gdal-utils/scripts/gdalcompare.py), but not which method it was deprecated in favour of. 

Calling the script also yields
`ModuleNotFoundError: No module named 'osgeo_utils'`

I suggest updating the docs to inform how to perform raster comparison. I would create a PR, but I simply don't know where this functionality lives.

Homebrew gdal 3.3.1

Edit: Typo

**Comment by rouault** [comment]
CC @idanmiara  The script isn't deprecated, right?

**Comment by idanmiara** [comment]
> CC @idanmiara The script isn't deprecated, right?

I don't think it is deprecated.

IIRC we put this depreciation warning on all the scripts as we presented a better way to call them. 

Let me ponder on this once again and I'll also look into the issue that @adriantre presented.

**Comment by idanmiara** [comment]
@adriantre I've tried to run gdalcompare with gdal 3.3.1 on win64, it does work without any issues.
I don't have a Mac, so I cannot try your distro, could you please check that you have a module named `osgeo_utils` in your `site-packages` ? It's supposed to be installed with `gdal`.

If you don't - please point out how you installed it so somebody with a Mac can try it out.
In the meantime - 
try to run `python -m osgeo_utils.gdalcompare file1 file2` or
please try to `pip install gdal-utils` and see if the issue is resolved (this way you can upgrade `osgeo_utils` to the latest version without upgrading gdal itself).

Regarding the deprecation warning - we put it there so that people who import it as a module by adding the script dir to the python path would see that there is a much more strait forward way for doing so, by importing `osgeo_utils.gdalcompare`. and we might drop this option to import it this way in the future.

This deprecation warning does not show for me when running the script itself.

**Comment by adriantre** [comment]
I see now that I had gdal python bindings version 3.0.4 in my environment. Updating it to 3.3.1 the `osgeo_utils.gdalcompare` works, and finds `osgeo_utils`.

Is `osgeo_utils.gdalcompare` documented somewhere? How about a reference to it in the above-mentioned docs?

The reason I'm working on this is because `rasterio.write` and `gdal.translate` yields different files on bit-level. This is a whole other issue, though.

**Comment by idanmiara** [comment]
> Is `osgeo_utils.gdalcompare` documented somewhere? How about a reference to it in the above-mentioned docs?
> 

https://github.com/OSGeo/gdal/pull/4132
