### ISSUE TITLE
PROJ error when reprojecting layer returns with zero exit code. 

### ISSUE THREAD

**Issue by spolloni** [OSGeo/gdal#4464]
## Expected behavior and actual behavior.

I've encountered a situation where reprojecting a layer raises a PROJ Error but the exit code is zero nonetheless. My expectation was that any occurrence of `ERROR 1: ...` should result in non-zero exit codes. Is this not the case?

I should note that this error is strictly tied to using version PROJ 8.0.0. Updating to 8.0.1 fixes the error. Still, I am flagging this as a potential misbehavior regarding exit codes. 

## Steps to reproduce the problem.

```{bash}
docker run ghcr.io/pdal/pdal:sha-3714fdd9 /bin/bash -c "
	echo '{
	    \"type\": \"FeatureCollection\",
	    \"name\": \"test\",
	    \"features\":
	    [
	        {
	            \"type\": \"Feature\",
	            \"properties\":{},
	            \"geometry\":{
	                \"type\": \"Polygon\",
	                \"coordinates\":[[
	                	[434916.52,4423542.54],
	                	[434916.52,4425800.00],
	                	[435499.99,4425800.00],
	                	[435499.99,4423542.54],
	                	[434916.52,4423542.54]
	                ]]
	            }
	        }
	    ]
	}' > test.geojson \
	&& ogr2ogr _test.geojson test.geojson -t_srs EPSG:4326 -s_srs EPSG:26915 \
	&& echo exit code: $?
"
```

Output:
```
ERROR 1: PROJ: Unrecognized horizontal grid format
exit code: 0
```

## Operating system

This image runs on `Debian GNU/Linux 10 (buster)`

## GDAL version and provenance

GDAL 3.2.2, `libgdal` conda installed with `-c conda-forge`

**Comment by rouault** [comment]
This is a very weird issue.  I don't have a definitive answer to that. Logging into the Docker image and looking at PROJ traces and with gdb, it seems that PROJ at some point does a fopen("/opt/conda/envs/pdal/share/proj") (a directory) and believes that the opening of the file /opt/conda/envs/pdal/share/proj/us_noaa_mohpgn.tif has succeeded, and afterwards there's a failure when reading from that non-existent file (actually reading from a directory file). The error message you get about Unrecognized horizontal grid format is something @hobu had recently, so I'm wondering if he might not have hit that issue. 

My hypothesis would be that around https://github.com/OSGeo/PROJ/blob/master/src/filemanager.cpp#L1500 std::string(proj_lib_name) + DIR_CHAR + name would result in a std::string with a NUL byte in the middle of it, perhaps due to proj_lib_name which equals to the #define PROJ_LIB passed at build time would contain one (but that still doesn't make sense as it should be eliminated at std::string() construction), and when doing the c_str(), one only sees the directory part of the full filename.). That part of the code hasn't changed  since PROJ 8.0.0, and I can't reproduce such issue on a local autoconf build. I see that Conda PROJ builds have changed from autoconf to cmake after 8.0, so maybe that could explain the difference ?

As far as why errors aren't propagated to GDAL, the reason is that there are multiple transformation paths possible for NAD83 to EPSG:4326 and one doesn't succeed, PROJ has a fallback logic to other transformation paths, hence this is non fatal from GDAL point of view.

So all in all, GDAL is fine regarding that and I'm not sure what happened in the Conda PROJ 8.0.0 build

**Comment by spolloni** [comment]
@rouault thanks for the detailed investigation!
