### ISSUE TITLE
For GRIB2, generate an OGRSpatialReference with proj4 +lon_wrap

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#4524]
## Expected behavior and actual behavior.

GRIB2s are supposed to have their longitudes in [0,360]
This is (AFAIK) not possible with WKT
GDAL currently generates a normal `OGRSpatialReference` object which does not take this into account
Ideally, it should generate an object with the proj4 `lon_wrap` extension

## Steps to reproduce the problem.

```
gdallocationinfo -wgs84 /vsis3/noaa-gfs-bdp-pds/gfs.20210918/06/atmos/gfs.t06z.pgrb2.0p25.f000 -60.874 14.463
```
(if you are reading this at a later date, replace the date string)

## Operating system

All

## GDAL version and provenance

3.4.0-git

**Comment by rouault** [comment]
> Ideally, it should generate an object with the proj4 `lon_wrap` extension

I wouldn't say it's ideal, as lon_wrap is a non-standard hack that doesn't fit into the ISO 19111 model.

If the issue is only with gdallocationinfo -wgs84, some logic could be added into it to adjust the longitudes
If it is more general, then the GRIB driver could potentially be modified to cut the raster into two parts, switch them and have something that fits (or is very close to) the [-180,180] range. That behavior should probably be controlled by an open option.

**Comment by mmomtchev** [comment]
This would be far more complex, but it will also solve the problem of translating to GeoTIFF - one would expect that once a layer is converted to GeoTIFF it becomes a normal raster with the greenwich meridian in the middle
Currently, if a GRIBv2 band is translated to GeoTIFF, it becomes a very weird 0-360 band that must be converted with gdalwarp:
<https://gis.stackexchange.com/questions/37790/reprojecting-raster-from-0-360-to-180-180-with-cutting-180-meridian-using-gdalw>
