### ISSUE TITLE
OAPIF: add a INITIAL_REQUEST_PAGE_SIZE open option

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4556]
to override the general PAGE_SIZE open option which override the server default setting.
The intent is to be able to have a quick way of establishing the layer schema.
See https://lists.osgeo.org/pipermail/gdal-dev/2021-September/054711.html for related thread

**Comment by hebersgit** [comment]
This would speed-up OAPIF-layers a lot. For now, in `OGROAPIFLayer::EstablishFeatureDefn()`, a result-set of size "PAGE_SIZE" is requested from the server and parsed from JSON, only to retrieve the _first_ feature and getting the datatype of it's _id_. A lot of time is burned for this.
I think for this request in `OGROAPIFLayer::EstablishFeatureDefn()`, one could even always work with limit=1, but an INITIAL_REQUEST_PAGE_SIZE would be a good alternative.

**Comment by jratike80** [comment]
An excerpt from MapServer logs show also that the big page_size, that has an advantage when fetching the data, has a drawback: one full page of data (here 10000 features) is spend just for judging if the schema from the service is trustworthy. 

```
 AH01215: GDAL: GDALOpen(OAPIF:https://beta-paikkatieto.maanmittauslaitos.fi/inspire-buildings/features/v1/, this=05457918) succeeds as OAPIF.\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: HTTP: Fetch(https://beta-paikkatieto.maanmittauslaitos.fi/inspire-buildings/features/v1/collections/building/schema)\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: OAPIF: Using JSON schema\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: HTTP: Fetch(https://beta-paikkatieto.maanmittauslaitos.fi/inspire-buildings/features/v1/collections/building/items?f=json&limit=10000)\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: GeoJSON: First pass: 19.15 %\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: GeoJSON: First pass: 38.30 %\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: GeoJSON: First pass: 57.45 %\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: GeoJSON: First pass: 76.60 %\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: GeoJSON: First pass: 95.74 %\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: GeoJSON: First pass: 100.00 %\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: VRT: Source feature definition is identical to VRT feature definition. Use optimized path\r: C:/ms4w/Apache/cgi-bin/mapserv.exe
 AH01215: HTTP: Fetch(https://beta-paikkatieto.maanmittauslaitos.fi/inspire-buildings/features/v1/collections/building/items?f=json&limit=10000&bbox=393430.774005548214,6675282.52235975303,394950.815519060823,6676067.64890727215&bbox-crs=http://www.opengis.net/def/crs/EPSG/0/3067&crs=http://www.opengis.net/def/crs/EPSG/0/3067)\r: C:/ms4w/Apache/cgi-bin/mapserv.exe

```

**Comment by jratike80** [comment]
I can read mostly comments from the code but I do not believe that only the data type of "id" is checked, and that only the first line is scanned.

I think that scanning just one line is not enough because some servers do not present null properties in JSON as `"property_1": null` but they save space and don't write the property at all. In that case the only certain way would be to read the JSON totally because some attribute may appear for first time in the last feature. But scanning some 10-20 features might be a good and fast compromise.

The driver is scanning a sample from data also when the API has a "describedby" link and missing properties are added to the advertised schema if they are met. This feels a bit like a poorly configured server but "describedby" is not so strictly described in OGCFeat core. Or maybe it comes from OpenAPI. The driver has an open option `IGNORE_SCHEMA` and a new option `TRUST_SCHEMA` would probably give a negligible speedup.

What I wonder is if the name `IGNORE_SCHEMA` should be changed into something else, or if it will be enhanced when the "Schemas" extension https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/schemas is approved. Those schemas are different than the one that "describedby" gives.
