### ISSUE TITLE
GDALDataset::MarkSuppressOnClose() won't delete auxiliary files

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#4791]
When using the ENVI driver, creating the main dataset file (for instance "foo.bip") will also create auxiliary files ("foo.hdr", and even for some custom metadata "foo.aux.xml")
Using GDALDriver::Delete("foo.bip") will remove all files, as expected
However, just using GDALDataset::MarkSuppressOnClose() and let the files be deleted automatically will only delete the main file ("foo.hdr" and "foo.aux.xml" will remain after closing, while "foo.bil" is deleted).
Is it expected behaviour ?

**Comment by rouault** [comment]
> Is it expected behaviour ?

probably not. That said this method was initially designed to be used internally for a few cases where auxiliary files weren't found. But it should be possible to use the GDALDriver::Delete() method

**Comment by rouault** [comment]
Hum, turns out that this is more complicated than what I thought and that cleaning auxiliary files would require going in every driver (which I didn't do... have already done this for the FlushCache(bool bAtClosing) and got overwhelmed by that) since the generic code in GDALDataset destructor has no easy way  to get the file list. So I just did in ENVI and PAM
