### ISSUE TITLE
FlatGeobuf; CRS WKT risk of wrong encoding

### ISSUE THREAD

**Issue by bjornharrtell** [OSGeo/gdal#5060]
I believe https://github.com/OSGeo/gdal/blob/7b5075b67201a1f6945b9e80d83364addf390184/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp#L353 can result in a string with some system or source specific encoding.

(All strings in FlatGeobuf are mandated to be UTF-8 and other encodings can cause issues)

**Comment by rouault** [comment]
if the CRS wasn't instantiated with something like proj_create(, ... "EPSG:XXXX"), but from a user-provided string, then PROJ will return in whatever encoding the user provided the string. Perhaps the issue is due to QGIS saving a .prj file with a non-UTF8 encoding ?
You could possibly use CPLIsUTF8() to check the string is UTF8 and then remove any char > 127 (we might have a generic CPLForceUTF8() function to do that)

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/5062
