### ISSUE TITLE
WCS: unusual metadata in SUBDATASETS domain and missing SUBDATASET_x_NAME

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#515]
@ajolma

```gdalinfo WCS:https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows?coverage=ortotesti__ortokuva```
reports

```
Subdatasets:
  SUBDATASET_1_NAME=WCS:https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows?service=WCS&version=2.0.1&coverageId=ortotesti__ortokuva
  SUBDATASET_1_WGS84BBOX=15.5706177104992,59.5209776951808,33.1881061199753,70.1359269604917
  SUBDATASET_1_BBOX(minX,minY,maxX,maxY)=61254.6580619824,6623749.72946716,735433.573091962,7782000,http://www.opengis.net/def/crs/EPSG/0/EPSG:3067
  SUBDATASET_1_TYPE=RectifiedGridCoverage
  DOMAIN=E,N
  DIMENSION_0_AXIS=E
  DIMENSION_0_UOM=m
  DIMENSION_0_INTERVAL=61254.6580619824,735433.573091962
  DIMENSION_1_AXIS=N
  DIMENSION_1_UOM=m
  DIMENSION_1_INTERVAL=6623749.72946716,7782000
  DIMENSION_2_AXIS=time
  DIMENSION_2_UOM=s
  FIELD_1_NAME=GRAY_INDEX
  FIELD_1_DESCR=GRAY_INDEX
  FIELD_1_INTERVAL=0 255
```

First issue is the lack of SUBDATASET_1_DESC metadata item
Second issue is the presence of all the other metadata items except SUBDATASET_1_NAME. They should likely be in the default metadata domain or in a dedicated one, but SUBDATASETS metadata domain should only contains SUBDATASET_x_DESC and SUBDATASET_x_NAME

**Comment by ajolma** [comment]
When I run that gdalinfo it dumps core because the CoverageDescription uses EnvelopeWithTimePeriod, which is unexpected (maybe not a bug but dumping core is a bug). Fixing that (I'll do a PR later), it seems to me that the ortokuva is the subdataset_1, reporting its metadata under Subdatasets: is probably my failed attempt to work with the metadata system. I think a dedicated domain should be added.

Probably the DESC item is  missing because there is no obvious contents for it.

`gdalinfo WCS:https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows`

Reports all subdatasets with NAME, WGS84BBOX, BBOX, and TYPE metadata. Perhaps the last three should be in DESC.
