### ISSUE TITLE
DODS/OPeNDAP Driver Removal... Please don't

### ISSUE THREAD

**Issue by vtdrfuka** [OSGeo/gdal#5173]
Just opening the ticket to request that the DODS driver remains in the mix. We have dependencies on this driver in several CRAN packages and python libraries. 

DODS/OPeNDAP
Driver short name: DODS

Driver is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one. If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it). T

**Comment by rouault** [comment]
Which driver do you use: the raster one or the vector one ?

One issue we have is that our unit tests (https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_dods.py and https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/dods.py) don't work anymore due to test servers used initially not being available, and we (at least I) have no idea of how to test that driver and if it still works (the base assumption is that untested code is broken code). Are there public DODS servers somewhere ?
Do you or someone else would volunteer to take over maintenance of those drivers ? At least bringing back the unit tests.
Another annoyance of the raster DOS driver is that it takes directly a URL, which conflicts with the generic HTTP driver. A "DODS:" prefix should be required for dataset names.

**Comment by rouault** [comment]
Call for action to the mailing list audience: https://lists.osgeo.org/pipermail/gdal-dev/2022-January/thread.html#55348

**Comment by bradh** [comment]
Could  the code be moved to the CRAN driver? If it is the only known user, seems possible.

**Comment by rouault** [comment]
@vtdrfuka Please provide feedback regarding the questions posted in this ticket

**Comment by mdsumner** [comment]
@vtdrfuka - please share you example sources, perhaps it's better done with NetCDF itself (I haven't used DODS via GDAL for a long time, but NetCDF generally works with URLs in GDAL - and often I disable the DODS driver, or use /vsicurl or NetCDF: to avoid conflation -  perhaps we can find alternatives along those lines for you)

**Comment by rouault** [comment]
@vtdrfuka can you provide some feedback ? Otherwise the driver will be removed as planned

**Comment by rouault** [comment]
Pull request removing the DODS drivers: https://github.com/OSGeo/gdal/pull/5666

**Comment by mdsumner** [comment]
thanks @rouault !

**Comment by rouault** [comment]
Why reopening ?

**Comment by nyalldawson** [comment]
Hmm, I can't recall doing this -- must have been an errant click!
