### ISSUE TITLE
Autotools configure script doesn't honour --with-sysroot directive when locating external driver libraries

### ISSUE THREAD

**Issue by RichardLangFromNZ** [OSGeo/gdal#531]
Unless a specific location for an optional driver/package/library has been specified, configure script searches from the build platform root, even when a --with-sysroot directive has been supplied, and on finding it potentially drags build platform include paths into the build configuration.

Cross-compiling with a custom sysroot, I'm not only having to specify the sysroot with a ```--with-sysroot=/foo/bar``` directive, but having to repeat myself on every optional package inclusion directive ```--with-sqlite3=/foo/bar```

**Comment by metux** [comment]
Yore're right: the configure.ac is in no way capable of doing clean cross compile.
It has almost a hundred places of harcoded includes to the host (grep for /usr), which need to be refactored for sysroot support.
In fact, those places should go the standard and clean way - pkg-config - instead of hand crafted guessing. (I've fixed that for a few cases, but lots of more missing yet)

**Comment by rouault** [comment]
Improvements to autotools build systems will no longer be considered now that we are developing a cmake build system that will eventually replace it
