### ISSUE TITLE
Is gdal version in `swig/python/setup.py` correct?

### ISSUE THREAD

**Issue by maphew** [OSGeo/gdal#5475]
https://github.com/OSGeo/gdal/blob/aac77f0465551112e29b7c21201bbb5a4e3b4bc3/swig/python/setup.py#L10

Is this meant to match gdal version? (currently 3.4.0)

**Comment by rouault** [comment]
That information is only updated / accurate at release time (see https://github.com/OSGeo/gdal/blob/master/HOWTO-RELEASE), and typically lags one version behind in master. Here it lags two versions behind because the 3.4.0 release was created from a branch forked from master (and thus master was last released as 3.3.0). I guess we could update it to '3.5.0dev' but I'm not sure about the implications. You can try a PR with that if you want.

**Comment by maphew** [comment]
Thanks for the pointer to where this fits into the overall release process. I'll think a bit before trying anything.

**Comment by rouault** [comment]
I just went ahead with updating the version numbers to intermediate ones in commit https://github.com/OSGeo/gdal/commit/c91707387325a48b3140996a845f2444f5592db8
