### ISSUE TITLE
Remove GRASS drivers from OSGeo/GDAL repository

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#5667]
They have been moved to https://github.com/OSGeo/gdal-grass.
Documentation pages (doc/source/drivers/raster/grass.rst and doc/source/drivers/vector/grass.rst) should be updated to reflect this. Perhaps the doc pages should just point to the OSGeo/gdal-grass repository, and their content moved to it.

@neteler / @metzm Is any of you able to do this before end of this week in time for 3.5.0 release candidate ? (if not, I may look at that)

**Comment by neteler** [comment]
> Perhaps the doc pages should just point to the OSGeo/gdal-grass repository, and their content moved to it.

The driver documentation is now reachable here:

- https://github.com/OSGeo/gdal-grass/blob/main/docs/grass_raster.md
- https://github.com/OSGeo/gdal-grass/blob/main/docs/grass_vector.md

Do you have any best practice recommendation in other drivers how to point to it? Otherwise I'll modify accordingly.

**Comment by rouault** [comment]
> Do you have any best practice recommendation in other drivers how to point to it?

Probably just use an external link to the new pages
