### ISSUE TITLE
Ogrinfo takes too much RAM memory with KML files

### ISSUE THREAD

**Issue by moicalcob** [OSGeo/gdal#5887]
## Expected behavior and actual behavior.

We're using `ogrinfo` to check remove files types before processing them, and we're facing some issues while working with KML files.
If we try to execute the `ogrinfo` command to check a KML file the process starts taking too much RAM memory, and this issue doesn't appear with other formats. As can be checked in this screenshot, it can takes more than 500MB:

<img width="701" alt="Screenshot 2022-06-07 at 10 52 49" src="https://user-images.githubusercontent.com/56086628/172568192-6d5e64e8-f29a-4c17-87e6-f3c58c047808.png">

As we've been using `ogrinfo` without any problem with multiple file types (CSVs, Geopackages, Shapefiles...) without encountering any issue with the amount of RAM memory required, we believe that there should be an issue with KML files using the command. We've uploaded a KML file to GCS so you can check the behaviour running the command available below.

## Steps to reproduce the problem.

```bash
ogrinfo '/vsicurl/https://storage.googleapis.com/carto-tnt-gcp-local-dev-client-storage/datasets/ac_1uo2qvbk/auth0%7C6294a15fbc3e500068ab24de/c7668aef-4301-494e-b88a-956a76362b1c.kml?GoogleAccessId=dev-env-cloud-storage%40carto-commons.iam.gserviceaccount.com&Expires=1654678292&Signature=upi72lhG1wpmN%2BP%2BPxbSRbcWHqECsdLRfmSDnhPhIwLtCB7zXog8B8OJPNLEEzYhO2GhYrDJ2MROC7AwqWk3ZlBgxKBnGNjxXP4GtUg6o%2F%2BCCvInbP5MVNxCCr%2B8NuMbVZnXCBEBsgb8Tlr%2F6aFbG2vzB1GXue1uG3rD2yy58fLO391zxT9Su9wjPeeHet3NawXgHA2E5b8kdL4mEpPIGyJQpAnBYV33CI1QjTIC65%2F7jF8bKHUjpsPZ6xJ6VPwLnYxo9Gm%2BmLF5tm8%2FRKpkTo3uWP7Akr45oVb%2BlNQBx53bJwEG35h4vKJrCWuoxpy99hAzkeoPc7puYIW5BFLYcQ%3D%3D'
```

## Operating system

* macOS Monterey
* Debian 11

## GDAL version and provenance

GDAL 3.4.3, released 2022/04/22 installed using Brew
GDAL 3.2.2 installed on Debian

**Comment by jratike80** [comment]
One cannot assume that XML file that KML is can be processed as fast as some binary formats like GeoPackage or shapefile. However, it does look like ogrinfo is using less memory if I convert the KML file into another type of XML with
`ogr2ogr -f gml c.gml c7668aef-4301-494e-b88a-956a76362b1c.kml`

It may also be that the other KML driver "KML" is using less memory than LIBKML. If you have both drivers installed you can have a try as well by skipping the LIBKLM driver by setting an environment variable `GDAL_SKIP=LIBKML`.

I think that you should have written a mail to gdal-dev mailing list and ask if the memory usage that you see with KML is normal instead of creating a bug report straight ahead.

**Comment by moicalcob** [comment]
I've tried with both drivers and the results are similar @jratike80. Sorry if I shouldn't have opened an issue for this one, I'll write an email to gdal-dev mailing list just to check if it's an expected behaviour 😓

**Comment by rouault** [comment]
The KML and LIBKML driver needs to parse the whole file in memory due to the structure of KML files. Perhaps that with a great deal of effort, one could write a streaming driver but it would require a huge rewrite effort (and that wouldn't be possible for the LIBKML driver since the underlying library requires to ingest everything)
