### ISSUE TITLE
Error building on mac os: can't map file, errno=22 file '...' for architecture x86_64

### ISSUE THREAD

**Issue by WhiteSte** [OSGeo/gdal#6052]
## Expected behavior and actual behavior.

Hi, I'm trying to build GDAL 3.5.1 on mac os with FileGDB plugin, I'm getting the following error 

```
[ 93%] Built target gcore_mdreader
[ 93%] Linking CXX shared library libgdal.dylib
ld: can't map file, errno=22 file '/Users/steve/Downloads/FileGDB_API_MACOSX15_64gcc8/lib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgdal.31.0.1.dylib] Error 1
make[1]: *** [CMakeFiles/GDAL.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to reproduce the problem.

Build gdal on mac os
## Operating system

Last MAC OS Monterei 12.4

## GDAL version and provenance

The last release 3.5.1

**Comment by rouault** [comment]
I'm afraid we can't do anything about that due to the proprietary nature of the FileGDB SDK. Probably some incompatibility between your MacOS version/architecture and what the SDK delivers.
If you just need read support, then you don't need the FileGDB SDK, and the OpenFileGDB one that is builtin will do the job
If you need write support, use GDAL master where write support has been added in the OpenFileGDB driver.
