### ISSUE TITLE
DOC: Contributing guide - SWIG | python virtualenv | minimize build

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#6094]
https://gist.github.com/snowman2/8fa931fd678cb6f0aca9089617b881fb

- I remember that a specific version of SWIG is needed for GDAL at some point, so I was thinking it would be good to have that documented for contributors. Is it still 3.0.12?
- It is a good idea to use Python virtual environments for development. Having that documented would be good.
- I added the flags for a minimal build by default as it greatly reduces the build time. I think mentioning those in there would be a helpful tip for first time contributors who are developing on a specific part of GDAL and don't need everything.

If you would like to see any of these additions added to CONTRIBUTING.md, just let me know.

**Comment by rouault** [comment]
> * Is it still 3.0.12?

no 4.0.2 currently

> I added the flags for a minimal build by default as it greatly reduces the build time

I would not put it in the default instructions. Perhaps as commented hint, that people must explicitly uncomment, and with some word of caution because there are a number of popular drivers that are optional (geopackage, csv, etc etc). I'm not sure disabling apps is also a good idea. It is so much convenient to be able to gdalinfo etc.
