### ISSUE TITLE
Add ability to explicitly specify desired driver for XLSX files

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#6375]
In some cases it is very handy to have an ability to prepend file path with driver name if file name has non-standard extension to let the GDAL know the desired driver:
```
$ ogrinfo CSV:test.data
INFO: Open of `CSV:test.data'
      using driver `CSV' successful.
1: test (None)
```

For [XLSX](https://gdal.org/drivers/vector/xlsx.html) driver such approach doesn't work.

**Comment by jratike80** [comment]
Or maybe something like `-if` in gdalinfo https://gdal.org/programs/gdalinfo.html#cmdoption-gdalinfo-if.

**Comment by rouault** [comment]
Are there .xlsx files without the .xlsx extension ?

> Or maybe something like `-if` in gdalinfo https://gdal.org/programs/gdalinfo.html#cmdoption-gdalinfo-if.

I know this is confusion, but -if is only about restricting driver selection (if several ones may recognize it), not forcing a driver to open a file when no-one does recognize it

**Comment by drnextgis** [comment]
> Are there XLSX files without the .xlsx extension ?

Imagine a platform where all file stored in a unified way with uuid as filenames and with no extensions. Information about file type might be stored in a different place.

**Comment by jratike80** [comment]
From the user's perspective it might be nice to have a common option for OGR and GDAL that is easy to remember and `-if` for "input format" feels good to me even it has another meaning in gdal_create and perhaps elsewhere. It would be also a bit easier to write scripts when GDAL needs a hint about the format because adding `-if CSV` into the scripts is simple while concatenating `CSV:` with the filename is not as simple.

Does imagination about uuid as a file name lead into a need of forced driver selection also with GDAL?
