### ISSUE TITLE
Error occurred in filegdbtable.cpp at line 1354

### ISSUE THREAD

**Issue by thk686** [OSGeo/gdal#6383]
I see:

ERROR 1: Error occurred in filegdbtable.cpp at line 1354
More than 1000 errors or warnings have been reported. No more will be reported from now.

with the following command: 

ogrmerge.py -overwrite_ds -a_srs epsg:3083 -nln texas_ecosystems -lco GEOMETRY_NAME=geom -lco SCHEMA=texas -lco FID=gid -lco PRECISION=NO -single -field_strategy Intersection -lco FID64=TRUE -lco OVERWRITE=TRUE -lco UNLOGGED=TRUE -lco DIM=2 -skipfailures -o PG:'dbname=keittlab' *.gdb

The *.gdb are downloaded from here: 

https://tpwd.texas.gov/gis/programs/landscape-ecology/by-ecoregion-vector

Very difficult to debug but I thought I'd report it just in case its helpful for someone.

**Comment by rouault** [comment]
Could you spot which file trigger this error ? Downloading all of them is quite tedious... I tried with AZ_NM_Mountains_L3C23_EMST.gdb.zip, CentralGreatPlains_L3C27_EMST.gdb.zip, CrossTimbers_L3C29_EMST.gdb.zip and ChihuahuanDesert_L3C24_EMST.gdb.zip and didn't hit any issue
For example run "ogr2ogr tmp.gpkg in.gdb" on each .gdb and see if the error is emitted (the error is very much likely reproducable with any process that read the .gdb file entirely, so ogr2ogr should do)
It also seems you're not using the latest stable GDAL release (perhaps 3.1.x or 3.2.x ?), although I'm not sure the issue would be fixed in a more recent version. It might be that one of the file is corrupted/truncated

**Comment by thk686** [comment]
Yes, did not think to check the download -- it was corrupted. (Now I have an issue with a feature being interpreted at a MULTISURFACE rather than a MULTIPOLYGON and ogrmere.py does not support the -nlt option.)
