### ISSUE TITLE
Enhancement request: VSIFAdviseRead

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#6456]
With the recent addition of #6438, multi-threaded decoding skips the VSIFReadMultiRangeL which causes consecutive ranges in a COG file to be fetched one by one instead of in a single chunk. I think it could make sense to expose a `VSIFAdviseRead(int nRanges, int *offsets, int *sizes)` function who's implementation is by default a no-op, but that could be implemented by a caching VSI backend to emit a VSIFReadMultiRangeL with much less actual read requests (due to consecutive range merging) and use the resulting cached chunks for the subsequent PReads emitted by gtiff in MultiThreadedRead.

Another option to reduce the number of read requests in MultiThreadedRead would be to have 2 threadpool jobqueues, one for the merged consecutive ranges, and one for the actual decoding, but that seems more complicated to implement (it would however reduce the number of requests also for non-caching vsi backends, namely vsicurl)

thoughts?

**Comment by rouault** [comment]
- I imagine the intent is that AdviseRead() implementations would be asynchronous ? ie return immediately and do the actual download in background thread(s).  In that case, there's no obvious way to communicate with it if the RasterIO() operation has failed: currently as soon as one decoding task/thread fails, it sets a global flag so that all other queued jobs are aborted. Perhaps AdviseRead() should return an opaque non-null void* handle, and have a CancelAdviseRead(void* handle) method ? hum, but if it is conditionally called, that might make things complicated. Or rename AdviseRead() as StartAdviseRead() and have a StopAdviseRead() always called before MultiThreadedRead() returns (which might be needed anyway in the successful code path to have an opportunity to release cached buffers)

- Let's imagine that the RasterIO() request reads several giga pixels, would it issue a single AdviseRead() with all the needed ranges ? Currently the ReadMultiRange() in the non-multi-threaded code path limits itself to requesting GDAL_MAX_RAW_BLOCK_CACHE_SIZE=10485760 bytes by default.

- related to the above, a AdviseRead() implementation should be careful not to merge too aggressively: if reading the whole file in a single time, the union of all ranges will be the whole file, so decoding threads could be waiting for the whole file to be cached if the AdvisRead() implementation merge the union of all ranges in a single request...

- what you mention about the alternative of MultiThreadedRead having 2 threadpool jobqueues applies to AdviseRead() + PRead() implementation. But that's perhaps cleaner if that's done at the VSIVirtualHandle level as a hidden implementation detail, that could potentially be used by other drivers.

- note: I'm aware of a user which exposes "virtual" GeoTIFF files as HTTP accessible resources. That is its underlying storage is something different from GeoTIFF, but when you request /foo.tif, a service exposes the raster as a GeoTIFF file (basically something similar to https://github.com/rouault/cogserver). In that implementation, performance is best reached if range requests exactly match [tileoffset[i], tileoffset[i]+tilebytecount[i] [, so the GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=NO setting (currently used by VSICurlHandle::ReadMultiRange()) should also be honoured by an enhanced MultiThreadedRead() that would implement multi range strategy by default.

**Comment by tbonfort** [comment]
Thanks for the comments @rouault

The aim of this enhancement is only to give a bit more context to a vsifile implementation about the context of the upcoming requests, in order to _maybe_ be able to optimize the number of requests to be made. A VSIHandle must  continue to return correct results to PRead/Read/ReadMultiRange whether or not AdviseRead was called.

> I imagine the intent is that AdviseRead() implementations would be asynchronous ?

Wether it is asynchronous or not is left up for decision by each implementer, but in the majority of cases I believe it would lead to asynchronously downloading the requested parts, yes. However an advise-read implementation may also just cache the ranges to know that when an actual pread request comes in it would be more efficient to emit a single GET request that also spans the adjacent tile ranges.

I don't have a specific need to have a CancelAdviseRead or Start/Stop methods. My underlying intent is to use this backed by a vsi implementation that holds its lru cache of file blocks, so in the worst case scenario where RasterIO fails the side-effect would only be that some superfluous reads have happened in the background.

> Let's imagine that the RasterIO() request reads several giga pixels (...) a AdviseRead() implementation should be careful not to merge too aggressively

These are valid points that from what I understand also apply to the current implementation of VSIReadMultiRange, correct? It would therefore be up to the AdviseRead specific implementation to decide how to handle such requests.

> what you mention about the alternative of MultiThreadedRead having 2 threadpool jobqueues applies to AdviseRead() + PRead() implementation. But that's perhaps cleaner if that's done at the VSIVirtualHandle level as a hidden implementation detail, that could potentially be used by other drivers.

I don't understand what you mean here, I don't see how that could be done at the VSIVirtualHandle level (in the context of a vsifile backed by a lru cache). My idea of 2 queues would be limited to the gtiff driver: a first level that downloads/preads one range of consecutive tiles per line of tiles, and at the end of the download would split the response into the ranges of each tile and send each tile to the 2nd queue.

> ... GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=NO ...

AdviseRead should probably be given unmerged ranges, and it would be left up to each implementation to apply the actual merging if that makes sense

**Comment by tbonfort** [comment]
To clarify my previous response, my 2-queue suggestion relies on PRead (inside the first queue only), but does not require or use AdviseRead
