### ISSUE TITLE
Adding OVERVIEW_COUNT creation option to the cog driver 

### ISSUE THREAD

**Issue by IdanAviv89** [OSGeo/gdal#6566]
When using custom tiling scheme, having the ability to control the number of overviews created using the OVERVIEW_LEVEL creation option (continuing the following [discussion](https://github.com/OSGeo/gdal/issues/6555)).

**Comment by rouault** [comment]
I actually meant to repurpose ZOOM_LEVEL

**Comment by rouault** [comment]
hum actually not, you may want to generate a ZOOM_LEVEL=15 raster with only OVERVIEW_COUNT=3 overviews. Must be separate options

**Comment by IdanAviv89** [comment]
what does it mean having zoom_level=15 in that case ?

**Comment by rouault** [comment]
ZOOM_LEVEL only applies to non-CUSTOM tiling schemes

**Comment by jratike80** [comment]
So which overviews these are? The three first ones as if `gdaladdo 2 4 8` was used? What if we meet a user who wants overviews `4 8 32`? I think that skipping the "2" overview could make sense sometimes because it would save nearly 25% of disk space. Not so sure about the need to skip the other levels but maybe I just don't understand the fundamentals of cloud environments.

**Comment by rouault** [comment]
> So which overviews these are? The three first ones as if `gdaladdo 2 4 8` was used?

in  PR #6567  yes

> What if we meet a user who wants overviews 4 8 32? 

Create a source geotiff, run custom gdaladdo and convert it to COG
