### ISSUE TITLE
OGR GML: GeometryType 0 instead of 7 on mixed Geometries

### ISSUE THREAD

**Issue by kraftto** [OSGeo/gdal#6616]
## Expected behavior and actual behavior.

On reading GML files with layers with mixed geometries, the resulting GeometryType in the GFS file should be 0 (any geometry type) instead of 7 (geometrycollection). This would allow opening such files with QGIS. 

## Steps to reproduce the problem.

ogrinfo /vsizip/[LRP_I.zip](https://github.com/OSGeo/gdal/files/9937913/LRP_I.zip)/xplan.gml

## Operating system

Windows 10 64bit

## GDAL version and provenance

GDAL 3.5.3 from osgeo4w

**Comment by jratike80** [comment]
At least this feature is a geometry collection.

```
OGRFeature(SO_SchutzgebietWasserrecht):776
  gml_id (String) = Gml_d6b8e123-f593-4f30-b01e-eb76b738a776
  rechtsstand (Integer) = 2000
  rechtscharakter (Integer) = 2000
  flaechenschluss (Integer(Boolean)) = 0
  artDerFestlegung (Integer) = 1000
  zone (Integer) = 1100
  GEOMETRYCOLLECTION (POINT (497732.481 6074028.922),POINT (462007.558 6096887.14),POINT (514082.024 6023123.739),POINT (457650.466 6085331.151),POINT (506956.259 6036056.193),POINT (465386.194 6061745.021))

```

**Comment by kraftto** [comment]
>but not a mixture of them but the data seems to be like that and "position" is always one MultiPoint, MultiLinestring, or MultiSurface
That's true, the geometry cannot be mixed within one particular feature, but the individual features of feature class can have different geometries. So would GeometryType 0/any geometry be wrong then, definition-wise?

**Comment by jratike80** [comment]
I think it would not not be wrong but XML is complicated sometimes. See the attached simple GML "mixed.gml". Ogrinfo reports that the geometry type is `Geometry: Unknown (any)` . So it seems that the title of your bug report is not quite right because the geometry type of a GML layer with mixed geometries is not always reported as geometry collection.

The GML driver https://gdal.org/drivers/vector/gml.html does not require XML schema but it reads the data and tries to build the schema:

> If the .xsd file is absent or OGR is not able to parse it, the driver attempts to automatically discover the feature classes and their associated properties by scanning the file and looking for “known” gml objects in the gml namespace to determine the organization.

I guess that GDAL just finds that the "position" contains a list of GML geometries, but without a complete XML schema it can't know that if the first geometry is point then all the other geometries must be points, and the same applies to linestrings and polygons. Maybe the xplan data would require some special rules like there are for some other XML schemas https://gdal.org/drivers/vector/gml.html#particular-gml-application-schemas. But it seems that the right thing to do is to use the GMLAS driver that resolves the schema.

```
ogrinfo gmlas:LRP_I.gml -oo REMOVE_UNUSED_LAYERS=YES so_schutzgebietwasserrecht

INFO: Open of `gmlas:LRP_I.gml'
      using driver `GMLAS' successful.

Layer name: so_schutzgebietwasserrecht
Geometry: Unknown (any)
Feature Count: 9
Extent: (455960.403000, 6022563.151000) - (515150.221000, 6099064.643000)
Layer SRS WKT:
PROJCRS["ETRS89 / UTM zone 32N",
...

```
[mixed.zip](https://github.com/OSGeo/gdal/files/9939499/mixed.zip)

**Comment by kraftto** [comment]
Thanks @rouault - looking forward to testing the fix - and @jratike80. We're also testing the GMLAS driver, but in terms of just having a quick look at a GML file, it's a bit too sophisticated.

**Comment by pathmapper** [comment]
Thanks @rouault @jratike80, just built with the fix and confirmed it fixes the issue here and also https://github.com/qgis/QGIS/issues/50373. 

For the created GFS there's no element `<GeometryType>0</GeometryType>` for layers with `Geometry: Unknown (any)`, it seems like it's optional.
