### ISSUE TITLE
GDAL/OGR VSICURL does not offer gzip compression​

### ISSUE THREAD

**Issue by sgofferj** [OSGeo/gdal#6686]
### Actual behavior
I am trying to open a GeoJSON from the Finnish Traffic Authority via https from QGIS and mapserver.
https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=false&situationType=TRAFFIC_ANNOUNCEMENT
The FTA has configured their servers so, that the client *must* accept gzip compression, otherwise, the request will be rejected with `Not Acceptable. Use of gzip compression is required with Accept-Encoding: gzip header`
Both QGIS and mapserver use the GDAL/OGR VSICURL virtual file system for accessing remote files via http/https.
NB: This is about VSICURL when the GDAL/OGR libraries are used by another piece of software, not about command line use of GDAL/OGR tools.

### Expected behavior
I would expect the VSICURL module to offer gzip compression to the server by default, because most servers support it and especially with text-based file formats, gzip compression saves quite a bit of traffic.

## Steps to reproduce the problem.
Access any remote file on a server which requires gzip compression through OGR/GDAL libraries (not GDAL cli tools).

## Operating system
Ubuntu 22.04 LTS

## GDAL version and provenance
GDAL 3.4.1, released 2021/12/27

**Comment by rouault** [comment]
This cannot be implemented for your use case with /vsicurl/, as the server doesn't accept range request, which is what /viscurl/ uses to do chunked reading.
``curl  "https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=false&situationType=TRAFFIC_ANNOUNCEMENT" -H "Accept-Encoding: gzip"  -H "Range: bytes=0-15" --output -| gunzip`` returns the whole file instead of the first 16 bytes

As answered in https://lists.osgeo.org/pipermail/gdal-dev/2022-November/056404.html, you can set the CPL_CURL_GZIP=YES environment variable/configuration option to fix this. For mapserver, use a ``CONFIG "CPL_CURL_GZIP" "YES"`` block (https://mapserver.org/mapfile/map.html) . For QGIS, go to Settings/Options/System/Environment
Actually, I realize you don't need to do it, as GDAL will automatically set "Accept-Encoding: gzip" if the curl version has zlib support and if you use the "https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=false&situationType=TRAFFIC_ANNOUNCEMENT" URL without /vsicurl/
```
$ ogrinfo  "https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=false&situationType=TRAFFIC_ANNOUNCEMENT" -so
INFO: Open of `https://tie.digitraffic.fi/api/v3/data/traffic-messages/simple?inactiveHours=0&includeAreaGeometry=false&situationType=TRAFFIC_ANNOUNCEMENT'
      using driver `GeoJSON' successful.
1: OGRGeoJSON
```

Note however that there was a regression in 3.6.0 regarding that, with a fix for 3.6.1 queued per https://github.com/OSGeo/gdal/pull/6687

**Comment by sgofferj** [comment]
Ah, I understand. I didn't know, though, that one can enter the URL in QGIS when selecting "file" instead of "http/https/ftp". That's fairly confusing but of course not GDAL's fault.

**Comment by rouault** [comment]
In GDAL 3.6.0, ``GDAL_HTTP_HEADERS="Accept-Encoding: gzip"`` can be used as a config option with /vsicurl/ and the like, but it doesn't seem to be honoured by S3 or Varnish Cache
Closing
