### ISSUE TITLE
QGIS crashes when applying .qml-style on GML-layer

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#6714]
This has been reported downstream before (https://github.com/qgis/QGIS/issues/50901) and was identified as related to GDAL.

## Expected behavior and actual behavior.

No crash is expected, but QGIS crashes when applying .qml-style on GML-layer.

## Steps to reproduce the problem.

With QGIS (tested with QGIS 3.29.0-Master):

1. Download and unzip [test_data.zip](https://github.com/qgis/QGIS/files/10018998/test_data.zip)
2. Drag'n'drop `test.gml` into QGIS
3. For this layer, load and apply style `BP_KennzeichnungsFlaeche_Flaeche.qml`
4. QGIS crashes

**No crash for GPKG**

If the same style is applied on `test.gpkg` (also included in [test_data.zip](https://github.com/qgis/QGIS/files/10018998/test_data.zip)), there's no crash.

## Operating system

Ubuntu 22.04.1 LTS

## GDAL version and provenance

3.4.1 from QGIS 3.29.0-Master (https://github.com/qgis/QGIS/commit/9b8be60f7b4bf81a953a718e192e25b40f611358)

**Comment by nicogodet** [comment]
Confirmed on GDAL 3.6.0 on Windows (OSGeo4W)

**Comment by elpaso** [comment]
The crash comes from the duplicated `zweckbestimmung` entry, which makes it an `OFTIntegerList` type, the expression evaluator considers it a string (because it gets converted to a string representation by the `default` entry in the switch from ` swq_expr_node *OGRFeatureFetcher`, when it comes to evaluation, again we take the default (`else`) which considers it a comparison between two strings, but the actual value to compare with is an integer and there is a null `string_value` in the expression node -> crash.

**Comment by elpaso** [comment]
I'm in doubt about the expected behavior (besides the obvious fact that it must not crash): the expression is `"zweckbestimmung" = 'Naturgewalten' or  "zweckbestimmung"  = 1000`, but the GML has two values for `zweckbestimmung`:

```xml
<ogr:featureMember>
    <ogr:test gml:id="GML_b0245903-e6cc-4068-b9ed-b3ef287b5581">
      <gml:boundedBy><gml:Envelope srsName="urn:ogc:def:crs:EPSG::25832"><gml:lowerCorner>343181.6727 5691983.6723</gml:lowerCorner><gml:upperCorner>343256.6939 5692122.4655</gml:upperCorner></gml:Envelope></gml:boundedBy>
      <ogr:geometryProperty><gml:Polygon srsName="urn:ogc:def:crs:EPSG::25832" gml:id="test.geom.0"><gml:exterior><gml:LinearRing><gml:posList>343181.6727 5691987.6714  [...]</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogr:geometryProperty>
      <ogr:rechtsstand>1000</ogr:rechtsstand>
      <ogr:ebene>0</ogr:ebene>
      <ogr:rechtscharakter>5000</ogr:rechtscharakter>
      <ogr:flaechenschluss>false</ogr:flaechenschluss>
      <ogr:zweckbestimmung>3000</ogr:zweckbestimmung>
      <ogr:zweckbestimmung>1000</ogr:zweckbestimmung>
    </ogr:test>
  </ogr:featureMember>
```

an `contains` operator (or an inverted `IN`) would be more appropriate than an `=` in this case.

What is the expected result from `"zweckbestimmung"  = 1000`  ? 
I think it should be `false`.

**Comment by rouault** [comment]
> I think it should be `false`.

yes, makes sense

true should probably only be returned for ``zweckbestimmung = '(2:3000,1000)'`` (which is the string serialized representation of the IntegerList)  or ``zweckbestimmung LIKE '%1000%'``, but the behaviour of SQL operators with the IntegerList type has probably never been really well defined in OGR SQL (not sure what other implementations like PostgreSQL do for such type)

Just avoiding the crash would be a reasonable fix.

**Comment by pathmapper** [comment]
> Just avoiding the crash would be a reasonable fix.

👍 

FYI: 
The style was created for a GML which has only one value for `zweckbestimmung` (Integer) and later applied also on a GML with two values for `zweckbestimmung` (IntegerList). It's not expected that `"zweckbestimmung" = 1000` returns `true` for the GML with two values/IntegerList.
