### ISSUE TITLE
Wrong library import generated if providing CRYPTOPP_LIBRARY_DEBUG and CRYPTOPP_LIBRARY_RELEASE

### ISSUE THREAD

**Issue by hebersgit** [OSGeo/gdal#7338]
If I providing both variables, **CRYPTOPP_LIBRARY_DEBUG** and **CRYPTOPP_LIBRARY_RELEASE**, and generate Visual Studio projects with cmake, the generated project GDAL.vcxproj contains invalid settings. The linked input libraries are generated wrong:
```
[...]
<Link>    <AdditionalDependencies>odbc32.lib;optimized%3BC:\Src\MyDlls\cryptopp\8.8\v143\lib\x64\release\cryptopp.lib%3Bdebug%3BC:\Src\MyDlls\cryptopp\8.8\v143\lib\x64\debug\cryptopp.lib;wbemuuid.lib;...</AdditionalDependencies>
</Link>
[...]
```
The libpath generated in `<gdal-base-dir>\cmake\modules\packages\FindCryptoPP.cmake`, which seems to be generated by function `select_library_configurations(CRYPTOPP)`, seems not to be treated correct for generating VS-projects.

## Expected behavior and actual behavior.

Should set different correct formatted library-paths for debug and release projects,
- for relase-config e.g. : `C:\Src\MyDlls\cryptopp\8.8\v143\lib\x64\release\cryptopp.lib`
- for debug-config e.g. : `C:\Src\MyDlls\cryptopp\8.8\v143\lib\x64\debug\cryptopp.lib`

## Steps to reproduce the problem.

- build your own cryptopp
- build gdal with providing the following parameters in cmak.config:
```
set (CRYPTOPP_INCLUDE_DIR "C:\\Src\\MyDlls\\cryptopp\\8.8\\v143\\include" CACHE STRING "" FORCE)
set (CRYPTOPP_LIBRARY_RELEASE "C:\\Src\\MyDlls\\cryptopp\\8.8\\v143\\lib\\x64\\release\\cryptopp.lib" CACHE STRING "" FORCE)
set (CRYPTOPP_LIBRARY_DEBUG "C:\\Src\\MyDlls\\cryptopp\\8.8\\v143\\lib\\x64\\debug\\cryptopp.lib" CACHE STRING "" FORCE)
set (CRYPTOPP_USE_ONLY_CRYPTODLL_ALG ON CACHE BOOL "" FORCE)
set (GDAL_USE_CRYPTOPP ON CACHE BOOL "" FORCE)
```

## Operating system

Windows 11

## GDAL version and provenance

3.6.2

**Comment by dg0yt** [comment]
Just a quick look: I assume the problem is here:
https://github.com/OSGeo/gdal/blob/9098af3eb3cc4a3f33dd1df224063be23bb0d1b7/cmake/modules/packages/FindCryptoPP.cmake#L82
With both libraries provided, `CRYPTOPP_LIBRARY` isn't a single file path, but two file paths marks with `optimized` and `debug`. These keywords aren't handled for the `IMPORTED_LOCATION` property. What is needed is setting per-config properties, like here:
https://github.com/OSGeo/gdal/blob/35c07b18316b4b6d238f6d60b82c31e25662ad27/cmake/modules/packages/FindDeflate.cmake#L92-L115
