### ISSUE TITLE
Remove ogrsqlite3ext.h

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#7444]
While discussing on the SQLite forums about compilation options, it appears that they found that the GDAL usage of SQLite was ill-conceived.

I drop it here in case it is something that could be inserted in the GDAL dev roadmap. (But I don't need it, it is just for information)

[https://sqlite.org/forum/forumpost/0138fd5fc9](https://sqlite.org/forum/forumpost/0138fd5fc9)

> The GDAL code basically duplicates the sqlite_api structure and "links up" names to its own version of the structure which includes the sqlite3_mutex* APIs and does not know how to handle the names not existing as exports even though they are never used.
> 
> Like I said, it is a really ill-conceived design.
> 
> The proper way to build a dynamic call trampoline is to loop though the required entry-points by name, and if the name exists in the DCSS then store the address in the trampoline. Then you let your trampoline code handle what to do with missing entries (or just explode when loading the trampoline if a required entry is missing).
> 
> The sqlite3 os modules are an example of how to load and use a trampoline properly.
>

**Comment by rouault** [comment]
> While discussing on the SQLite forums about compilation options, it appears that they found that the GDAL usage of SQLite was ill-conceived.

I read the discussion, but fail to understand what you want to change in GDAL / what the actual issue is. Not sure the answer you got in the SQlite forum are actually relevant to your problem.

If you want to link GDAL against a sqlite3 version that has no mutex support, you need to build GDAL with -DACCEPT_MISSING_SQLITE3_MUTEX_ALLOC=YES . Isn't that enough for your purpose ?

**Comment by chacha21** [comment]
> I read the discussion, but fail to understand what you want to change in GDAL / what the actual issue is
I have neither issue nor request to GDAL. My initial request was only for the sqlite side, and it is solved.

I just wanted to make a feedback to GDAL that the SQLite support could be improved by refactoring the sqlite "trampoline".

>If you want to link GDAL against a sqlite3 version that has no mutex support, you need to build GDAL with -DACCEPT_MISSING_SQLITE3_MUTEX_ALLOC=YES . Isn't that enough for your purpose
Right, but since I was not sure about what it would imply, I didn't want to resort to this build option.

Actually, my final conclusion is that providing an SQLite build to GDAL with THREADSAFE=1 rather than THREADSAFE=0 is certainly the best choice.

**Comment by rouault** [comment]
> I just wanted to make a feedback to GDAL that the SQLite support could be improved by refactoring the sqlite "trampoline".

well, that stuff is only used if loading GDAL as a SQLite loadable module, and I believe this is a bit broken , because GDAL itself links to sqlite, so when loading GDAL as a SQLite module from the sqlite3 interpreter (statically linked), you get with duplicate sqlite symbols (the static ones from the sqlite3 interpreter and the ones from libsqlite3.so loaded by libgdal.so). I guess we should just remove that capability, since I don't think it is really used.

> Right, but since I was not sure about what it would imply, I didn't want to resort to this build option.

That means that you can't use the SQLite based GDAL/OGR drivers from multiple threads, due to sqlite lacking the necessary locking.

> Actually, my final conclusion is that providing an SQLite build to GDAL with THREADSAFE=1 

Definitely, that's the default value in sqlite3's configura.ac

**Comment by rouault** [comment]
> well, that stuff is only used if loading GDAL as a SQLite loadable module, and I believe this is a bit broken , because GDAL itself links to sqlite, so when loading GDAL as a SQLite module from the sqlite3 interpreter (statically linked), you get with duplicate sqlite symbols (the static ones from the sqlite3 interpreter and the ones from libsqlite3.so loaded by libgdal.so). I guess we should just remove that capability, since I don't think it is really used.

oh well that part was "solved" per https://github.com/OSGeo/gdal/pull/7457

The thing we could improve is to remove the custom ogrsqlite3ext.h file and just use the standard sqlite3ext.h from SQLite. The custom file comes at ancient times when spatialite was sometimes distributed as "amalgamated", but that's no longer the case. Removing ogrsqlite3ext.h is blocked per https://github.com/gisinternals/buildsystem/pull/209
