### ISSUE TITLE
MacOS brew install gdal does not install python

### ISSUE THREAD

**Issue by sheffe** [OSGeo/gdal#7509]
(Heavy GDAL user for years but first time filing an issue, so let me start with a thank-you -- it enables so much.)

I can't determine if this is a bug, a deliberate behavior change by GDAL, or a Homebrew error -- happy to redirect elsewhere.

I'm on MacOS Monterey 12.6.3, using Homebrew version 4.0.9 to install gdal. In version 3.6.0, `brew install gdal` would result in gdal programs like gdalinfo, gdal_translate, etc. _and_ the Python tools (eg gdal_proximity.py, gdal_calc.py) being available in `/opt/homebrew/bin`. 

For 3.6.2 and 3.6.3, none of the GDAL python scripts are available in `opt/homebrew/bin` after installation. I was not able to test 3.6.1.

I have one indication that it's not a homebrew error -- looks like [3.6.3 on Arch](https://archlinux.org/packages/community/x86_64/gdal/files/) also doesn't retain the `.py` files in `/usr/bin` on installation, but I don't have an Arch machine to test on my own.

A little extra detail: after a clean installation of Homebrew and GDAL 3.6.3 this morning, I see `ls /opt/homebrew/bin | grep gdal` return:
gdal-config
gdal_contour
gdal_create
gdal_grid
gdal_rasterize
gdal_translate
gdal_viewshed
gdaladdo
gdalbuildvrt
gdaldem
gdalenhance
gdalinfo
gdallocationinfo
gdalmanage
gdalmdiminfo
gdalmdimtranslate
gdalsrsinfo
gdaltindex
gdaltransform
gdalwarp

and `ls /opt/homebrew/bin | grep "py$"` returns nothing.

**Comment by rouault** [comment]
for Arch Linux, they are in a separate "python-gdal" package https://archlinux.org/packages/community-testing/x86_64/python-gdal/

I suspect this is a packaging issue with brew.
I see in https://github.com/Homebrew/homebrew-core/blob/4a0a48e323bfff0507451f5a4dc4f6aaa8522c59/Formula/gdal.rb#L82 that they do some fragile hacking of GDAL's swig/python/CMakeLists.txt . This might no longer work due to recent changes.
You may want to file a bug about that to https://github.com/Homebrew/homebrew-core/issues/new?assignees=&labels=bug&template=bug.yml

**Comment by sheffe** [comment]
If anyone stumbles on this issue in the future:
- Even's [general diagnosis here](https://github.com/OSGeo/gdal/issues/7509#issuecomment-1483094209) was correct
- [This issue](https://github.com/Homebrew/homebrew-core/issues/126623) shows how Homebrew-core diagnosed the details and patched it

(Thanks again @rouault, this was <48 hours to fixed after to your suggestion on where to look.)
