### ISSUE TITLE
Build error on minified_zutil.h on GDAL 3.7.0 on Gentoo and derivatives

### ISSUE THREAD

**Issue by seemantk** [OSGeo/gdal#7739]
## Expected behavior and actual behavior.

compile and build gdal-3.7.0

## Steps to reproduce the problem.

use ninja to build and seeing this error:

`[41/1099] /usr/bin/x86_64-pc-linux-gnu-gcc -DDONT_DEPRECATE_SPRINTF -DGDAL_COMPILATION -DHAVE_SSE_AT_COMPILE_TIME   -mtune=generic -O2 -pipe -fvisibility=hidden -fPIC -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-prototypes -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wfloat-conversion -std=gnu99 -MD -MT frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o -MF frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o.d -o frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o -c /var/tmp/portage/sci-libs/gdal-3.7.0/work/gdal-3.7.0/frmts/zlib/contrib/infback9/infback9.c
FAILED: frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o 
/usr/bin/x86_64-pc-linux-gnu-gcc -DDONT_DEPRECATE_SPRINTF -DGDAL_COMPILATION -DHAVE_SSE_AT_COMPILE_TIME   -mtune=generic -O2 -pipe -fvisibility=hidden -fPIC -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-prototypes -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wfloat-conversion -std=gnu99 -MD -MT frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o -MF frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o.d -o frmts/zlib/contrib/infback9/CMakeFiles/infback9.dir/infback9.c.o -c /var/tmp/portage/sci-libs/gdal-3.7.0/work/gdal-3.7.0/frmts/zlib/contrib/infback9/infback9.c
In file included from /var/tmp/portage/sci-libs/gdal-3.7.0/work/gdal-3.7.0/frmts/zlib/contrib/infback9/infback9.c:6:
/var/tmp/portage/sci-libs/gdal-3.7.0/work/gdal-3.7.0/frmts/zlib/contrib/infback9/minified_zutil.h:194:45: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  194 |     ZEXTERN uLong ZEXPORT adler32_combine64 OF((uLong, uLong, z_off_t));
      |                                             ^~
/var/tmp/portage/sci-libs/gdal-3.7.0/work/gdal-3.7.0/frmts/zlib/contrib/infback9/minified_zutil.h:195:43: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  195 |     ZEXTERN uLong ZEXPORT crc32_combine64 OF((uLong, uLong, z_off_t));
      |                                           ^~
/var/tmp/portage/sci-libs/gdal-3.7.0/work/gdal-3.7.0/frmts/zlib/contrib/infback9/minified_zutil.h:196:47: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OF'
  196 |     ZEXTERN uLong ZEXPORT crc32_combine_gen64 OF((z_off_t));
      |                                               ^~
`

## Operating system

Funtoo 'next'

## GDAL version and provenance

gdal-3.7.0

**Comment by danielrobbins** [comment]
@rouault we have some options there. One option is to give you access to our VPN via wireguard so you can log into a system where we have already reproduced the issue. The second option is to point you to an LXD image and give you steps to do-it-yourself. Third option is we can generate a docker image and hand it to you along with repro steps. First option is probably ideal if you are comfortable setting up wireguard, because we are already locking Funtoo to use the previous version of gdal for the time being so it's best if we set up the bug reproduction and then give you steps to access it. If wireguard works, we have docs here: 

https://www.funtoo.org/Funtoo:User_Services/VPN_Setup

The setup steps should be similar on other Linux distros. You just need wireguard-tools and the kernel module available. You can email me at drobbins@funtoo.org with your public key if you are OK going this route.

Steps 2 and 3 will probably involve us adding 3.7.0 to Funtoo, but as a "masked" version, so you can then "unmask" it for reproduction. Also an option if option 1 just doesn't work for you.

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/7741
