### ISSUE TITLE
JP2KAK driver writing RPB into jpeg2000 file when GMLJP2 is disabled

### ISSUE THREAD

**Issue by mtobby** [OSGeo/gdal#7800]
Hi, 
I have an jpeg2000 raster that come with RPB file with the same name.
When I do gdal_translate to the raster, I get that the RPB data is saved into the raster (I am seeing it using gdalinfo).
I want that the raster will not contain this information, I tried to set the GMLJP2 = NO, but I still got that the RPB data is saved into the raster.

I am using gdal 3.6

**Comment by jratike80** [comment]
Do you think that you have found a bug, or did you just want to ask a question? If the latter, the gdal-dev mailing list is the place to ask questions.

By reading the driver manual page https://gdal.org/drivers/raster/jp2kak.html there seems to be totally three creation options which deal with georeferencing: GMLJP2=, GMLJP2V2_DEF=, and GeoJP2=.  Have you tried to set all of then into NO?

Just to be sure, you mention JP2KAK in the title. Do you really have that driver in your system? I ask because it requires that you have acquired the non-open Kakadu SDK.

**Comment by rouault** [comment]
@mtobby It is not clear which output format you use, but I'll assume it is GeoTIFF.
And I'd assume you don't want to RPCCoefficientTag TIFF tag to be written with the RPC information.
If so, something like the following will prevent writing the RPCCoefficientTag (-co PROFILE=GeoTIFF), and the fallback RPB file ( -co RPB=NO), as well as the PAM .aux.xml side car file (--config GDAL_PAM_ENABLED NO):
```
gdal_translate ../autotest/gcore/data/md_dg.tif out.tif -co PROFILE=GeoTIFF -co RPB=NO --config GDAL_PAM_ENABLED NO
```

**Comment by rouault** [comment]
Ah if the output driver is JP2KAK, you actually want to disable GEOJP2, which is the encoding that conveys RPC using the RPCCoefficientTag TIFF tag, and possible also the  PAM .aux.xml side car file:
```
gdal_translate ../autotest/gcore/data/md_dg.tif out.jp2 -of JP2KAK  -co GEOJP2=NO --config GDAL_PAM_ENABLED NO
```
