### ISSUE TITLE
Improve CSV driver separator detection process

### ISSUE THREAD

**Issue by moicalcob** [OSGeo/gdal#7829]
## Expected behavior and actual behavior.

I expected to be able use ogr2ogr using the CSV driver with the following file, which is a CSV  using semi-colons as separator:

[comma_separated.csv](https://github.com/OSGeo/gdal/files/11564202/comma_separated.csv)

But as it contains a comma inside a column' name, it takes the comma as the expected separator.

## Steps to reproduce the problem.

Execute the following command using the attached file:

```
ogr2ogr --debug ON -f CSV ./output.csv CSV:./comma_separated.csv
```

And check that it takes the `,` as separator:

<img width="773" alt="Screenshot 2023-05-25 at 13 25 56" src="https://github.com/OSGeo/gdal/assets/56086628/f91e8c50-c976-4387-9233-334887c1b41e">

## Operating system

MacOS Ventura 13.2.1

## GDAL version and provenance

GDAL 3.6.4, released 2023/04/17

**Comment by jratike80** [comment]
The command will work if you edit the header line and doing that does not feel too hard for me.

`Column1 ; "Column2 (7,4a)" ; Column3 ; Column4 ; Column5 ; Column7 ; Column 8 ; Column 9`

Maybe the documentation, that is correct per se, could be enhanced so that the need to enclose a field name that is using reserved characters is mentioned. Perhaps via a new example.

> The driver will also accept a semicolon, a tabulation, a pipe, or a space character as field separator . This autodetection will work only if there's no other potential separator on the first line of the CSV file. Otherwise it will default to comma as separator.

**Comment by rouault** [comment]
improvements in https://github.com/OSGeo/gdal/pull/7831
