### ISSUE TITLE
ogr2ogr MVT driver closes hole in polygon

### ISSUE THREAD

**Issue by leofuhrmann** [OSGeo/gdal#7890]
## Expected behavior and actual behavior

I expected the vector tile(s), created from a shapefile ([problematic_polygon.zip](https://github.com/OSGeo/gdal/files/11635642/problematic_polygon.zip)) using `ogr2ogr`, to represent a polygon with two holes. Instead, depending on the zoom level, the polygon has closed holes.

## Steps to reproduce the problem

1. Create vector tiles using `ogr2ogr -f MVT tileset -dsco MAXZOOM=15 problematic_polygon.shp`
2. Visualize vector tile set using any tool (e. g. QGIS with Vector Tiles Reader)
3. Zoom to zoom level 15 (upper hole is closed, relevant vertices are missing)

## Operating system

macOS Ventura (Version 13.3.1)

## GDAL version and provenance

GDAL 3.6.4 installed via homebrew

**Comment by jratike80** [comment]
The original geometry seems to have vertices at very close distance in a few places

<img width="114" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/58c37a59-a5c2-42f0-89bf-51006cbb2d6b">

Maybe the quantization of coordinates into integers for the MVT geometry creates initially an invalid geometry, that is then processed with "make valid", and the hole is removed in that process. That should not happen and I believe that you have found a bug but I try to think about what could go wrong.

**Comment by rouault** [comment]
The issue was indeed related to the current algorithm discarding inner rings that have become invalid after quantization. The largest inner ring once quantized (in yellow) indeed produced a self intersection at:

![image](https://github.com/OSGeo/gdal/assets/1192433/d945da6b-4a2a-42dd-a298-8314d9a54cce)

https://github.com/OSGeo/gdal/pull/7891 fixes that by running MakeValid() on the whole quantized polygon and hope for it to make the most sense of it, which works here.
