### ISSUE TITLE
Missing preprocessor directives for static linking on Windows

### ISSUE THREAD

**Issue by dnewhall** [OSGeo/gdal#7955]
We build GDAL.dll on Windows with all the dependencies/optional libraries statically linked (so there're no DLL loading conflicts when our software is embedded inside others). We are currently building the source from gdal.org on Windows 11 with Visual Studio 2019 as RelWithDebInfo.

We found that with the new CMake build system we have to modify the generated Visual Studio project file to get the final linker step for gdal.dll to work.

Specifically, for Curl and Expat certain parts of the GDAL codebase have to be compiled with the following added after the <PreprocessorDefinitions> tag:
XML_STATIC
CURL_STATICLIB

Additionally, the following have to be added after the <AdditionalDependencies> tag:
Wldap32.lib;normaliz.lib;

**Comment by dnewhall** [comment]
To clarify, we are building against Expat, Curl, and OpenSSL all as static libraries. Those changes are needed to get those specific libraries to work.

**Comment by rouault** [comment]
General remark: static linking is hard, due to generally lack of automated information from libraries you're linking against on what is needed to statically linked

@dnewhall It would help if you could provide an archive with the headers and .lib of those static libraries as this would simplify reproduction

Note for self: https://github.com/curl/curl/issues/8591 and https://github.com/Microsoft/vcpkg/issues/1100 seems relevant

Actually seeing the later, you might perhaps have a try using static libraries provided by vcpkg, or even just using the GDAL static build from it

**Comment by dnewhall** [comment]
Files attached. We build with the following command:

# Run from D:\gdal-3.7.0\build with all the libraries in subdirectories in the source directory
cmake -G "Visual Studio 16 2019" -DBUILD_APPS=OFF -DBUILD_SHARED_LIBS=ON ^
	-DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=D:\gdal-3.7.0 ^
	-DCMAKE_CXX_FLAGS="-DCURL_STATICLIB -DXML_STATIC" -DGDAL_USE_EXTERNAL_LIBS=OFF ^
	-DPROJ_INCLUDE_DIR="D:\gdal-3.7.0\proj-6.3.1\src" ^
	-DPROJ_LIBRARY_RELEASE="D:\gdal-3.7.0\proj-6.3.1\build_VS2017_x64\lib\RelWithDebInfo\proj.lib" ^
	-DGDAL_USE_CURL=ON -DCURL_INCLUDE_DIR="D:\gdal-3.7.0\libcurl\include" -DCURL_LIBRARY_RELEASE="D:\gdal-3.7.0\libcurl\lib\libcurl.lib" ^
	-DGDAL_USE_OPENSSL=ON -DOPENSSL_ROOT_DIR="D:\gdal-3.7.0\openssl-1.1.0f-vs2017" -DOPENSSL_USE_STATIC_LIBS=TRUE -DOPENSSL_MSVC_STATIC_RT=TRUE ^
	-DGDAL_USE_EXPAT=ON -DEXPAT_INCLUDE_DIR="D:\gdal-3.7.0\Expat\lib" -DEXPAT_LIBRARY="D:\gdal-3.7.0\Expat\RelWithDebInfo\libexpat.lib" ^
	..

[Expat.zip](https://github.com/OSGeo/gdal/files/11770632/Expat.zip)
[libcurl.zip](https://github.com/OSGeo/gdal/files/11770633/libcurl.zip)
[openssl-1.1.0f-vs2017.zip](https://github.com/OSGeo/gdal/files/11770705/openssl-1.1.0f-vs2017.zip)

**Comment by dnewhall** [comment]
We found one more: Apparently XercesC also requires a XERCES_BUILDING_LIBRARY preprocessor directive for static linking.

**Comment by dg0yt** [comment]
> XERCES_BUILDING_LIBRARY

... which by name is a macro for building, not consuming, xerces.

If you really want to use static linking, you better systematically modify your installations of the dependencies. This is what vcpkg does. It is O(n) with n dependencies, instead of O(n*m) with n dependencies and m consumers. Where the dependencies know their configuration at build time and the consumers (gdal) only could guess.
For

> Additionally, the following have to be added after the tag:
> Wldap32.lib;normaliz.lib;

For example, wldap32 isn't generally needed for curl.

**Comment by dg0yt** [comment]
> Looking at the include files generated when building XercesC as static shows that XERCES_BUILDING_LIBRARY is needed to use on Windows.

Looking at [src/xercesc/util/XercesDefs.hpp](https://github.com/apache/xerces-c/blob/5052c90b067dcc347d58822b450897d16e2c31e5/src/xercesc/util/XercesDefs.hpp#L136-L137), `XERCES_BUILDING_LIBRARY` is meant to be used with `DLL_EXPORT` to switch between dllimport and dllexport. `DLL_EXPORT` comes from `src/xercesc/util/Xerces_autoconf_config.hpp.cmake.in` when building with CMake (and it may also come from an unexpected side if because it doesn't use a good prefix...).

> (built with simply nmake /f Makefile.vc mode=static)

But do you use ldap with curl with gdal?
I really didn't want to talk about the default. This the best possible guess, but it remains a guess. Even curl's nmake build system has knobs to turn dependencies on and off.
And curl's cmake build system offers to export cmake config exactly as built.

**Comment by huzaifacontour** [comment]
@rouault Can I use geos static library here?
Having this kind of errors with geos and proj:
ld: Undefined symbols:
  geos::triangulate::VoronoiDiagramBuilder::getDiagram(geos::geom::GeometryFactory const&), referenced from:
      _GEOSVoronoiDiagram_r in libgeos_c.a[3](geos_ts_c.cpp.o)
