### ISSUE TITLE
ogr2ogr Postgis driver ignores -nlt CONVERT_TO_LINEAR in combination with -nlt GEOMETRY

### ISSUE THREAD

**Issue by Harm-Olthof** [OSGeo/gdal#8101]
## Expected behavior and actual behavior.
I want to load several sources with different geometry types into one Postgis table, therefore I use the parameter -nlt GEOMETRY
I also add -nlt CONVERT_TO_LINEAR  to prevent curved geometries. The latter seems to be ignored, because when I run:
SELECT distinct ST_GeometryType(geom) from bgt.bgt_weginrichtingselement
I get: "ST_MultiCurve" als result. I would expect "ST_LINESTRING"

## Steps to reproduce the problem:

ogr2ogr --config CPL_DEBUG ON -overwrite -skipfailures -f PostgreSQL PG:"host=%EKG_PG_HOST% port=%EKG_PG_PORT% user=%EKG_PG_USER% password=%EKG_PG_PW% dbname=%EKG_PG_DB_NAME% schemas=bgt" -nln bgt_weginrichtingselement -lco LAUNDER=no -spat 206912 540346 278026 621876 -lco LAUNDER=no -spat_srs EPSG:28992 -a_srs EPSG:28992 -nlt GEOMETRY  -nlt CONVERT_TO_LINEAR -where "eindregistratie is NULL" bgt_20230714.gpkg bgt_weginrichtingselement_L

## Operating system

Microsoft Windows [Version 10.0.22000.2176]

## GDAL version and provenance
ogr2ogr --version
GDAL 3.7.0, released 2023/05/02  (OSGeo4W shell)

**Comment by jratike80** [comment]
I think that this is not a bug but it may be a missing feature. By the synopsis the -nlt parameter is supposed to be used only once:

` [-nlt type|PROMOTE_TO_MULTI|CONVERT_TO_LINEAR|CONVERT_TO_CURVE]`

However, there is one documented exception https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-nlt

> Starting with GDAL 3.0.5, -nlt CONVERT_TO_LINEAR and -nlt PROMOTE_TO_MULTI can be used simultaneously.

**Comment by Harm-Olthof** [comment]
@jratike80 Thanks, I think you are right, I should have close read the documentation better. I will submit this as feature request. 
I think however, that there are possible more subtleties to the issue: e.g. changing the order from  -nlt GEOMETRY -nlt CONVERT_TO_LINEAR to -nlt CONVERT_TO_LINEAR -nlt GEOMETRY gives the same results. From a user experience it would be better to give an error. Like "conflicting -nlt parameters" or something.

**Comment by jratike80** [comment]
The better user experience would be nice but I do not know what would be the best way to achieve that. Obviously `-nlt` was originally meant to be just a single choice, and because `-nlt POINT -nlt POLYGON` clearly makes as little sense than using `-f GPKK -f JML` or `-t_srs EPSG:4326 -t_srs EPSG:3857` and other repeated parameters the user input is not even checked. Maybe CONVERT_TO_LINEAR should rather be an own option like the `-explodecollections` option. Allowing some combinations of -nlt parameters but not all of them is also unfriendly both to developers and users.

**Comment by Harm-Olthof** [comment]
@jratike80 very good points and directions. So what can/should I do to get these points adressed in the development cycle of the GDAL project? (Not having too much experience with this proces of submitting bugs/requests?)  Or is this issue and the previous discussion enough to be taken up by de developers?

**Comment by jratike80** [comment]
It seems that this issue is connected with https://github.com/OSGeo/gdal/issues/2338.

It is often complicated to change the behavior of some (mis)features which have been existing for a long time. The -nlt CONVERT_TO_LINEAR has been there for 8 years since GDAL version 2.0 was released so it is not really feasible to remove it. Maybe adding a support for a combination of -nlt GEOMETRY and -nlt CONVERT_TO_LINEAR like you originally suggested is a possible way to go. The use case does not feel especially uncommon.

**Comment by Harm-Olthof** [comment]
@rouault Thanks for taking this up and implemting it so fast! @jratike80 thanks for helping to  explore  possible solutions
