### ISSUE TITLE
Missing proj:epsg for CRS in gdalinfo -json output

### ISSUE THREAD

**Issue by julian-zeidler** [OSGeo/gdal#8137]
STACIT Driver currently only utilizes proj:epsg to get CRS
https://github.com/OSGeo/gdal/blob/6e268bb61c95462d2704dca2ec0cad7d95d32df1/frmts/stacit/stacitdataset.cpp#L220

Other implementations eg odc-stac use proj:wkt2 and proj:projjson as fallback  for CRS without EPSG Code. This enables usage of stuff like the MODIS sinusoidal Grid. 
 see https://odc-stac.readthedocs.io/en/latest/stac-best-practice.html

**Comment by rouault** [comment]
> STACIT Driver currently only utilizes proj:epsg to get CRS

well, if you look lines below the one you mention, it tries projwkt2 and proj:projjson as well.
Can you point to a STAC document where the fallback doesn't work ? This might be due to "proj:epsg" missing. The driver requires "proj:epsg" to be set to null (then the IsValid() test should pass), as required by https://github.com/stac-extensions/projection#projepsg, before trying the fallbacks
That said I don't see any unit tests for that, so it is possible that this doesn't work.

**Comment by julian-zeidler** [comment]
Hi Even,

You are right. I was the missing proj:epsg. I created the test json I was using based on the output of gdalinfo -json which unfortunatly only contained "proj:shape" and "proj:projjson".

**Comment by rouault** [comment]
Re-opening as gdalinfo -json should output conformant STAC projection extension, and we could be a bit more resilient in the STACIT driver

**Comment by julian-zeidler** [comment]
As the proj:epsg is not mandatory anymore in current release, it would correct not to fail if any of the other fields are available. 

"Also, [version 1.0.0](https://github.com/stac-extensions/projection/releases/tag/v1.0.0) of this extension required proj:epsg (either as integer or null) in Item Properties. This is not required anymore, but it is still recommended to additionally provide an EPSG code whenever available."
