### ISSUE TITLE
Python - GetNoDataValue type is not consistent with Band's DataType

### ISSUE THREAD

**Issue by jm-uom** [OSGeo/gdal#8197]
Gdal 3.7.1 on Python 3.9.x

If the raster band's datatype is an `int`, the datatype of the NoData value should be an int too.

```
print(gdal.GetDataTypeName(band.DataType))
# 'Int32'

print(band.GetNoDataValue())
# -9999.0

print(type(band.GetNoDataValue()))
# Float
```

**Comment by rouault** [comment]
I can understand but your point of view, but this reflects the C API which always return a double. I don't see a strong enough point to change the Python API to return a tighter type, especially since, athough not nominal, some drivers might return a non-integer representable value for the nodata value
