### ISSUE TITLE
Bump to C++17?

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#8270]
How consequential and disruptive would it allow and enable C++17 in the GDAL library? Are we ready to do so at our next major release, or would there still be detrimental impacts?

**Comment by rouault** [comment]
Looking at https://en.wikipedia.org/wiki/C%2B%2B17#Compiler_support , it seems that compiler support for it is quite widespread (GCC >= 8, clang >= 5, MSVC >= 2017) and shouldn't be an issue. For example Ubuntu 20.04 (old LTS) ships with gcc 9 which is the minimum to get C++17), Debian Bullseye (oldstable) ships with gcc 10

**Comment by rouault** [comment]
Starting on this. We need to first migrate the ubuntu 18.04 based CI configs

**Comment by dbaston** [comment]
> We need to first migrate the ubuntu 18.04 based CI configs

I got started on this and then began to wonder if it made sense to reuse https://github.com/OSGeo/gdal/blob/master/docker/ubuntu-full/Dockerfile as a base.

**Comment by rouault** [comment]
> I got started on this and then began to wonder if it made sense to reuse https://github.com/OSGeo/gdal/blob/master/docker/ubuntu-full/Dockerfile as a base.

ah ok, my idea was:
- replace ubuntu_1804_32bit  by a alpine i386 since newer Ubuntu no longer have a i386 distribution. Cf https://github.com/rouault/gdal/commit/51efd0e0a3cc43818f5d5fb5bf2b2a12fb691924 (untested) which tries to make a single config for alpine 32 and 64 bit
- retire ubuntu_1804, and move mongodb compilation to ubuntu_2004, and move most of services.sh & test.sh there too
- Travis CI: hopefully just update ``dist``
But I'm open to have a ubuntu 2204 target

**Comment by dbaston** [comment]
I don't want to hold you up, and I should avoid taking on new things until I finish the autotest work. Maybe we can keep it in mind when we add a 22.04 target.

**Comment by rouault** [comment]
> I don't want to hold you up, and I should avoid taking on new things until I finish the autotest work. Maybe we can keep it in mind when we add a 22.04 target.

I don't think that's holding anything. I've switched to something else. Unassigning me. Feel free to take it over

**Comment by rouault** [comment]
implemented in 3.9 per RFC98
