### ISSUE TITLE
OSM: Feature Count not available

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#8290]
## Expected behavior and actual behavior.

`ogrinfo` shows Feature Count for OSM file layer but instead it shows `-1`.

## Steps to reproduce the problem.
`ogrinfo test.osm multipolygons` (sample data: [test.zip](https://github.com/OSGeo/gdal/files/12474096/test.zip))

![grafik](https://github.com/OSGeo/gdal/assets/20856381/cb3cec64-d5d0-48a2-9c81-e2f31af5892a)

or drag'n'drop the sample file in QGIS:

![grafik](https://github.com/OSGeo/gdal/assets/20856381/3c1003a1-2a3a-4546-bee1-084fb9b10fec)

Attribute table:
![grafik](https://github.com/OSGeo/gdal/assets/20856381/da2e77f5-c1fb-4e54-90de-48d5aa998e92)

## Operating system

Windows 10 Version 1809

## GDAL version and provenance

3.6.4 and 3.7.1 from OSGeo4W

**Comment by pathmapper** [comment]
> As a workaround you can run a SQL query

Thanks! but ofc not an option when drag'n'drop the file in QGIS.

For some reason ogrinfo + SQL query shows for multipolygons a different number (138) compared to the count in the attribute table in QGIS (99)

```
ogrinfo test.osm -so -sql "select * from multipolygons"
...
Layer name: multipolygons
Geometry: Multi Polygon
Feature Count: 138
```

**Comment by jratike80** [comment]
I can't say why QGIS shows a different number.

I checked the documentation of the GetFeatureCount() what is the function that ogrinfo is using.

> Fetch the feature count in this layer.
> Returns the number of features in the layer. For dynamic databases the count may not be exact. If force is 0, and it would be expensive to establish the feature count a value of -1 may be returned indicating that the count isn't know. If force is 1 some implementations will actually scan the entire layer once to count objects.
> The returned count takes the spatial filter into account.
> Parameters:
> force - Flag indicating whether the count should be computed even if it is expensive.
> Returns:
> feature count, -1 if count not known.

I consider that this is not really a bug but the behavior is intentional. I guess there are also other drivers which don't support feature count. From users point of view I understand that sometimes it would be nice get the number of features count even if it is expensive. Using SQL is not the most natural option for all users but adding a `-force` flag to ogrinfo feels too much because it would have an effect on only few drivers. By the way, this query returns "725379" in about 20 seconds.

`ogrinfo algeria-latest.osm.pbf --config  OGR_INTERLEAVED_READING YES -dialect SQLite -sql "select count(*) from multipolygons"`

**Comment by pathmapper** [comment]
> I consider that this is not really a bug but the behavior is intentional.

Yes, seems like it is intentional -thanks @jratike80 .
