### ISSUE TITLE
ogrinfo --formats: document what order is used

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8315]
$ ogrinfo --formats

Prints the formats in some odd order.

The man page entry should mention what order it is, or mention no order.

**Comment by jratike80** [comment]
The place to edit is in the common options https://gdal.org/programs/raster_common_options.html#cmdoption-formats. The order matter because the drivers are tested in that order. See gdal.org/user/configoptions.html, there is a connection to GDAL_SKIP and OGR_SKIP configuration options. Feel free to have a try and make a PR for improving the documentation.

**Comment by jidanni** [comment]
Well OK but driver testing order isn't necessarily best public reading order.

Should the man page say "They are listed in driver testing order"?

**Comment by rouault** [comment]
cf https://github.com/OSGeo/gdal/pull/8318
