### ISSUE TITLE
GeoJSON 2008 creates invalid geometry (self-intersection)

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#8332]
## Expected behavior and actual behavior.

`ogr2ogr -f GeoJSON out.geojson test.gml -t_srs "EPSG:4326"` creates a valid geometry because the source geometry is valid but it creates a self intersecting geomety.

![grafik](https://github.com/OSGeo/gdal/assets/20856381/a0c39bd5-0551-432f-8703-9295ddf3ff4f)

![grafik](https://github.com/OSGeo/gdal/assets/20856381/e4d21c33-1078-46a7-ac40-4503be469757)

## Steps to reproduce the problem.

[test_data.zip](https://github.com/OSGeo/gdal/files/12523339/test_data.zip)

1. `ogr2ogr -f GeoJSON out.geojson test.gml -t_srs "EPSG:4326"`

2. Use "Check validity" from the processing toolbox in QGIS on out.geojson.

## Additional information

1. `-lco RFC7946=YES` creates a valid geometry:
`ogr2ogr -f GeoJSON out_7946.geojson test.gml -lco RFC7946=YES`

2. Reducing the precision doesn't help: 
`ogr2ogr -f GeoJSON out_7.geojson test.gml -t_srs "EPSG:4326" -lco COORDINATE_PRECISION=7`
 
## Operating system

Windows 10 Version 1809

## GDAL version and provenance

3.6.4 and 3.7.1 from OSGeo4W

**Comment by jratike80** [comment]
The behavior is not specific to GeoJSON 2008. The result is the same if the outputformat is for example JML that does not support curve geometries either.

The input file is in EPSG:25832 and it contains non-linear geometry. WKT begins with

`  CURVEPOLYGON (COMPOUNDCURVE ((317018.977 5681963.646,317002.781 5681973.088,316986.675 5681987.895,316985.397 5681986.773,316982.423 5681983.791),CIRCULARSTRING...` 

It is not guaranteed that conversion into a linear polygon in EPSG:4326 is producing a topologically valid geometry.
Ogr2ogr has an option for fixing the geometries which have lost their validity in the conversion https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-makevalid. It is not used by default because fixing a geometry is changing the geometry by removing vertices, dividing polygons into multipolygons or in some other way that may have bad side effects.

> Run the [OGRGeometry::MakeValid()](https://gdal.org/api/ogrgeometry_cpp.html#_CPPv4NK11OGRGeometry9MakeValidE12CSLConstList) operation, followed by [OGRGeometryFactory::removeLowerDimensionSubGeoms()](https://gdal.org/api/ogrgeometry_cpp.html#_CPPv4N18OGRGeometryFactory28removeLowerDimensionSubGeomsEPK11OGRGeometry), on geometries to ensure they are valid regarding the rules of the Simple Features specification.

In the problematic case the GeoJSON 2008 route as well as conversion into JML creates a self-intersection

<img width="437" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/0a3e2a3d-0a47-4bee-95ae-b17c6daecd46">

For some reason the GeoJSON 7946 route does not create self-intersection. I do not know why but I rather believe that it is by chance than by design.

<img width="357" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/5e0f747b-4dad-4dc1-89f4-947f05ded25d">

I do not see a bug here but I am slightly uncertain so I did not close the ticket yes.

**Comment by pathmapper** [comment]
Thanks @jratike80, I think you're right and this is not a bug. 

Just tried with a much [bigger dataset](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/9URfvgdO/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvYzkyZmUzMmMtYzI3YS00MjIzLTkxMDgtOGU5YTRjOTQyNzIx/test2.gml) ~176k features, a lot of them with circular arcs and while the GeoJSON 7946 route creates a better result (41 invalid features according to GEOS) compared to the GeoJSON 2008 route (192 invalid features) the result is not perfect.

So please close here if there is nothing to improve.

**Comment by jratike80** [comment]
Did you try `ogr2ogr -f GeoJSON out.geojson test.gml -t_srs "EPSG:4326" -makevalid`?

**Comment by jratike80** [comment]
There may be something in `ERROR 1: Linearring not allowed` but it requires more skills than what I have for finding out where they come. I checked that without `-t_srs "EPSG:4326"` those messages do not appear.

**Comment by pathmapper** [comment]
Some findings:

-> here are the 9 GML features with valid geometries: [all_9.zip](https://github.com/OSGeo/gdal/files/12645038/all_9.zip)

1. All 9 geometries include minimum 2 circular arcs.

2. `ERROR 1: Linearring not allowed` has nothing to do with the 9 invalid geometries:
`ogr2ogr -f GeoJSON out_all_9.geojson all_9.gml -t_srs "EPSG:4326" -makevalid`
results in 9 invalid geometries but no error shown for ogr2ogr.

Example (left before ogr2ogr):
<img src="https://github.com/OSGeo/gdal/assets/20856381/3766bdbf-6dbd-48bd-8ec5-775bed8b2053" height="350" /> <img src="https://github.com/OSGeo/gdal/assets/20856381/7dccb553-f528-4bf2-8b27-eb8efc165302" height="350" />

**3. If the conversion to GeoJSON and reprojection to EPSG:4326 is done in 2 steps, all geometries are valid without using `-makevalid` option!**

`ogr2ogr -f GeoJSON out_all_9_only_to_geojson.geojson all_9.gml`
`ogr2ogr -f GeoJSON out_all_9_reproject.geojson out_all_9_only_to_geojson.geojson -t_srs "EPSG:4326"`

So it looks like at least for thes 9 sample geometries the issue with resulting invalid geometries only happes if conversion to GeoJSON and reprojection are done in one single command:
`ogr2ogr -f GeoJSON out_all_9.geojson all_9.gml -t_srs "EPSG:4326"`
(and `-makevalid` is not able to fix this).

**Comment by pathmapper** [comment]
Also for  [test.zip](https://github.com/OSGeo/gdal/files/12646033/test.zip) from https://github.com/OSGeo/gdal/issues/8332#issue-1881875856, and the[ ~176k features](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/9URfvgdO/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvYzkyZmUzMmMtYzI3YS00MjIzLTkxMDgtOGU5YTRjOTQyNzIx/test2.gml) from https://github.com/OSGeo/gdal/issues/8332#issuecomment-1706852534 the resulting geometries are valid when conversion to GeoJSON and reprojection is done in two different steps in the following order:

1. `ogr2ogr -f GeoJSON out.geojson test.gml`


2. `ogr2ogr -f GeoJSON out_2.geojson out.geojson -t_srs "EPSG:4326"`

Important: 
The order of the steps matters:
 if `2. (reprojection to EPSG:4326)` is done before `1. (conversion to GeoJSON)`, the resulting geometry is invalid.

---
So maybe the fix for the single command `ogr2ogr -f GeoJSON out.geojson test.gml -t_srs "EPSG:4326"` would be to do the format conversion before the reprojection.

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/8419
