### ISSUE TITLE
Extra white space on first line of each converted element for ASC file

### ISSUE THREAD

**Issue by antoniolocandro** [OSGeo/gdal#8344]
## Steps to reproduce the problem.
Reported here as I suspect it is an upstream possible issue rather than a QGIS bug

Using QGIS convert the attached file
[PNOA_MDT200_ETRS89_HU30_Madrid.zip](https://github.com/OSGeo/gdal/files/12536590/PNOA_MDT200_ETRS89_HU30_Madrid.zip)

Raster > Conversion > Translate > Save to file as ASC
I guess the above steps can be done via the command line directly with GDAL but have no clue on how to do that

Extra white space on first line of each converted element, check line 7  / 8 
![image](https://github.com/OSGeo/gdal/assets/4627073/9ec1a4f3-2947-4e14-8e61-88fc4ee5453b)
![image](https://github.com/OSGeo/gdal/assets/4627073/3f849ab1-c130-4e54-9b9c-9f0d3a3e8206)

This makes the file not readable in software not expecting this white space which apparently is the norm or maybe I am mistaken but it would be great if there was an option/switch to produce an ASC version without the whitespace rather than removing it afterwards by some other mean

## Operating system

Windows 11

## GDAL version and provenance

GDAL 3.8.0dev-4b68c95c09 used in QGIS

**Comment by antoniolocandro** [comment]
As reference there is this post on the internet about a user testing in ESRI and QGIS noticing the QGIS version has the extra space and mentions a way to remove the unwanted white space at the beginning of each line

**Comment by jratike80** [comment]
I verified that ESRI ArcGIS Pro opens the .asc files from GDAL without problem.

Then I found this specification for ESRI ASCII grid https://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/esri-ascii-raster-format.htm.

> Data format
> The data component of the Esri ASCII raster follows the header information.
> 
> Cell values should be delimited by spaces.
> No carriage returns are necessary at the end of each row in the raster. The number of columns in the header determines when a new row begins.
> Row 1 of the data is at the top of the raster, row 2 is just under row 1, and so on.

The document has an example where the data rows do begin from the left margin. I also compared the asc files from GDAL and from ArcGIS Pro.

Differences:

GDAL
Data row begins with a space and ends with `LF` Thus, once `LF` is removed there is one space between the data values of subsequent rows.

ArcGIS
Data row begins with the first value and end with a sequence `space-CR-LF`. Thus, once `CR-LF` is removed there is one space between the data values of subsequent rows.

The specification "Cell values should be delimited by spaces" is not exact about how the data rows should begin. It is sure that it is not a problem for ESRI, and because GDAL has always written .asc files like that there must be loads of such .asc files hanging around.

Is is possible to contact the authors of the problematic software and ask if their product could be made more lenient?

What did your source in the internet say about the space at the end of lines? When they removed spaces from the beginning, did they add spaces to the end?

**Comment by antoniolocandro** [comment]
Hi thanks for the quick response, sorry I see the link to the internet source did not make it. It is at this forum https://georeference.org/forum/t158504.7#158509

The ASC file produce by Global Mapper does not have the white space so I was told that should be the correct way as you also show in the link directly by ESRI. Now if ESRI is able to parse GDAL produced ASC then I guess they just decided to allow it. Let me ask the software developers if they can implement the parsing on their side instead like ESRI does and allow GDAL produced ASC files to be read

**Comment by rouault** [comment]
Esri spec shows an example without leading space : https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/esri-ascii-raster-format.htm . Let's align on that: https://github.com/OSGeo/gdal/pull/8362
