### ISSUE TITLE
SQL: Implement SHOW before DROP or ALTER

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8429]
Do please remember, before implementing SQL DROP or ALTER, to first implement SHOW.

Just like in Unix, before implementing rm(1) there was a ls(1)  command, to allow the user to first be able to see the things s/he then might want to remove.

**Comment by jidanni** [comment]
I'm very happy that there are commands like ALTER TABLE,
https://gdal.org/user/ogr_sql_dialect.html#alter-table

The problem is, for any SQL dialect, one must be sure to
first implemtent SHOW TABLES, yes, even though one might be able to piece that
information together through other means. But that is not straight from the horses mouth.

Or, on the same page, mention what the guaranteed other means formula is.

Same with DROP COLUMN: be sure you document the official way to list the columns first.

Just like in UNIX,
we have an ls(1) command before we have an rm(1) command.
Or if there is no ls(1) command, then on the rm(1) man page
we say "to see what the files are that one can delete, use the find(1) command,
or 'echo *'.

At the bottom of
https://gis.stackexchange.com/questions/177545/convert-kml-to-geojson-with-ogr2ogr-and-remove-kml-special-attributes#comment268948_177554
he says he doesn't know the colunm names.

**Comment by rouault** [comment]
"show tables" can be done with ``ogrinfo``. DROP and ALTER were implemented as SQL commands as a convenience to be able to execute them through the command line (this can be done through the API too in a non-SQL way). SHOW is basically repeating ogrinfo. No need to do that IMHO

**Comment by jidanni** [comment]
OK, but then at

https://gdal.org/programs/ogrinfo.html#cmdoption-ogrinfo-sql


or at

> ogrinfo input.shp -sql "ALTER TABLE input ADD fieldX float"

there, I would mention "for SHOW TABLES, SHOW COLUMNS(?) use ..."

**Comment by jratike80** [comment]
This was the first time I heard about SHOW TABLES and SHOW COLUMNS. They are not standard SQL. Are they used in MySQL?

**Comment by jidanni** [comment]
You're right. 
https://stackoverflow.com/questions/50848075/is-show-statement-in-sql

Okay, anyway the documentation should say how to list things, before it says how to alter them.

**Comment by jratike80** [comment]
During the years I have been following GDAL mailing list and other forums I do not remember seeing this as an issue. I also spent half on hour with search engines and the study strengthened my belief. The referenced stackoverflow question is not a good example because the original poster says already in their question that they see the fields that they feel unnecessary by using ogrinfo. Their real problem was that they did not understand KML and that schema is adding custom attributes but it does not remove the standard ones.

Adding a line about ogrinfo into section of ALTER TABLE would not be expensive, but users must know the table name always (and column names frequently) when they use SQL.  org2ogr requires also column names for `-select` and `-where` and this has not been a problem.
