### ISSUE TITLE
-wgs84 affects error messages

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8464]
```
$ gdallocationinfo dem.tiff 87.5 -42.1
Report:
  Location: (87P,-43L)

Location is off this file! No further details to report.
$ gdallocationinfo dem.tiff -wgs84 87.5 -42.1
$
```
Error message gone. Yes`$?` gets set, but the program still fails silently.

**Comment by jratike80** [comment]
The first case is clear because by default the input is in x and y pixels https://gdal.org/programs/gdallocationinfo.html#cmdoption-gdallocationinfo-arg-x.
https://gdal.org/programs/gdallocationinfo.html#cmdoption-gdallocationinfo-arg-x

When you add `-wgs84` the command is changing more than you may believe. You used the same numbers `87.5 -42.1` but now they are presenting longitude and latitude. GDAL converts them into pixel coordinates by using the knowledge about the CRS of dem.tiff.
Is location 87.5E -42.1N outside your DEM? If it is then I would await some kind of error message.

**Comment by jidanni** [comment]
OK maybe it is working normally. I had better close this now.
