### ISSUE TITLE
NetCDF bottomup problem

### ISSUE THREAD

**Issue by rhijmans** [OSGeo/gdal#8477]
Here is a NetCDF file that GDAL (version 3.6.2) reads as if the data are "bottomup" whereas they are "topdown". 

https://www.dropbox.com/scl/fi/fybz1w514y3issi94q4yu/tp_GPCC_25_ltmonsum_1951_2000.nc?rlkey=azwxekzq8rn1woc67x804uaww&dl=0

See https://github.com/rspatial/terra/issues/1289 for illustrations.

These are the y coordinates (with R): 

```
f <- "tp_GPCC_25_ltmonsum_1951_2000.nc"
library(ncdf4)
nc <- ncdf4::nc_open(f)
ncdf4::ncvar_get(nc, nc$var[["tp"]]$dim[[2]]$name)
#[1] 3187500 3162500 3137500 3112500 3087500 3062500 3037500 3012500 2987500 2962500 2937500 2912500 2887500 2862500
#[15] 2837500 2812500 2787500 2762500 2737500 2712500 2687500 2662500 2637500 2612500 2587500 2562500 2537500 2512500
#[29] 2487500 2462500 2437500 2412500 2387500 2362500 2337500 2312500 2287500 2262500 2237500 2212500 2187500 2162500
#[43] 2137500 2112500
```

That does not look "bottomup", but I need to configure GDAL to get the values in the correct order:

```
library(terra)
setGDALconfig("GDAL_NETCDF_BOTTOMUP", "no")
x <- rast(f)
```

**Comment by rouault** [comment]
GDAL behaves here as designed. The issue is that this netCDF file doesn't implement fully the CF conventions. In particular, the "tp" variable doesn't have a "grid_mapping "attribute that would point to a grid_mapping variable that would define the projection. Consequently GDAL considers the file to be non-georeference, and assume that line 0 of the variable is at the "bottom", which is the usual convention for netCDF files. This file has a contrary organization (but GDAL as said above ignores the "y" variable), hence defining GDAL_NETCDF_BOTTOMUP=no.

You can also pass the IGNORE_XY_AXIS_NAME_CHECKS=YES open option (if terra allows that) that will relax the checks regarding to georeferencing, and will manage to get a geotransform.

```
$ gdalinfo  NETCDF:"tp_GPCC_25_ltmonsum_1951_2000.nc":tp -oo IGNORE_XY_AXIS_NAME_CHECKS=YES | head
Driver: netCDF/Network Common Data Format
Files: tp_GPCC_25_ltmonsum_1951_2000.nc
Size is 52, 44
Origin = (3450000.000000000000000,3200000.000000000000000)
Pixel Size = (25000.000000000000000,-25000.000000000000000)
Metadata:
  NC_GLOBAL#contact=Bastian Klein (klein@bafg.de)
  NC_GLOBAL#institution=Federal Institute of Hydrology www.bafg.de
  NC_GLOBAL#source=GPCC climatology (1951-2000) 0.25 Degree interpolated to a 25 km grid with Thiessen polygons
  NC_GLOBAL#title=Interpolated GPCC climatology (1951-2000) for Central Europe
```

**Comment by rhijmans** [comment]
Thanks, that works indeed; and is much better than setting the configuration.

```
f <- "tp_GPCC_25_ltmonsum_1951_2000.nc"
library(terra)
x <- rast(f, opts="IGNORE_XY_AXIS_NAME_CHECKS=YES")
```

**Comment by 1358943896** [comment]
@rouault hello, I have another similar problem. I have a netcdf file like this, it doesn't implement fully the CF conventions. Dimensions of variable "ds" don't follow the rules [P,T,Y,X]. gdal assume  that dimension "expver" represents x-axis and dimension "long" represents y-axis.Can gdal parse long and lat dimensions into x-axis and y-axis?
![image](https://github.com/OSGeo/gdal/assets/74649143/0bed4463-ef50-4744-9541-0eeb8dee0b4a)
