### ISSUE TITLE
Spatial filtering of multipart polygons within a shapefile dataset broken

### ISSUE THREAD

**Issue by nirvn** [OSGeo/gdal#8481]
## Expected behavior and actual behavior.

OGR appears to have regressed in filtering of multipart polygons within a shapefile dataset. This was reported in QGIS () but I can replicate using ogrinfo.

Spatial intersection of a multipart polygon when doing spatial filtering will only work if the spatial extent intersects within the bounding box of the first part of a multipart polygon. 

## Steps to reproduce the problem.

Decompress the two datasets (blah.shp and blah.gpkg) in this ZIP file:
[blah.zip](https://github.com/OSGeo/gdal/files/12733542/blah.zip)

Type the following command against the shapefile dataset:
`ogrinfo -so -spat 0.40 -0.11 0.43 -0.09 blah.shp blah`

Notice the feature count (wrongly) reported as 0, even though a multipolygon geometry intersects with the spatial extent provided.

Now try to type in the same command against the geopackage dataset (exact same geometry, crs, etc.):
`ogrinfo -so -spat 0.40 -0.11 0.43 -0.09 blah.gpkg blah`

The feature count will be (correctly) reported as 1.

## Operating system

Ubuntu 23.10

## GDAL version and provenance

GDAL 2.7.1 from the main ubuntu repository

**Comment by nirvn** [comment]
... actually, the geometry in there is a one part polygon with inner rings located outside of the polygon. It could well be an issue downstream with QGIS for allowing a broken geometry.

**Comment by agiudiceandrea** [comment]
It looks like the issue (originally reported at https://github.com/qgis/QGIS/issues/54537) occurs using QGIS with GDAL/OGR >= 3.7 and it seems to me it is about the writing of additional part in an ESRI Shapefile layer: the added "part" is added as an interior ring instead of an additional part.

To replicate the issue: using QGIS with GDAL/OGR >= 3.7, just create a polygonal ESRI Shapefle layer, start Editing the layer, draw a polygon geometry using the "Add Polygon Feature" tool, select such polygon geometry, then use the "Add Part" tool to add a part, then save the editing.

Here is an ESRI Sahpefile layer created with QGIS 3.22 on Windows (GDAL/OGR 3.5): [addparttest_QGIS322_GDAL35.zip](https://github.com/qgis/QGIS/files/12572613/addparttest_QGIS322_GDAL35.zip)

- geom_to_wkt(@geometry): `MultiPolygon (((10.9 40.3, 11.7 40.3, 11.7 39.7, 10.9 39.7, 10.9 40.3)),((12.4 40.3, 13.2 40.3, 13.2 39.7, 12.4 39.7, 12.4 40.3)))`
- num_geometries( @geometry): 2 | num_rings( @geometry): 2 |  num_interior_rings( @geometry): 0
- ogrinfo: `MULTIPOLYGON (((10.9 40.3,11.7 40.3,11.7 39.7,10.9 39.7,10.9 40.3)),((12.4 40.3,13.2 40.3,13.2 39.7,12.4 39.7,12.4 40.3)))`

Here is an an ESRI Sahpefile layer created with QGIS 3.28 on Windows (GDAL/OGR 3.7): [addparttest_QGIS328_GDAL37.zip](https://github.com/qgis/QGIS/files/12568546/addparttest_QGIS328_GDAL37.zip)
The WKT representation of the geometry in such layer is:

- geom_to_wkt(@geometry): `MultiPolygon (((10.9 40.3, 11.7 40.3, 11.7 39.7, 10.9 39.7, 10.9 40.3),(12.4 40.3, 12.4 39.7, 13.2 39.7, 13.2 40.3, 12.4 40.3)))`
- num_geometries( @geometry): 1 | num_rings( @geometry): 2 |  num_interior_rings( @geometry): 1
- ogrinfo: `POLYGON ((10.9 40.3,11.7 40.3,11.7 39.7,10.9 39.7,10.9 40.3),(12.4 40.3,12.4 39.7,13.2 39.7,13.2 40.3,12.4 40.3))`


The tests made on Windows show that:

1. QGIS >=3.28.6 (GDAL 3.7), QGIS 3.30.3 (GDAL 3.7), QGIS >=3.32.0 (GDAL 3.7) and QGIS 3.33 dev master branch (GDAL 3.7): the issue occur

2. QGIS <=3.28.5 (GDAL 3.6) and QGIS <=3.30.2 (GDAL 3.6): the issue doesn't occur
 
3. QGIS 3.22 (GDAL 3.5): the issue doesn't occur

**Comment by rouault** [comment]
GDAL behaves correctly here. The new behaviour of GDAL 3.7 was due to 72c640f3bac where GDAL now trusts the input geometry to be Simple Feature compliant to avoid issues in some situations. The old behaviour where the shapefile writer does topological analysis of rings (which can fail sometimes) can be restored with setting the SHAPE_REWIND_ON_WRITE config option to YES 

``MultiPolygon (((10.9 40.3, 11.7 40.3, 11.7 39.7, 10.9 39.7, 10.9 40.3),(12.4 40.3, 12.4 39.7, 13.2 39.7, 13.2 40.3, 12.4 40.3)))`` is an invalid multipolygon. The second ring here declared as an inner ring of the first one is not an inner ring, but an outer ring

**Comment by rouault** [comment]
Cf https://github.com/qgis/QGIS/pull/54761 and https://github.com/OSGeo/gdal/pull/8483
