### ISSUE TITLE
inconsistent behavior of GeoJSON-drivers when dealing with multiple layers

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#8665]
## Expected behavior and actual behavior.
When trying to convert a dataset with multiple layers, the normal _GeoJSON_ driver complains, while _GeoJSONseq_ consequently appends the layers.

```
ERROR 1: Layer 'layer_two' does not already exist in the output dataset, and cannot be created by the output driver.
ERROR 1: Layer 'layer_three' does not already exist in the output dataset, and cannot be created by the output driver.
```
I'm aware that GeoJSON files can only have one layer. It is therefore questionable whether the behavior of GeoJSONseq is a bug. If so, it is a good error. It would be best if both drivers were simply given an additional entry `ogr_layer` containing the original layer. Both drivers could then adopt the aggregating behavior of GeoJSONseq.

## Steps to reproduce the problem.
```
ogr2ogr -F GeoJSON /vsistdout/ multilayer.gpkg
ogr2ogr -F GeoJSONseq /vsistdout/ multilayer.gpkg
```
## Operating system
Debian Bookworm, 64-bit

## GDAL version and provenance
- GDAL 3.6.2, released 2023/01/02
- GDAL 3.8.0beta1, released 2023/11/04

**Comment by rouault** [comment]
The current behavior is probably historical and I'd be hesitant, at least by default, to allow multiple layers in a GeoJSON file.
That said, the JSON-FG spec has standardized a "featureType" member and the new OGR JSONFG driver allows multiple layers by writing the layer name into it, so that's now an easy way of solving this.
Handling several layers in reading in the GeoJSON driver would require significant restructuring of the driver

**Comment by tobwen** [comment]
Okay, so I'll go for this to produce GeoJSONseq with artificial CRS, until JSON-FG gets acepted:

```sh
ogr2ogr -F JSONFG /vsistdout/ mvt/15 -lco WRITE_GEOMETRY=NO \
| awk 'NR > 1 && /^{/ { sub(/,$/, ""); print }' \
| jq -c '.type = "Feature" | .properties.ogr_layer = .featureType | .geometry = .place | del(.coordRefSys, .featureType, .place, .time)' > output.json
```
