### ISSUE TITLE
`mvt_id` is null

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#8669]
## Expected behavior and actual behavior.
Seems like `mvt_id` can be null, when it's not defined in the MVT file at all. 

If this is the case, there's a different behavior in drivers :
- _GPKG_ driver writes out `mvt_id (Integer64) = (null)` to each feature, but
- _GeoJSONseq_ and _JSON-FG_ don't.

## Steps to reproduce the problem.
```
# license 1: CC BY 4.0: © GeoBasis-DE / BKG (2023) CC BY 4.0
# license 2: DL-DE->BY-2.0: © GeoBasis-DE / BKG (2023) dl-de/by-2-0

curl -kJLOR https://sgx.geodatenzentrum.de/gdz_basemapde_vektor/tiles/v1/bm_web_de_3857/6/34/20.pbf

ogr2ogr -F GeoJSONseq 20.geojsons 20.pbf
ogrinfo -ro -al 20.geojsons

ogr2ogr -F GPKG 20.gpkg 20.pbf
ogrinfo -ro -al 20.gpkg
```
## Operating system
Debian Bookworm, 64-bit

## GDAL version and provenance
- GDAL 3.6.2, released 2023/01/02
- GDAL 3.8.0beta1, released 2023/11/04

**Comment by rouault** [comment]
> Seems like `mvt_id` can be null

Actually, mvt_id is not null, it is unset. OGR has those 2 different concepts. A unset field is a field not mentionned at all in a feature content (think has a GeoJSON property not present at all). A null field is a field explicitly set to null ( `"foo": null`` in JSON )
This distinction doesn't necessarily exist in all formats. In particular in SQL database, the only concept that exists is NULL, since the column is always there. Hence the behaviour you observe.

**Comment by tobwen** [comment]
Thanks.

Then I have to drop the column in every layer.
