### ISSUE TITLE
GDAL_HTTP_PROXY currently affects both http and https URL. Having separate options could be useful

### ISSUE THREAD

**Issue by guydou** [OSGeo/gdal#878]
When setting `GDAL_HTTP_PROXY` it affects url using https as well

While the env variable `http_proxy` affects only http urls, and `https_proxy` affects only https urls.

It is relevant to my usecase,
I have server that uses tiffs on a cloud storage. 
I want the http urls to go through a forward proxy that caches the requests, 
I can't use that forward proxy on https urls.
So I want the http requests to use the proxy and the https requests not use the proxy, 
as a workaround I am using `http_proxy` setting

**Comment by drnextgis** [comment]
@rouault I've started to work for this issue and need some guidance. I was able to implement support of different environment variable for https URLs in case of using `/vsicurl`, code example: https://github.com/drnextgis/gdal/commit/e3aa8c5a38a9de4fe9eeb8a33dab6e67965b193d. But for me it doesn't look like a good way to solve the original issue. Because using this approach I need to put the same code to different files (e.g. to cpl_vsil_az.cpp). One of the possible solution is to change the signature of CPLHTTPSetOptions function in this way:
```
void *CPLHTTPSetOptions(void *pcurl, const char papzUrl,
                       const char * const* papszOptions)
```
What do you think? Maybe I miss something and you can propose a better option.

**Comment by rouault** [comment]
I'm fine if you add a const char* pszURL (note the fix in type and naming convention) argument to CPLHTTPSetOptions(). The function should then call ``curl_easy_setopt(http_handle, CURLOPT_URL, pszURL )```. We currently have the common pattern of setting CURLOPT_URL and calling CPLHTTPSetOptions() afterwards

**Comment by drnextgis** [comment]
Using this PR it is possible to set `GDAL_HTTPS_PROXY=''` for preventing of usage proxy which comes from `GDAL_HTTP_PROXY`.
