### ISSUE TITLE
OFTTime field type in Geopackage (GPKG)

### ISSUE THREAD

**Issue by michkowalczuk** [OSGeo/gdal#8850]
## Expected behavior and actual behavior.

Shouldn't the `OFTTime` field type be written like `OFTDateTime` in the Geopackage driver?
This would improve the support for this type, as GPKG only supports Time and DateTime.
Now if we add `OFTTime` field to GPKG and then read it again, we will get only `OFTString`.

The problem is already known, because for some reason python test are commented for this type :-)
https://github.com/OSGeo/gdal/blob/32bb33a6b7fff7b5d238760fff17548c8736df4c/autotest/ogr/ogr_gpkg.py#L2651

## Steps to reproduce the problem.

1. Create a new GPKG dataset
2. Add field with `OFTTime`, `OFTDate` and `OFTDateTime`
3. Close the dataset
4. Check types in QGIS or DB viewer

## Operating system

Windows 11 x64

## GDAL version and provenance

GDAL 3.7.2

**Comment by jratike80** [comment]
I think that you should not add OFTTime field into GeoPackage because it is not supported.
There are two alternatives:
save as string (current behavior)
save as DateTime(suggested behavior)

OFTTime fields are formatted as "HH:MM:SS[.sss]" 
OFTDateTime fields are formatted with "YYYY/MM/DD HH:MM:SS[.sss]+ZZ"

Converting into DateTime would add the date part with some defaults (now?) but that information would be artificial. For my mind string saves the original data better.

Autotests seem to test the Oracle Spatial driver. Oracle tends to have its own peculiarities.

**Comment by michkowalczuk** [comment]
> I think that you should not add OFTTime field into GeoPackage because it is not supported. There are two alternatives: save as string (current behavior) save as DateTime(suggested behavior)
> 
> OFTTime fields are formatted as "HH:MM:SS[.sss]" OFTDateTime fields are formatted with "YYYY/MM/DD HH:MM:SS[.sss]+ZZ"
> 
> Converting into DateTime would add the date part with some defaults (now?) but that information would be artificial. For my mind string save the original data better.
> 
> Autotests seem to test the Oracle Spatial driver. Oracle tends to have its own peculiarities.

Probably you are right with defaults for date...
BTW, I fixed link to gpkg test.
