### ISSUE TITLE
man ogr2ogr needs to mention --help-general and --long-usage

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8853]
Please make sure the ogr2ogr man page mentions:
> Use --help-general and --long-usage to see several items not
mentioned on this man page.

**Comment by jidanni** [comment]
Yes.
All I know is --long-help is hidden in --help,
and e.g., --config is hidden in --long-help.
In other words, someone planning to print out the
complete usage, who would normally assume the man
page has more than the --help stuff, would find
themselves with an incomplete picture.

**Comment by jratike80** [comment]
You mean that instead of 
`Usage: ogr2ogr [--help] [--help-general]`
there could read
`Usage: ogr2ogr [--help] [--help-general] [--long-help]`.

That feels reasonable. Otherwise I like that the help page should be compact and list the most common options and it is acceptable that for understanding the whole usage users must read https://gdal.org/programs/ogr2ogr.html.
