### ISSUE TITLE
Docker images for rc1/rc2/.. should use distinct tag

### ISSUE THREAD

**Issue by pjonsson** [OSGeo/gdal#8977]
## Expected behavior and actual behavior.

Dependabot can update Dockerfiles, so I just saw PRs for updating to GDAL 3.8.2. I can only find a 3.8.2rc1 tag in the repository, so it seems 3.8.2 is not released yet.

It would be nice to give the release candidate images a distinct tag, just like it's done in the repository, so Dependabot will only create a 3.8.2 update PR after GDAL 3.8.2 is released.

## Steps to reproduce the problem.

Look for images tagged with "3.8.2" at https://github.com/OSGeo/gdal/pkgs/container/gdal/versions?filters%5Bversion_type%5D=tagged

## Operating system

Docker image.

## GDAL version and provenance

3.8.2 docker image through Dependabot.

**Comment by rouault** [comment]
Well, I'm doing the current procedure to have the Docker images ready when the final version is announced. If people use them in advance, well, I don't really see an issue. But I'm not keen doing distinct RC and final Docker images.  Note that the Docker images are sometimes refreshed after having been published, keeping the same Docker tag, when someone insists to do so because of some vulnerability in a component of the OS, so their versioning isn't as strict as the GDAL source code itself.

**Comment by pjonsson** [comment]
Would it be possible to have the release job run a `docker tag image:version_rcX image:version` instead so we only get the final RC image masquerading as the release image? This shrinks the window for accidentally running release candidates, and by the time Dependabot has made pull requests and the pull requests have been merged, the odds are that the release image has been pushed.

**Comment by rouault** [comment]
> Would it be possible to have the release job

There's no automated job. Producing the Docker images involves spinning a beefy VM.

> run a docker tag image:version_rcX image:version instead so we only get the final RC image masquerading as the release image?

That would be more complicated than that since the Docker images are bi-architecture and generated using docker builldx. Re-tagging them would require pulling the 2 to recreate manifests.

to avoid overcomplicating the release process, I'll just stick with creating the Docker images after the source tag has been set

**Comment by pjonsson** [comment]
Wonderful, thank you!
