### ISSUE TITLE
ECW not supported

### ISSUE THREAD

**Issue by PabloMeseguerEsbri** [OSGeo/gdal#9047]
GDAL version 3.0.4 is not supporting ECW (v3) files

**Comment by jratike80** [comment]
GDAL does not support ECW natively. GDAL does have a driver that is utilizing a proprietary ECW SDK. Because of the not open source components the the driver is not built by default. If your GDAL version has the driver you can find more details about it with this command:

```
gdalinfo --format ECW
Format Details:
  Short Name: ECW
  Long Name: ERDAS Compressed Wavelets (SDK 5.5)
...
```
BTW, your GDAL version 3.0.4 is old, the current version is 3.8. The GDAL project does not support old versions.

**Comment by PabloMeseguerEsbri** [comment]
I am with this old version as I needed to do while working inside a docker container.

```
sudo apt-get update
sudo apt-get install libgdal-dev python3-gdal
python from osgeo import gdal
```

Do you suggest to install de the SDK inside the docker?

**Comment by jef-n** [comment]
> Do you suggest to install de the SDK inside the docker?

You need to build GDAL with the SDK.

**Comment by rouault** [comment]
cf https://github.com/OSGeo/gdal/blob/895e9fbd63b2aa22471f4f8c69efd5ba4e700e9c/.github/workflows/ubuntu_20.04/Dockerfile.ci#L156 and https://github.com/OSGeo/gdal/blob/master/.github/workflows/ubuntu_20.04/build.sh#L14 for a build recipee for GDAL >= 3.5 building it against the old ECW SDK 3.3. 

If using SDK 5.5, then pass to CMake something like -DECW_ROOT=/opt/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only
