### ISSUE TITLE
gdalinfo proj:shape order seems wrong

### ISSUE THREAD

**Issue by jdries** [OSGeo/gdal#9337]
## Expected behavior and actual behavior.

In stac, proj:shape is defined as having Y,X order:
https://github.com/stac-extensions/projection?tab=readme-ov-file#projshape

> An array of integers that represents the number of pixels in the most common pixel grid used by the Item Asset objects. The number of pixels should be specified in Y, X order.

When doing gdalinfo, it seems to be returned in X,Y order.

## Steps to reproduce the problem.

`gdalinfo -json /vsicurl/https://download.osgeo.org/geotiff/samples/usgs/c41078a1.tif  `

Contains:
```
  "stac":{
    "proj:shape":[
      7202,
      5593
    ],
...
}
```

While for this geotiff, 7202 is the width, and 5593 is height, so expected shape according to proj definition would be [5593,7202].

## Operating system

Arch Linux

## GDAL version and provenance

GDAL 3.8.4, released 2024/02/08

**Comment by jratike80** [comment]
Please edit your example and add `-json` option or otherwise there is no "stac" section.
`gdalinfo /vsicurl/https://download.osgeo.org/geotiff/samples/usgs/c41078a1.tif -noct -json`.

So for GDAL the size is pixels-rows (width-height) 

 ```

"size":[
    7202,
    5593
  ],
```
but you interpret that for stac it should always be reversed
  
```
   "stac":{
    "proj:shape":[
      5593,
      7202
    ],
```
I hate Y and X because it is impossible to know what they mean if they are not explained. Now the definition is "Number of pixels in Y and X directions for the default grid" but there is no direct definition for the "default grid".  Maybe, and hopefully, the meaning of X and Y is always the same as in bbox:

> coordinates of upper right corner, , e.g., [west, south, east, north], [xmin, ymin, xmax, ymax], [left, down, right, up], or [west, south, lowest, east, north, highest].

**Comment by rouault** [comment]
> but you interpret that for stac it should always be reversed

@jratike80 I guess this is to follow the numpy or ND-array convention where when you access a 2D array the first dimension is the vertical one.
