### ISSUE TITLE
ogr2ogr: catch invalid -spat arguments better

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9623]
### Feature description

```
ogr2ogr -spat BLA 30 -90 50 orr.csv -dialect SQLITE -sql \
'SELECT XCOORD,YCOORD,POINTID FROM PLSSPoint_GCDB WHERE
POINTID LIKE "UT260060S0020E0%"' file.gdb.zip; echo $?
ERROR 1: Invalid geometry field index : 0
0
```
Maybe say
> ERROR 1: Invalid geometry field index : 0 (xmin)

or
> ERROR 1: Invalid geometry field index : 0 ("BLA") (xmin)

### Additional context

And more importantly, set $? to non-zero!

**Comment by rouault** [comment]
The issue about BLA being silently mis-parse has been fixed in master by the switch to the argparser module. There's now an error message.
The error message that was emitted (and didn't result in an error return code) was due to trying to apply a spatial filter to a layer that has no geometry field (as you only selected attribute fields). Fixed per https://github.com/OSGeo/gdal/pull/9645
